- readme.md
Just some simple instructions on how to make codecept available in the $PATH
> Instructions how to make Codecept available in $PATH

- src/Codeception/Module/MongoDb.php
- tests/unit/Codeception/Module/MongoDbTest.php
Added methods: 
**grabCollectionCount**: _returns the documents count in a collection, possible to filter by criteria_
**seeElementIsArray** and **seeElementIsObject**: _useful to check that an element in a document has the correct type_
> Added some useful methods, with tests

- src/Codeception/Module/MongoDb.php
- tests/unit/Codeception/Module/MongoDbTest.php
Assert number of docs in a collection.
```
$I->countInCollection('users', 2);
$I->countInCollection('users', 1, array('name' => 'miles'));
```
> Feature, MongoDb Count In Collection

- src/Codeception/Module/Facebook.php
- tests/unit/Codeception/Module/FacebookTest.php
Add a new method to obtain the user id.
> Get the id of a Facebook test user

- src/Codeception/PHPUnit/ResultPrinter/template/scenario.html.dist
- src/Codeception/PHPUnit/ResultPrinter/template/scenarios.html.dist
Implement issue #1669 
Added a 'toolbar' for easy filtering.
Click on every statusCode toogle visibility of given status, additionally there is a "Show all" button.
> Filter HTML report.

- src/Codeception/Lib/Connector/Yii2.php
This PR is also a fix for #1262
> Yii2: Fixed output buffer level down to zero if exception occurs

- composer.json
- composer.lock
- src/Codeception/Module/REST.php
- src/Codeception/Util/JsonArray.php
- tests/unit/Codeception/Module/RestTest.php
- tests/unit/Codeception/Util/JsonArrayTest.php
- Added support for jsonPath v0.2.*
- New method to test if json does not match jsonPath. `dontSeeResponseJsonMatchesJsonPath()`
Close Codeception/Codeception#1700
> Support JsonPath v0.2

- src/Codeception/Module/Laravel5.php
This pull request fixes an issue with domain-specific routes in the Laravel 5 module that was reported to me. I also added a test to the sample app that covers this issue. I will push this test to the sample app repository after the fix is included in Codeception, to prevent failing tests.
> Fixed issue with domain-specific routes

- src/Codeception/Lib/Connector/Laravel4.php
See also https://github.com/Codeception/Codeception/issues/1680
> Laravel4: fix problem with middleware not being loaded

- src/Codeception/Module/Yii2.php
> Fix Yii 2 haveRecord not inserting unsafe fields

- src/Codeception/Module/Asserts.php
- src/Codeception/Util/Shared/Asserts.php
- tests/unit/Codeception/Module/AssertsTest.php
add assert function `assertSame`
> add func assertSame

- src/Codeception/Module/REST.php
> add request headers logging

- src/Codeception/Lib/Connector/Yii2.php
This allows to send Xml payload:
```php
$i->haveHttpHeader('Content-Type', 'application/xml');
$i->sendPOST('/v1/door/new-goods', $xmlString);
```
> Pass body request into yii2 request

- docs/modules/SOAP.md
- src/Codeception/Module/SOAP.php
Fixes #1784 - With this changes the output buffer use can be disabled by user.
> Extend SOAP module sendRequest handling

- src/Codeception/Module/Laravel5.php
Sync changes from my own repository of the Laravel 5 module. 
There is no need to release a new version, these changes can just go out when you plan a new release yourself.
> Sync changes

- src/Codeception/SuiteManager.php
This is a fix for this issue:
https://github.com/Codeception/Codeception/issues/1830
> enable group listener for grouping with annotation

- src/Codeception/Module/Laravel5.php
Hey,
i've update codeception and got an error because of brace.
with the issue #1783
i just replace it with the missing one
thanks you !
> Fix Laravel5 Module

- src/Codeception/Lib/Connector/Phalcon1.php
- src/Codeception/Module/Phalcon1.php
* Fixed getting model identity
* Update doc
* Cleanup CS
> Update Phalcon1 module

- src/Codeception/Lib/InnerBrowser.php
- tests/data/app/view/form/example5.php
- tests/unit/Codeception/Module/TestsForWeb.php
URLs were not properly constructed for GET form submissions on URLs requested with query parameters.  Fixes #1891
(waiting for Travis scan to merge).
> Fixes GET requests on URLs with query params

- src/Codeception/Lib/Connector/Phalcon1.php
- src/Codeception/Module/Phalcon1.php
+ Cleanup, minor improvement and CS fixes
> Phalcon1: Fixed declaration of PhalconMemorySession::get

- src/Codeception/Command/GenerateScenarios.php
- src/Codeception/Scenario.php
- tests/cli/GenerateScenariosCept.php
> Fix g:scenarios --single-file missing linebreaks between scenarios

- src/Codeception/Module/Laravel5.php
just some simple formatting for the docs to match the other sections. no functionality changes
> add correct formatting for seeRecord() method

- src/Codeception/Lib/Generator/Cept.php
- src/Codeception/Lib/Generator/Cest.php
This pull request fixes issue described in the #1925 ticket.
> Fix double slashes issue in the namespaces

- src/Codeception/Lib/Connector/ZF1.php
> Pass headers to ZF1 correctly

- src/Codeception/Lib/Driver/Db.php
- tests/data/dumps/mysql.sql
- tests/unit/Codeception/Lib/Driver/MysqlTest.php
> Quote table name in Db::getPrimaryKeyColumn and Db::deleteQueryMethods (to 2.0 branch)

- CONTRIBUTING.md
I got the idea from https://github.com/Codeception/codeception.github.com/issues/17#issuecomment-104038409
> Add a note about how to contribute documentation

- src/Codeception/Module/Db.php
For foreign keys compatibility.
Issue: #1942
> Db::haveInDatabase. Reverse order of removing inserted records.

- src/Codeception/Lib/Connector/ZF2.php
I fixed passing of request uri and request headers to ZF2 application.
All changes have been tested  by using https://github.com/Naktibalda/codeception-rest-testcase in https://github.com/Naktibalda/codeception-zf2-tests site.
> Zf2 connector improvements

- src/Codeception/TestCase/Test.php
- tests/unit/Codeception/TestCase/TestTest.php
Added getReportFields to the Codeception\TestCase\Test class
> Fix for #1964. Added Interfaces\Reported implementation to the Codeception\TestCase\Test class

- src/Codeception/Module/Yii2.php
It's currently kind of hard to read the docs here: http://codeception.com/docs/modules/Yii2#amOnPage
> Tweaked Yii2 module DocBlock to show better in the docs

- CONTRIBUTING.md
- readme.md
This pull updates the readme and contribution files based on @Ragazzo suggestion at #1948
This is the same contribution sent at #1969 this time against 2.0 branch as suggested by @DavertMik
> Update Contributing instructions in 2.0

- tests/unit/Codeception/Lib/Driver/MysqlTest.php
I moved initial setup to setUpBeforeClass, load to setUp, cleanup to tearDown
> MysqlTest refactoring

- src/Codeception/TestCase/Test.php
- tests/cli/UnitCept.php
- tests/unit/Codeception/TestCase/TestTest.php
Added getReportFields to Codeception\TestCase\Test class
> Fix for #1964 Added getReportFields to Codeception\TestCase\Test class

- .travis.yml
- src/Codeception/Lib/Connector/Phalcon1.php
> Updated Phalcon config for Travis CI

- composer.lock
- tests/unit/Codeception/SuiteManagerTest.php
> Event dispatcher upgrade

- composer.lock
This is a temporary fix for #2012 which is breaking 2.0 builds.
> Restored composer.lock

- src/Codeception/Command/Bootstrap.php
- src/Codeception/Command/GenerateStepObject.php
- src/Codeception/Command/SelfUpdate.php
- tests/data/claypit/tests/dummy/AnotherCest.php
DialogueHelper is deprecated. #2012
> Updated bootstrap, self-update and generate:stepobject to use QuestionHelper instead of DialogueHelper

- src/Codeception/Lib/Connector/ZF1.php
- src/Codeception/Lib/Connector/ZF2.php
I copied content header fix from Guzzle to ZF1 and ZF2 connectors
> Content headers fix for ZF1 and ZF2 connectors

- src/Codeception/Module/Symfony2.php
To fix entity manager closed error when running all tests together.
> Create a new Symfony2 kernel for every test

- src/Codeception/Module/WebDriver.php
- tests/unit/Codeception/Module/WebDriverTest.php
Prevent fatal error and log stacktrace when webDriver is not set #2046
> Fixed issue 2046

- src/Codeception/Module/REST.php
- tests/unit/Codeception/Module/RestTest.php
Reverted unnecessary and not working fix inspired by scrutinizer #1992
Improved coding style,
Eliminated assignment by reference.
> Reverted scrutinizer fix in REST module

- src/Codeception/Module/Db.php
> Fixed int assertion

- src/Codeception/Util/JsonArray.php
- tests/data/rest/index.php
- tests/unit/Codeception/Module/PhpBrowserRestTest.php
- tests/unit/Codeception/Util/JsonArrayTest.php
I improved JsonArray to compare repeated values correctly. #2070
> Solved Issue 2070

- src/Codeception/Module/Asserts.php
- src/Codeception/Util/Shared/Asserts.php
- tests/unit/Codeception/Module/AssertsTest.php
It was implemented assertRegExp and assertNotRegExp from PHPUnit_Framework_Assert.
> Implemented assertRegExp and assertNotRegExp

- src/Codeception/Module/PhpBrowser.php
- tests/unit/Codeception/Module/PhpBrowserRestTest.php
> Fixed issue #2075

- src/Codeception/Util/Stub.php
- tests/unit/Codeception/Util/StubTest.php
> Reproduced and fixed issue 2082

- src/Codeception/Module/Asserts.php
- src/Codeception/Util/Shared/Asserts.php
- tests/unit/Codeception/Module/AssertsTest.php
Implemented assertFileExists and assertFileNotExists, as did their tests.
I also put some more tests other asserts that were not being tested.
> Implemented assertFileExists and assertFileNotExists.

- src/Codeception/Module/Phalcon1.php
* Fixed Exceptions
* Added missed setter for `Phalcon1::$bootstrapFile` in `Phalcon1::_initialize`
* Added `Phalcon::grabServiceFromDi`
* Fixed doc (added missed `?>`)
* Changed maintainer
> Fixed Phalcon1 module

- src/Codeception/Lib/Connector/Guzzle.php
- src/Codeception/Lib/Connector/Guzzle6.php
- tests/data/app/controllers.php
- tests/data/app/index.php
- tests/data/app/view/redirect_params.php
- tests/unit/Codeception/Module/PhpBrowserTest.php
> parse meta refresh url with htmlspecialchars_decode

- src/Codeception/Extension.php
Fixed error in \Codeception\Extension::getSubscribedEvents
> Fixed error in \Codeception\Extension::getSubscribedEvents

- src/Codeception/Lib/Driver/SqlSrv.php
SqlSrv uses a proper function to get primary column.
> Update SqlSrv.php for a primary column function

- .travis.yml
- composer.lock
- src/Codeception/Coverage/SuiteSubscriber.php
- tests/unit/Codeception/Coverage/FilterTest.php
Upgraded Guzzle and enabled code coverage on HHVM
> Fixed hhvm issues

- docs/06-ReusingTestCode.md
I think the code sample is based on ~2.0 version.
> Update code sample in 06-ReusingTestCode:PageObjects

- src/Codeception/Module/Db.php
Issuing a request for the 2.0 branch.
This is a follow up for https://github.com/Codeception/Codeception/pull/2148
> Cleanup should happen only if enabled

- src/Codeception/Module/Db.php
Moving the documentation to the source so it can be generated.
See pull request https://github.com/Codeception/Codeception/pull/2154
> Documenting format of dump.sql

- docs/06-ReusingTestCode.md
> Resend #2156 (Update code sample in 06-ReusingTestCode:PageObjects)

- .travis.yml
- src/Codeception/Lib/Connector/Phalcon.php
- src/Codeception/Module/Phalcon1.php
- src/Codeception/Module/Phalcon2.php
* Enabled Phalcon tests
* Added initial `Phalcon2` module
* `Renamed Codeception\Lib\Connector\Phalcon1` → `Codeception\Lib\Connector\Phalcon`
> Enable Phalcon

- src/Codeception/Command/Run.php
-- is not a valid option
#2200
> Fixed issue #2200

- src/Codeception/Util/Stub.php
- tests/unit/Codeception/Util/StubTest.php
> Fixed Issue 2195

- src/Codeception/Subscriber/Console.php
> Fixed issue #2187

- docs/modules/Asserts.md
- docs/modules/FTP.md
- docs/modules/Filesystem.md
- docs/reference/Stub.md
- src/Codeception/Module/FTP.php
- src/Codeception/Module/Filesystem.php
- src/Codeception/Module/Laravel5.php
- src/Codeception/Module/WebDriver.php
- src/Codeception/SuiteManager.php
- src/Codeception/TestCase/Cest.php
- src/Codeception/Util/Shared/Asserts.php
- src/Codeception/Util/Stub.php
- tests/data/claypit/tests/_support/_generated/AbsolutelyOtherGuyActions.php
- tests/data/claypit/tests/_support/_generated/DumbGuyActions.php
- tests/data/claypit/tests/_support/_generated/OtherGuyActions.php
- tests/data/claypit/tests/_support/_generated/ScenarioGuyActions.php
- tests/data/included/jazz/pianist/tests/_helpers/_generated/TestGuyActions.php
- tests/data/included/jazz/pianist/tests/functional/TestGuy.php
- tests/data/included/jazz/tests/_helpers/_generated/TestGuyActions.php
- tests/data/included/jazz/tests/functional/TestGuy.php
- tests/data/included/shire/tests/_helpers/_generated/TestGuyActions.php
- tests/data/included/shire/tests/functional/TestGuy.php
- tests/data/services/UserModel.php
- tests/support/_generated/CliGuyActions.php
- tests/support/_generated/CoverGuyActions.php
fixing instances of exists vs exist in documentation and strings
> grammar fixes

- src/Codeception/Module/WebDriver.php
Needed to support running tests on a remote server that's behind a proxy
> Add http_proxy and http_proxy_port vars to config

- src/Codeception/Command/GenerateScenarios.php
https://github.com/Codeception/Codeception/issues/1962
> Fix for generate:scenarios in Cest files. See issue #1962

- src/Codeception/Module/Yii2.php
and corrects https://github.com/Codeception/Codeception/pull/1770
> fixes https://github.com/Codeception/Codeception/issues/2110

- src/Codeception/Module/Yii2.php
> fix #2110 for branche 2.1

- src/Codeception/Lib/Connector/Guzzle6.php
- tests/data/app/controllers.php
- tests/data/app/index.php
- tests/unit/Codeception/Module/PhpBrowserTest.php
> Disabled CookieJar strict mode in Guzzle6 connector

- src/Codeception/Module/ZF2.php
Also changed contents of _getEntityManager()
> Added grabServiceFromContainer function

- src/Codeception/Lib/Driver/PostgreSql.php
- tests/data/dumps/postgres.sql
I merged #2191 to 2.0 earlier.
Now I cherry-picked it to 2.1 branch.
> Postgress dollar fix to 2.1

- src/Codeception/Lib/InnerBrowser.php
html_entity_decode() would be more comprehensive? Added ENT_QUOTES to make sure all quotes are handled
> Issue #2034

- docs/10-WebServices.md
> Minor grammatical changes in documentation

- src/Codeception/Module/Phalcon1.php
> Added db->close() on _after to avoid too many connections message

- src/Codeception/Module/Laravel5.php
Add example to amLoggedAs. Clarify $driver param.
> Add example to amLoggedAs.

- src/Codeception/Lib/Connector/Guzzle6.php
> Don't override ConnectException in Guzzle6 connector

- src/Codeception/Lib/InnerBrowser.php
- src/Codeception/Module.php
- src/Codeception/Util/Stub.php
- tests/data/rest/index.php
- tests/unit/Codeception/Module/PhpBrowserRestTest.php
- tests/unit/Codeception/Module/PhpBrowserTest.php
- tests/unit/Codeception/Module/TestsForWeb.php
@DavertMik Could you make one more release of 2.0 ?
> Cherry-picked some compabile changes from 2.1 to 2.0

- src/Codeception/Module/REST.php
Updated doc-blocks of grabDataFromJsonResponse and grabDataFromResponseByJsonPath methods
> [REST] Updated doc-blocks of grabDataFromJsonResponse and grabDataFromResponseByJsonPath methods

- src/Codeception/Lib/InnerBrowser.php
- src/Codeception/Util/PropertyAccess.php
- tests/data/app/controllers.php
- tests/data/app/index.php
- tests/unit/Codeception/Module/PhpBrowserTest.php
Before
```
Running PhpBrowserTest::testHeadersRedirect...
[Response] 200
[Page] http://localhost:8000/info
[Cookies] []
[Headers] {"Host":["localhost:8000"],"Connection":["close"],"X-Powered-By":["PHP/5.5.28-1+deb.sury.org~trusty+1"],"Content-Type":["text/html; charset=UTF-8"]}
PhpBrowserTest::testHeadersRedirect                                                         Ok
```
After
```
Running PhpBrowserTest::testHeadersRedirect...
[Response] 302
[Page] http://localhost:8000/redirect
[Cookies] []
[Headers] {"Host":["localhost:8000"],"Connection":["close"],"X-Powered-By":["PHP/5.5.28-1+deb.sury.org~trusty+1"],"Content-Type":["text/html; charset=UTF-8"],"Location":["/info"]}
[Redirecting to] /info
[Response] 200
[Page] http://localhost:8000/info
[Cookies] []
[Headers] …
```
> [InnerBrowser] Debug redirects

- src/Codeception/SuiteManager.php
It is aimed to fix #2032. I have only tested it locally and looks like it works.
> Preload tests before checking environments; fixes #2032

- src/Codeception/Module/Symfony2.php
Added two new methods to Symfony2 module:
```
$I->amOnRoute ($routeName, array $params)
```
will set your url matching your given route. You can add parameters to your routing call.
```
$I->seeCurrentRouteIs($routeName, array $params)
```
It will check that current url matches given route with specified parameters.
$params argument are always optional.
> Issue 2171

- CHANGELOG.md
- src/Codeception/Module/ZF1.php
Tests: https://github.com/Naktibalda/codeception-zf1-tests/pull/1/files
> Added amOnRoute and seeCurrentRouteIs methods to ZF1 module

- CHANGELOG.md
- src/Codeception/Exception/ExternalUrlException.php
- src/Codeception/Lib/Connector/Lumen.php
- src/Codeception/Lib/Connector/Symfony2.php
- src/Codeception/Lib/Connector/Yii1.php
- src/Codeception/Lib/Connector/Yii2.php
- src/Codeception/Lib/InnerBrowser.php
- src/Codeception/Lib/Interfaces/SupportsDomainRouting.php
- src/Codeception/Module/Laravel4.php
- src/Codeception/Module/Laravel5.php
- tests/data/app/controllers.php
- tests/data/app/index.php
- tests/data/app/view/external_url.php
- tests/unit/Codeception/Module/FrameworksTest.php
#2328
Intercept click() for debugging
Throw exception when framework module tries to open an external URL
> Throw exception when framework module tries to open an external URL 

- CHANGELOG.md
- src/Codeception/Module/ZF2.php
Tests: https://github.com/Naktibalda/codeception-zf2-tests/pull/1
> [ZF2] Added amOnRoute and seeCurrentRouteIs methods to ZF2 module

- src/Codeception/Codecept.php
- src/Codeception/Configuration.php
Sorry, first take was a blindly patch. This is actually tested
> Environment subfolders support

- CHANGELOG.md
- src/Codeception/Lib/InnerBrowser.php
- tests/data/app/controllers.php
- tests/data/app/index.php
- tests/data/app/view/iframe.php
- tests/unit/Codeception/Module/PhpBrowserTest.php
- tests/unit/Codeception/Module/TestsForWeb.php
> Implemented switchToIframe method for InnerBrowser

- src/Codeception/Lib/InnerBrowser.php
- src/Codeception/Lib/Interfaces/Web.php
- tests/data/app/view/info.php
- tests/unit/Codeception/Module/TestsForWeb.php
(will merge after tests)
- 'foreach' returns DOMElements
- Added documentation
- Added test
> Fix for InnerBrowser::grabMultiple

- src/Codeception/Module/Lumen.php
Lumen does not support domain routing.
> Remove getInternalDomains() from Lumen module

- src/Codeception/Module/Symfony2.php
My implementation of getInternalDomains for Symfony2 framework.
I will implement tests this weekend.
> Sf2 get internal domains

- src/Codeception/Lib/Interfaces/Db.php
- src/Codeception/Module/Db.php
Fixes #2389 
I fixed the 404 link to the drivers and moved it below the list of supported drivers. This also brings some minor updates to the doc.
> Improve the Db module documentation

- src/Codeception/Lib/InnerBrowser.php
- src/Codeception/Module/Symfony2.php
- src/Codeception/Module/ZF1.php
> Fixed URL of sendAjaxRequest in verbose output

- CHANGELOG.md
- src/Codeception/Lib/InnerBrowser.php
- tests/data/app/view/info.php
- tests/unit/Codeception/Module/FrameworksTest.php
- tests/unit/Codeception/Module/TestsForWeb.php
@DavertMik You asked me for a way to get out of iframe when I implemented switchToIframe method.
This is one simple way to do that.
> Implemented moveBack method for InnerBrowser

- src/Codeception/Lib/InnerBrowser.php
- tests/unit/Codeception/Module/PhpBrowserTest.php
> Improved exception message thrown when click('name') does not match any elements

- src/Codeception/Scenario.php
- src/Codeception/Step.php
- tests/unit/Codeception/ScenarioTest.php
- tests/unit/Codeception/StepTest.php
Fixes #2280 
The actor is already included in the Step class.
> Fix the double actor mention in the Step html output

- docs/05-UnitTests.md
Copied from https://github.com/Codeception/codeception.github.com/pull/49
> Corrected Specify code example

- RoboFile.php
Fixes https://github.com/Codeception/codeception.github.com/issues/47
> Sort releases by version correctly

- src/Codeception/Lib/Generator/Actor.php
Added reflection based parameter inspection to derive default values; falls back to null.
> Fixing issue #2459 - Default param is always null (v2.0)

- src/Codeception/Lib/Generator/Actor.php
Added reflection based parameter inspection to derive default values; falls back to null.
> Fixing issue #2453 - Default param is always null

- CHANGELOG.md
- src/Codeception/Lib/Connector/Phalcon.php
- src/Codeception/Module/Phalcon1.php
+ Added `seeSessionHasValues`
+ Cleaned `seeCurrentRouteIs`, `amOnRoute`
+ Refactored `PhalconMemorySession`
+ Improved `seeInSession`
> Improved Phalcon modules

- src/Codeception/Lib/Connector/ZF1.php
- src/Codeception/Lib/Framework.php
- src/Codeception/Lib/InnerBrowser.php
- src/Codeception/Module/ZF1.php
- src/Codeception/Module/ZF2.php
> Implemented getInternalDomains for ZF1

- src/Codeception/Command/GenerateHelper.php
- src/Codeception/Lib/Generator/Helper.php
This is the same patch from the abandoned #2487, only applied to proper branch.
> Add support for nested helpers

- src/Codeception/Lib/Interfaces/Web.php
Just added some better documentation to clarify how `see()` and `dontSee()` work, especially in PhpBrowser.  I hope this is the right place to put them.
> Clarified documentation on the inner workings of `see()` and `dontSee()`

- docs/modules/PhpBrowser.md
- src/Codeception/Lib/Interfaces/Web.php
I found that `submitForm()` was a little confusing to me at first, so I've updated the documentation to hopefully help out others.
> Improved documentation for PhpBrowser->submitForm()

- CHANGELOG.md
- src/Codeception/Module/PhpBrowser.php
- tests/unit/Codeception/Module/PhpBrowserTest.php
> Set curl options for Guzzle6 correctly

- src/Codeception/Lib/GroupManager.php
Bugfix issue #2550
Replaces double slash by one.
> Bugfix groups by directory

- .travis.yml
As advised in https://github.com/yiisoft/yii2-app-basic/issues/36
> Bumped fxp/composer-asset-plugin up to ~1.1.1

- src/Codeception/Step.php
- tests/unit/Codeception/StepTest.php
#2537 fix
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/codeception/codeception/2538)
> Lambda function step output

- src/Codeception/Lib/Connector/Yii2.php
> Yii2: Don't set body parts if raw body is provided

- src/Codeception/Module/REST.php
Use the same message as in https://github.com/Codeception/Codeception/blob/4ee596129d5d41dc69b0ddf13c162a86037b3b7f/src/Codeception/Util/JsonArray.php
> Use json_last_error_msg in seeResponseIsJson

- docs/06-ReusingTestCode.md
Comma was missing in example code
> Typo fixed in 06-ReusingTestCode

- src/Codeception/Module/Symfony1.php
Updated with PHPUnit_Framework_Assert::contains
> Fix bad call to PHPUnit_Framework_Assert::pageContains

- docs/11-Codecoverage.md
copy/pasting the example didn't work - adding "enabled: true" fixes that
> "enabled: true" was missing

- src/Codeception/Module/WebDriver.php
This is to allow to add ssl proxy settings.
https://github.com/facebook/php-webdriver/wiki/HowTo-Work-with-proxy
> can add ssl proxy setting

- src/Codeception/Util/JsonArray.php
- tests/unit/Codeception/Util/JsonArrayTest.php
> Modified JsonArray::sequentialArrayIntersect to return complete matches only

- .travis.yml
- composer.json
- composer.lock
- tests/cli/ExtensionsCest.php
- tests/cli/RunEnvironmentCest.php
- tests/cli/WildcardIncludeCest.php
* Travis to test different Symfony versions
* CssSelector's old deprecated API added (for BC)
> Symfony 3.0 compatibility

- ext/README.md
- ext/Recorder.php
in config set `animate_slides` to false to disable left-right sliding animation between screenshots in output.html
> make carousel slide animation configurable

- src/Codeception/Lib/Connector/Guzzle.php
- src/Codeception/Lib/Connector/Guzzle6.php
- src/Codeception/Lib/Connector/ZF1.php
- src/Codeception/Lib/Connector/ZF2.php
- src/Codeception/Lib/Connector/ZendExpressive.php
- src/Codeception/Module/REST.php
- tests/data/rest/index.php
- tests/unit/Codeception/Module/PhpBrowserRestTest.php
Reverted incorrect fix for issue #1650
Removed unnecessary setting of HTTP_HOST from Guzzle and Zend connectors
> Removed unnecessary code which was setting HTTP_HOST in various places

- .travis.yml
- tests/web/WebDriverTest.php
* improved Phalcon compilation time
* moved WebDriver tests to web suite
> Travis CI improvements

- .travis.yml
- CHANGELOG.md
- src/Codeception/Module/Asserts.php
Working module is better than elegant module.
> Made Asserts module work on HHVM

- src/Codeception/Lib/Connector/Laravel5.php
- src/Codeception/Module/Laravel5.php
My application relies on particular URLs in order to set context, so it would be nice to be able to set the URL from the config file.
> allow Laravel5 application url to be set in config

- .gitignore
- src/Codeception/Module/REST.php
Added an annotation to make sure an XML method is pulled in when only part xml is specified.
> Updated gitignore and fixed 2688

- src/Codeception/Util/JsonArray.php
- tests/unit/Codeception/Util/JsonArrayTest.php
> Reproduced and fixed another JsonArray matching issue

- src/Codeception/Lib/GroupManager.php
Convert double backslash to single backslash.
See #2550 and https://github.com/Codeception/Codeception/pull/2551#issuecomment-167756694
> Bugfix groups by directory for Windows

- src/Codeception/Module/Symfony2.php
> [Symfony2] Removed localhost from internal domains. 

- src/Codeception/Lib/InnerBrowser.php
- tests/unit/Codeception/Module/TestsForWeb.php
seeOptionIsSelected sees first option as selected if none is selected #2733
> Fixed issue #2733

- src/Codeception/Module/Doctrine2.php
> Bug in seeInRepository when using @Embedded

- src/Codeception/Application.php
- tests/cli/GlobalCommandOptionCest.php
Hi,
in this PR is the --config option treated as cli standard.
by
Tobi
> console option are handled like cli standard

- composer.json
- composer.lock
- src/Codeception/Lib/Driver/Facebook.php
- src/Codeception/Module/Facebook.php
- tests/data/app/view/facebook.php
- tests/unit/Codeception/Module/FacebookTest.php
facebook module - add support for facebook/php-sdk-v4 version 5
> add support for facebook/php-sdk-v4 version 5

- docs/08-Customization.md
- src/Codeception/Application.php
- tests/data/register_command/examples/MyCustomCommand.php
- tests/data/register_command/examples/YourCustomCommand.php
- tests/data/register_command/standard/codeception.yml
- tests/data/register_command/standard/tests/_autoload.php
- tests/unit/Codeception/ApplicationTest.php
- tests/unit/Codeception/Command/MyCustomCommandTest.php
> Change the namespace for the example command.

- src/Codeception/Util/JsonArray.php
- tests/unit/Codeception/Module/RestTest.php
> Escaped XML text content with htmlspecialschars

- .travis.yml
- composer.json
Set upper boundaries for versions of all dependencies and PHP in composer.json
Added  build with lowest versions of all dependencies to travis.yml
> Updated dependencies of master branch

- src/Codeception/Lib/Connector/ZF2.php
> Pass POST parameters to ZF2

- src/Codeception/Actor.php
- src/Codeception/Lib/Console/Message.php
- src/Codeception/Step.php
- src/Codeception/Subscriber/Console.php
Fix encoding problems, #2831 redone for master branch
> Fix encoding problems in PHP prior to 5.6 related to #2831

- RoboFile.php
- composer.json
- src/Codeception/Lib/Interfaces/ActiveRecord.php
- src/Codeception/Lib/Interfaces/DataMapper.php
- src/Codeception/Lib/Interfaces/ORM.php
- src/Codeception/Module/DataFactory.php
- src/Codeception/Module/Doctrine2.php
Cleaner PR for DataFactory module
* Includes dependnecy on FactoryMuffin package
* Added Doctrine support
* Tests needed
> Datafactory module

- tests/unit/Codeception/Lib/ParserTest.php
Fixes #2859
Codeception 2.1 does not support PHPUnit 5
> Fixed broken test

- src/Codeception/Module/WebDriver.php
I guess we close https://github.com/Codeception/Codeception/issues/2511 afterwards.
> docs: Clarify slowness of fuzzy selectors when using Selenium with implicit wait

- CHANGELOG.md
- src/Codeception/Module/Laravel5.php
Laravel 5 module add `guard` parameter for `seeAuthentication` and `dontSeeAuthentication` methods. See #2876.
> Laravel 5 module add guard parameter for authentication methods

- src/Codeception/Module/WebDriver.php
Previous version was confusing to follow, made more readable with outer switch statement.
> Better layout of logic using switch

- src/Codeception/Module/WebDriver.php
- src/Codeception/PHPUnit/Constraint/Page.php
> Display correct path to output directory in the message

- docs/06-ReusingTestCode.md
Fixed readability within the StepObjects section.
> Grammar fix within StepObjects documentation

- src/Codeception/Util/JsonArray.php
- tests/unit/Codeception/Util/JsonArrayTest.php
Improves handling of issue #2899
> Throw UnexpectedValueException if JSON can't be converted to XML 

- src/Codeception/Util/JsonArray.php
- tests/unit/Codeception/Util/JsonArrayTest.php
> Replace JSON keys that can't be converted to XML tags with invalidTagX

- src/Codeception/Module/WebDriver.php
- tests/data/app/view/info.php
- tests/unit/Codeception/Module/TestsForWeb.php
> Ignore MalformedLocatorException because click can still match a text

- docs/reference/Commands.md
- src/Codeception/Command/Run.php
> Changed shortcut of --skip-group to -x 

- src/Codeception/Command/SelfUpdate.php
Fix for problem with proxy problem. Issue #2981
> Add self-update proxy support

- docs/modules/WebDriver.md
- src/Codeception/Module/WebDriver.php
- tests/data/app/view/form/select_selectors.php
- tests/web/WebDriverTest.php
PR for #3003
Included doc update and tests
> Add ability to define selector with selectOption

- .travis.yml
- CHANGELOG.md
- src/Codeception/Lib/Connector/ZF2.php
- src/Codeception/Module/ZF2.php
A significant modification of ZF2 module in order to fix #2964
New Application is created for each request, all services from previous request are reused except Request and Response.
I am not very happy with this solution but this is the best I can do.
> [ZF2] Create new Application for each request

- src/Codeception/Lib/Parser.php
- tests/data/php70Test
- tests/unit/Codeception/Lib/ParserTest.php
> Support anonymous classes in tests

- .travis.yml
- CHANGELOG.md
- src/Codeception/Lib/Connector/ZF2.php
- src/Codeception/Lib/Connector/ZF2/DoctrineServiceManager.php
> ZF2 Reuse only Doctrine services across different requests

- src/Codeception/Lib/Driver/Db.php
- src/Codeception/Module/Db.php
> Improved debug output of DB module

- .travis.yml
- src/Codeception/Module/REST.php
> REST: Merge query string and params in sendGET

- src/Codeception/Exception/Fail.php
- src/Codeception/Lib/Generator/GherkinSnippets.php
- src/Codeception/Test/Gherkin.php
- src/Codeception/Test/Loader/Gherkin.php
- tests/unit/Codeception/Test/GherkinTest.php
Should also fix https://github.com/Codeception/Codeception/issues/3037
> Gherkin improvements, added fail exception

- docs/071-BDD.md
changes `scenairo` to scenario
> Fix small typo

- docs/071-BDD.md
I'm not sure if it sounds better or not but I found the original text a bit hard to understand.
> Draft for new BDD paragraph

- src/Codeception/Lib/Connector/ZendExpressive.php
> Zend Expressive: support file upload

- docs/04-FunctionalTests.md
- docs/05-UnitTests.md
- docs/08-Customization.md
- docs/09-Data.md
- docs/10-WebServices.md
- docs/modules/DataFactory.md
- docs/modules/Doctrine2.md
- src/Codeception/Exception/ModuleConflictException.php
- src/Codeception/Module/DataFactory.php
- src/Codeception/Module/Doctrine2.php
Removed references to Dbh, Symfony2 and Laravel4 modules.
> Removed references to removed modules from docs

- .travis.yml
- appveyor.yml
- composer.json
- src/Codeception/Lib/Driver/MongoDb.php
- src/Codeception/Module/MongoDb.php
- tests/unit/Codeception/Module/MongoDbLegacyTest.php
- tests/unit/Codeception/Module/MongoDbTest.php
Updated MongoDb driver to check if using the legacy driver or not.
> Check installed mongo extension to use.

- RoboFile.php
- composer.json
`php robo.phar check:code-style`
`php robo.phar check:code-style -r diff`
> Add Robo command for checking code style

- CHANGELOG.md
- src/Codeception/Module/Dbh.php
> Fix Dbh module seeInDatabase or dontSeeInDatabase with empty criteria.

- src/Codeception/Lib/Driver/Db.php
Adding the ability to generate where clause with LIKE operator usage ['field LIKE' => '%value%']
> Support LIKE operator in Db Module

- src/Codeception/Lib/Generator/PageObject.php
- tests/unit/Codeception/Command/GeneratePageObjectTest.php
> Fixes page object generation with namespaces

- src/Codeception/Lib/Driver/Db.php
- tests/data/dumps/mysql.sql
- tests/unit/Codeception/Lib/Driver/MysqlTest.php
> Allow INT Parameter SQL Binding

- CHANGELOG.md
- src/Codeception/Lib/Interfaces/Db.php
- src/Codeception/Module/Db.php
Documented LIKE functionality
Removed repetitive examples
Added missing parameter types in docblocks
Formatting changes
> Updated documentation of Db module

- src/Codeception/Coverage/Subscriber/Printer.php
> --steps will not disable code coverage

- composer.json
> Allow symfony 3.1 components

- src/Codeception/Module/Lumen.php
the travis' test failure #3142 is enbugged by #3124. sorry 😢
> Fixes Lumen module does not work on PHAR version.

- CHANGELOG.md
- src/Codeception/Lib/InnerBrowser.php
- src/Codeception/Module/WebDriver.php
- tests/unit/Codeception/Module/TestsForWeb.php
* [WebDriver] fixed URL matching in WebDriver::seeLink
* [WebDriver][InnerBrowser] Improved error messages of seeLink and dontSeeLink
Fixes #3148
> Fixed URL matching in WebDriver::seeLink

- src/Codeception/Module/REST.php
> Added missing deleteHeader method to REST module

- src/Codeception/Lib/InnerBrowser.php
- tests/data/app/controllers.php
- tests/data/app/index.php
- tests/unit/Codeception/Module/PhpBrowserTest.php
> Location header only redirects when status code is 3xx

- src/Codeception/Module/Asserts.php
parent "Module" class already use this trait
> remove duplicated trait usage

- src/Codeception/Lib/InnerBrowser.php
- tests/data/app/view/info.php
- tests/unit/Codeception/Module/TestsForWeb.php
Searching checkboxes including label in InnerBrowser seeCheckboxIsChecked/dontSeeCheckboxIsChecked methods
> Searching checkboxes including label in InnerBrowser

- CHANGELOG.md
- src/Codeception/Lib/Connector/Yii1.php
Yii1 connector improved
* AR metadata cache is cleaned
* db connection closed
* `regenerateId` of CHttpSession disabled
> Improvements to Yii1

- src/Codeception/Module/DataFactory.php
https://github.com/Codeception/Codeception/issues/3208
> Fixing #3208

- src/Codeception/Test/Unit.php
- tests/data/claypit/tests/unit/DependsTest.php
> Restored passing return values in Unit tests as PHPUnit does in Uni

- docs/modules/Yii1.md
- src/Codeception/Module/Yii1.php
Now Yii1 module can be loaded partially without conflicting to WebDriver
documentation updated as well. Closes #3277
> `init` part added to Yii1 module

- src/Codeception/Event/FailEvent.php
- src/Codeception/PHPUnit/Listener.php
- src/Codeception/PHPUnit/ResultPrinter/UI.php
> Print execution time of non-successful tests

- docs/12-ParallelExecution.md
First  step to have to fix issue #3261 
And fix for robo-paracept is here https://github.com/Codeception/robo-paracept/pull/9
> Update install, split, run and merge

- .travis.yml
- CHANGELOG.md
- src/Codeception/Lib/Connector/ZendExpressive.php
- src/Codeception/Module/REST.php
Fixes #3298
Tested with Zend Expressive https://github.com/Naktibalda/codeception-zend-expressive-tests/commit/4cbeda777d2d9c57b7dd4e19148547fddcb751b5
> [REST] Allow objects in files array

- .travis.yml
- src/Codeception/Lib/Connector/ZF2.php
- src/Codeception/Lib/Connector/ZF2/PersistentServiceManager.php
- src/Codeception/Module/ZF2.php
Closes https://github.com/Codeception/Codeception/issues/3300
Test https://github.com/Naktibalda/codeception-zf2-tests/blob/2.2/tests/functional/AddServiceToContainerCept.php
> [ZF2] Added addServiceToContainer method

- docs/12-ParallelExecution.md
> Parallel Execution docs

- src/Codeception/Module/Lumen.php
> Update Lumen amLoggedAs to be compatible with 5.2

- ext/Recorder.php
* fixes #3356 - error saving files on Windows
* support for creating different records for tests with @example
> Recorder extension fix

- src/Codeception/Configuration.php
fixed merging module configs . Fixes #3292
> Fixed module configs

- src/Codeception/Lib/Connector/Yii2.php
> Mailer mock is now configured with options that make sense for it only

- CHANGELOG.md
- src/Codeception/Lib/Connector/Laravel5.php
> Laravel5 fix issue with uploaded files

- src/Codeception/Lib/Connector/Guzzle.php
- src/Codeception/Lib/Connector/Guzzle6.php
- src/Codeception/Module/REST.php
I cherry-picked commits from another pull request.
Replaces #3384
> [REST] fixed digest authentication

- src/Codeception/Lib/Connector/Yii2.php
> Fixes #3332: Fixed regression in Yii 2 connector not allowing to work with output of error pages in functional tests

- CHANGELOG.md
- src/Codeception/Lib/Connector/ZF2.php
- src/Codeception/Module/ZF2.php
Doctrine integration and services part is not compatible yet
> [ZF2] Support zend-mvc 3.0

- docs/03-AcceptanceTests.md
> added missing semicolon

- src/Codeception/Lib/InnerBrowser.php
- tests/unit/Codeception/Module/PhpBrowserRestTest.php
> [REST] requests are added to browser history

- CHANGELOG.md
- src/Codeception/Module/Memcache.php
* Updated `Memcache::seeInMemcached` to check if the key exists alone or with the desired value
* Added `Memcache::haveInMemcached`
* Fixed `Memcache::dontSeeInMemcached`
> Updated Memcache::seeInMemcached

- src/Codeception/Test/Cest.php
- src/Codeception/Test/Feature/CodeCoverage.php
- src/Codeception/Test/Interfaces/StrictCoverage.php
> Basic strict coverage support for Cest-format tests. Fixes #3409

- src/Codeception/Lib/InnerBrowser.php
- tests/unit/Codeception/Module/PhpBrowserRestTest.php
> [REST] application/json header check is case insensitive

- CHANGELOG.md
- src/Codeception/Lib/Connector/Lumen.php
- src/Codeception/Lib/Connector/Lumen/DummyKernel.php
- src/Codeception/Module/Lumen.php
Major refactoring of the Lumen module for the changes in Lumen 5.2 and 5.3.
I only tested this refactoring against the sample application, which is quite limited. I did not have the opportunity to test it with a real application. In case you do run into problems please open a new issue to report the problem.
> Refactor Lumen module

- tests/cli/RunCest.php
- tests/data/claypit/tests/unit/DataProvidersTest.php
> Test running test with data provider by group

- appveyor.yml
Appveyour should cache already installed libraries
> Cache appveyor installation

- src/Codeception/Module/Db.php
> [Db] Corrected description of cleanup parameter

- src/Codeception/Module/MongoDb.php
> [MongoDb] Updated documentation of grabFromCollection

- src/Codeception/PHPUnit/ResultPrinter/HTML.php
> Fixed wrong subSteps rendering in HTML ResultPrinter

- composer.json
- src/Codeception/Module/Facebook.php
> Replaced facebook/php-sdk with facebook/graph-sdk

- src/Codeception/Module/SOAP.php
> SOAP conflict with REST - come back

- src/Codeception/Module/Yii2.php
Fixes http://stackoverflow.com/questions/39810706/using-fixtures-in-functional-test-for-yii2-application
> [Yii2] Check if Yii::$app is set in _after before using it

- autoload.php
Issue: #3573 
_Note: Fixed bad (previously created from master) pull request #3574_
> Fixed redeclaring functions in autoload

- src/Codeception/PHPUnit/Constraint/Crawler.php
- src/Codeception/PHPUnit/Constraint/CrawlerNot.php
- src/Codeception/PHPUnit/Constraint/Page.php
- src/Codeception/PHPUnit/Constraint/WebDriver.php
- src/Codeception/PHPUnit/Constraint/WebDriverNot.php
- tests/unit/Codeception/Constraints/CrawlerConstraintTest.php
- tests/unit/Codeception/Constraints/CrawlerNotConstraintTest.php
- tests/unit/Codeception/Constraints/WebDriverConstraintTest.php
- tests/unit/Codeception/Constraints/WebDriverNotConstraintTest.php
> Removed all styling from see() error output to fix #3570

- src/Codeception/Lib/Friend.php
> Console Friend without style from 2.2.5 (regression)

- src/Codeception/Module/Yii1.php
> fix to return right value Yii1::getDomainRegex

- CHANGELOG.md
- src/Codeception/Lib/InnerBrowser.php
- tests/data/app/view/form/anchor.php
- tests/data/app/view/form/button_in_link.php
- tests/data/app/view/form/multiple_matches.php
- tests/unit/Codeception/Module/PhpBrowserTest.php
- tests/unit/Codeception/Module/TestsForWeb.php
- tests/web/WebDriverTest.php
Support clicking button in a link.
Click on the first clickable item when clickBySelector is used.
I expect WebDriver to fail some tests, but I can't run it locally now.
> [InnerBrowser] click improvements

- src/Codeception/Lib/Connector/Yii2/Logger.php
fix #3452 
Yii2 logging complex data (array) throws [PHPUnit_Framework_Exception]: Array to string conversion
> Array to string conversion #3452

- src/Codeception/Subscriber/GracefulTermination.php
> Disable graceful termination for PHP 7.0

- src/Codeception/Util/JsonType.php
> FIX #3671: removed duplicate if statement

- src/Codeception/Test/Loader.php
- tests/cli/RunCest.php
- tests/data/claypit/codeception.yml
- tests/data/claypit/tests/_data/groupFileTest1
> Fixed group files with exact test not working with @example on Windows

- docs/02-GettingStarted.md
- docs/03-AcceptanceTests.md
Improved grammar and greater consistency.
> Documentation Improvements - Chapter 02

- src/Codeception/Module/SOAP.php
> Force string for debugSection output

- docs/02-GettingStarted.md
- docs/03-AcceptanceTests.md
- docs/04-FunctionalTests.md
Improved grammar and greater consistency.
Some inaccuracies corrected.
> Documentation Improvements - Chapter 04

- src/Codeception/Util/Autoload.php
> Potential fix to autoloading issue

- CHANGELOG.md
- src/Codeception/Module/Lumen.php
> Fix issue with non-existing error class in Lumen module

- CHANGELOG.md
- src/Codeception/Lib/Connector/Laravel5.php
> Fix issue with service container bindings in Laravel 5 module

- docs/09-Data.md
> FIX: typo in data documentation

- src/Codeception/Module/WebDriver.php
ADDED notes to WebDriver->WaitForText() DocBlock about how the method operates.
> [WebDriver] Documented operation of waitForText method

- src/Codeception/Lib/Interfaces/Web.php
It works, just isn't documented.
> Add strict CSS locator example for see()

- src/Codeception/Lib/InnerBrowser.php
- tests/data/app/view/index.php
- tests/unit/Codeception/Module/TestsForWeb.php
Correct test for #3678 
and fix for InnerBrowser.
WebDriverTest will pass after #3678 is merged.
> Test click link by title

- src/Codeception/Coverage/Filter.php
> Coverage config exception when passing something other than array

- composer.json
- src/Codeception/Configuration.php
- src/Codeception/Lib/ParamsLoader.php
- tests/cli/ConfigParamsCest.php
- tests/data/params/codeception_dotenv2.yml
- tests/data/params/params.env.example
Using vlucas/phpdotenv for dot.env params loader.
Refactored params loader out of Configuration class.
Fxes #3716
> Refactored params loader. 

- composer.json
- src/Codeception/Lib/InnerBrowser.php
- tests/data/app/controllers.php
- tests/data/app/index.php
- tests/data/app/view/basehref.php
- tests/unit/Codeception/Module/TestsForWeb.php
> [PhpBrowser][Frameworks] Honour base tag

- codecept
- package/bin
- src/Codeception/Command/ConfigValidate.php
- src/Codeception/Command/Run.php
- src/Codeception/Command/Shared/Config.php
- src/Codeception/Configuration.php
- tests/cli/ConfigValidateCest.php
- tests/data/claypit/codeception_invalid.yml
- tests/support/CliHelper.php
This command prints array of currently loaded config and validates all config for suites.
Also can print per suite config.
Also better validation message for Configuration parsing added.
Closes #3766
> Added validate:config command

- src/Codeception/Lib/InnerBrowser.php
- tests/data/app/view/form/button-not-in-form.php
- tests/unit/Codeception/Module/PhpBrowserTest.php
> [InnerBrowser] Handle clicking on button outside a form correctly

- src/Codeception/Exception/ParseException.php
- src/Codeception/Test/Gherkin.php
- src/Codeception/Test/Loader/Gherkin.php
- tests/unit/Codeception/Test/GherkinTest.php
> gherkin: validating step regex before loading and using it

- src/Codeception/Test/Loader/Gherkin.php
- tests/cli/GherkinCest.php
- tests/cli/RunCest.php
- tests/data/claypit/tests/_support/ScenarioGuy.php
- tests/data/claypit/tests/scenario/File.feature
- tests/unit/Codeception/Test/GherkinTest.php
> Gherkin: Multiple definitions for steps supported.

- docs/modules/Asserts.md
- src/Codeception/Module/Asserts.php
- src/Codeception/Util/Shared/Asserts.php
- tests/unit/Codeception/Module/AssertsTest.php
Sometimes I need to use assertCount in my tests. Do you?)
> Added assertCount to Asserts module

- src/Codeception/Codecept.php
- src/Codeception/Configuration.php
- src/Codeception/Extension.php
- src/Codeception/Subscriber/ExtensionLoader.php
- tests/cli/ExtensionsCest.php
- tests/cli/GroupEventsCept.php
- tests/data/claypit/codeception.yml
- tests/data/claypit/tests/_support/ExtendedGuy.php
- tests/data/claypit/tests/_support/Group/CountEvents.php
- tests/data/claypit/tests/_support/Helper/Extended.php
- tests/data/claypit/tests/_support/SuiteExtension.php
- tests/data/claypit/tests/extended.suite.yml
- tests/data/claypit/tests/extended/HelloCept.php
- tests/data/claypit/tests/extended/_bootstrap.php
* loading **per suite** extensions
* configuring extensions inside enabled block
* merging global and suite extension configs
> Extensions Improvements

- src/Codeception/Command/GenerateSuite.php
- tests/support/Helper/Hobbit.php
- tests/unit/Codeception/Command/GenerateSuiteTest.php
Building actor class, printing additional details
> generate:suite made frendlier

- ext/Recorder.php
- src/Codeception/Subscriber/ExtensionLoader.php
> improved loading extensions per suite

- src/Codeception/Util/JsonArray.php
- tests/unit/Codeception/Module/RestTest.php
- tests/unit/Codeception/Util/JsonArrayTest.php
> [JsonArray] Convert array having single element to XML correctly

- src/Codeception/Util/ConsecutiveMap.php
- src/Codeception/Util/Stub.php
- src/Codeception/Util/StubMarshaler.php
I would like to see in the 21st century each class in a separate file and did not see any reason not to do it :)
> Moved ConsecutiveMap and StubMarshaler to the separated classes

- src/Codeception/Module/REST.php
- tests/unit/Codeception/Module/RestTest.php
> [REST] Implemented dontSeeResponseJsonMatchesXpath method

- src/Codeception/Module/WebDriver.php
- tests/unit/Codeception/Module/TestsForWeb.php
Add WebDriver::checkOption name attribute support.
> add checkbox name attrbitute support

- src/Codeception/SuiteManager.php
- tests/cli/RunCest.php
- tests/data/claypit/tests/scenario/DataProviderCest.php
- tests/data/claypit/tests/scenario/DependencyForCest.php
Fix for the issue "**@depends doesnt work with @dataprovider**" #3862
> Fix "@depends doesnt work with @dataprovider" #3862

- src/Codeception/Lib/InnerBrowser.php
- tests/data/app/view/form/bug3866.php
- tests/unit/Codeception/Module/TestsForWeb.php
> fix #3866 grabValueFrom doesn't work with fillField

- src/Codeception/Lib/Driver/Oci.php
(not sure how we missed this on #3881)
> remove bad line

- src/Codeception/Util/Locator.php
> [DOC] fix locator rendering

- src/Codeception/Module/Filesystem.php
- tests/cli/BootstrapCest.php
- tests/cli/RunCest.php
- tests/unit/Codeception/Module/FTPTest.php
- tests/unit/Codeception/Module/FilesystemTest.php
- tests/unit/Codeception/Module/SFTPTest.php
> [Filesystem] dontSeeFileFound searches in path

- src/Codeception/Subscriber/Console.php
`PHP Notice:  Undefined offset: 4`
> avoid Notice

- src/Codeception/Lib/Connector/Phalcon.php
Refs: http://phptest.club/t/codeception-not-clearing-http-x-requested-with/1352
Cc: @Naktibalda, @staveleyhead-garethmatthews
> Fixed handling $_SERVER with Phalcon Connector

- src/Codeception/Module/Db.php
- tests/unit/Codeception/Module/DbTest.php
> [Db] Disconnect after initializing when using reconnect, fixes #3903

- src/Codeception/Module/WebDriver.php
- tests/data/app/view/form/click.php
- tests/web/WebDriverTest.php
* add `clickWithLeftButton`
* make element optional for `clickWithLeftButton`, `clickWithRightButton` and `moveMouseOver`
* improve documentation
> improve mouse interaction

- docs/12-ContinuousIntegration.md
Gitlab CI configuration was "work in progress". This Pull Request gives a sample .gitlab-ci.yml file that will run codecept with the built-in php webserver.
> Adds gitlab CI configuration

- src/Codeception/Module/REST.php
Please use codeception/remote-debug package instead
Closes #3883
> [REST] Removed broken xdebug_remote functionality

- docs/07-AdvancedUsage.md
> Documentation Update: Using directories to define groups

- src/Codeception/Module/Yii2.php
> Fixes #3916: Don't try to start transaction when working with non-transactional DBs

- src/Codeception/Lib/Di.php
Closes #3869
Implementation suggested by @timtkachenko
> Fixed error description in DI

- src/Codeception/PHPUnit/ResultPrinter/HTML.php
> Fixed output path in HTML reporter

- src/Codeception/Module/WebDriver.php
Restart affects browser window, session is cleaned in any case
> [WebDriver] Minor config documentation improvement. 

- src/Codeception/Step.php
- tests/unit/Codeception/StepTest.php
> Fixed step output error, when max length is negative

- CHANGELOG.md
- docs/06-ModulesAndHelpers.md
- readme.md
- src/Codeception/Module/WebDriver.php
- tests/data/app/view/form/bug3865.php
- tests/web/WebDriverTest.php
> Webdriver test

- src/Codeception/Command/Run.php
* `use Symfony\Component\Yaml\Yaml;` not used
> cleanup use statements

- src/Codeception/Lib/Connector/Yii2.php
I think issue #3834 need reopen and will research
> Fixed #3961 (removed bad changes after #3834)

- docs/modules/Laravel5.md
- src/Codeception/Module/Laravel5.php
To be inline with Laravel
Addresses #3990
> Update Laravel5 database_migrations_path default

- src/Codeception/Step.php
> Fixed the issue that caused undefined index class #4038

- src/Codeception/Module/WebDriver.php
- tests/web/WebDriverTest.php
> [WebDriver] Dismiss popup if seeInPopup failed

- src/Codeception/Lib/Driver/Db.php
- src/Codeception/Lib/Driver/Oci.php
- src/Codeception/Lib/Driver/PostgreSql.php
- tests/unit/Codeception/Lib/Driver/PostgresTest.php
- tests/unit/Codeception/Lib/Driver/SqliteTest.php
Run the last statement in dump file even if it doesn't end with delimiter
Fixes #4059
> Fixed Issue/4059

- .gitignore
- src/Codeception/Module/WebDriver.php
- tests/web/WebDriverTest.php
> [WebDriver] Fixed compatibility with facebook/webdriver 1.4.0

- src/Codeception/Command/GenerateSuite.php
> Allow generate suites with uppercase names

- src/Codeception/Lib/Connector/Lumen.php
same change as #3124 for refactored Lumen module.
> changed timing of clearing facade cache

- docs/07-BDD.md
I'm a big fan of BDD and found it a shame that the opening paragraph to the BDD Codeception doc page had grammatical errors.
I find this easier to read as a native English speaker.
What do you think? Does it still convey what you were trying to get across?
> edits to first paragraph to make it easier to read & understand

- src/Codeception/Lib/Generator/GherkinSnippets.php
- src/Codeception/Test/Gherkin.php
- tests/cli/GherkinCest.php
- tests/data/claypit/tests/_support/ScenarioGuy.php
- tests/data/claypit/tests/scenario/InlineArgumentExample.feature
- tests/data/claypit/tests/scenario/PyStringArgumentExample.feature
> Steps with PyString and with inline string argument considered the same

- tests/unit/Codeception/Lib/Driver/MysqlTest.php
- wercker.yml
Removed mysql-server-5.5 package from Wercker build
> Possible fix to Wercker CI

- docs/03-AcceptanceTests.md
- src/Codeception/Module/WebDriver.php
* Added ChromeDriver mention to WebDriver docs
* Added Docker as possible setup
* Added link to WebDriver Local Testing from AcceptanceTesting guide
* Removed Data section (we have special guide for it) in Acceptance Testing
> Improved docs for acceptance testing.

- src/Codeception/Module/WebDriver.php
- tests/web/FriendsLeaveCept.php
Fixes #4098
Clearing base element on closing session.
Thanks @Naktibalda for reproducing the issue and creating a test. I copied it from your branch.
> Fixes #4098

- src/Codeception/Module/REST.php
This has been [noted in SO](http://stackoverflow.com/questions/28437633/send-file-to-restful-service-in-codeception) years ago, but there's still no docs on this, so...
> Adds doc about different manners to POST files

- src/Codeception/Lib/Connector/Yii2.php
Added the missing events according to
https://github.com/yiisoft/yii2/blob/c19b2f7dc8f487f0a867f2cacab68b8e86b7a8f9/framework/base/Application.php#L377
> add missing YII2 lifecycle events

- src/Codeception/Configuration.php
> added sort by test name on configuration load (#4180)

- docs/06-ModulesAndHelpers.md
- src/Codeception/Module/WebDriver.php
- tests/data/app/controllers.php
- tests/data/app/index.php
- tests/support/WebHelper.php
- tests/web/ReconfigureWebDriverCept.php
> Webdriver Reconfigure

- CHANGELOG-2.2.md
- composer.json
- src/Codeception/Configuration.php
- src/Codeception/Module/WebDriver.php
* updated changelog
* lowered PHPUnit support back to 5.x to avoid potential issues in patch release. Will be enabled back in 2.3.0
> Release 2.2.11

- src/Codeception/Test/Test.php
- tests/cli/SecondTestIsExecutedWhenTheFirstTestFailsCest.php
- tests/data/exception_in_before/tests/_support/_generated/.gitignore
- tests/data/first_test_fails/codeception.yml
- tests/data/first_test_fails/tests/_bootstrap.php
- tests/data/first_test_fails/tests/_output/.gitignore
- tests/data/first_test_fails/tests/_support/CustomReporter.php
- tests/data/first_test_fails/tests/_support/UnitTester.php
- tests/data/first_test_fails/tests/_support/_generated/.gitignore
- tests/data/first_test_fails/tests/unit.suite.yml
- tests/data/first_test_fails/tests/unit/_bootstrap.php
- tests/data/first_test_fails/tests/unit/twoTestsCest.php
Fixed condition which is checking if error happened in before
Closes #4223
> Don't skip other tests after failed test

- tests/README.md
Please help (I'm starting to work on https://github.com/Codeception/Codeception/issues/4231 ):  
I've cloned the project locally, how can I run the tests?
> Minor language improvements

- docs/03-AcceptanceTests.md
- docs/modules/WebDriver.md
- ext/README.md
- src/Codeception/Module/Db.php
- src/Codeception/Module/WebDriver.php
- tests/README.md
- tests/web.suite.yml
Taken from https://github.com/Codeception/Codeception/pull/4233
> Detailed installation instructions

- src/Codeception/Lib/DbPopulator.php
> Make dump optional in populator

- .travis.yml
It should fix a failing yii2 build
https://github.com/yiisoft/yii2-app-basic/commit/19b6143f051b404c8d73f4b1328d51064aa19e98
> Use newer version of fxp/composer-asset-plugin

- composer.json
- src/Codeception/Codecept.php
- src/Codeception/Command/Run.php
Changed handling optional values in console options
Fixes #4277
> Symfony 3.3.0 compatibility

- composer.json
Fixes https://github.com/yiisoft/yii2/issues/14226
Reverts https://github.com/Codeception/Codeception/pull/4262
> Removed "shim" from "files" in "composer.json"

- docs/modules/AMQP.md
- src/Codeception/Module/AMQP.php
This PR add new option which fix this issue: 
#4280
> Added AMQP Module option to use only one channel

- docs/07-AdvancedUsage.md
changed `loginCheck` to `tryToCheck` to ensure consistency between the text and the code part
> Updated 07-AdvancedUsage.md

- docs/01-Introduction.md
- docs/03-AcceptanceTests.md
This is meant to replace the current "Pros" and "Cons" sections, for better overview.
Points which I left out:
* "can be shown to your clients and managers": Doesn't make sense to me, since you can anything to anyobdy - as long as they are willing to take a look ;-)
* "most stable in support: less affected by changes in source code or technologies": Not true for me, since acceptance test is most affected by changes in *browser* source code or *JavaScript* technologies
* "fewer checks can lead to false-positive results": Don't understand
* "not stable in execution: rendering and JavaScript issues can lead to unpredictable results": You mean that Selenium is sometimes running unstable? I wouldn't mention that here.
* "can provide more detailed reports": Don't understand. Which reports?
* …
> Overview table for test suites

- src/Codeception/Lib/InnerBrowser.php
> [InnerBrowser] seeLink assertion counter

- src/Codeception/Lib/InnerBrowser.php
`setHeader` is an old api it looks like
> [DOC] Clean up doc example for haveHttpHeader

- docs/03-AcceptanceTests.md
- src/Codeception/Module/WebDriver.php
* Cleanup for Selenium/WebDriver/Phantom sections
* Added ChromeDriver (this was the initial motivation for the change)
* Manual controlling of browser sessions (can be cool for advanced usage on cloud systems)
* Recommended RunProcess extension (in #4338)
@ThomasLandauer please review )
> Updated Acceptance Testing documentation:

- .travis.yml
Based on ZF2 test suite and Symfony standard edition skeleton.
Covered:
- various HTTP features with REST module
- amOnRoute
- hostname based routes
- redirects
- Doctrine module integration
> Test suite for Symfony 3

- src/Codeception/Lib/ModuleContainer.php
> Check $module::$excludeActions property for existence before accessing

- docs/08-Customization.md
> Replaced link for Custom command example

- src/Codeception/Module/Db.php
- tests/unit/Codeception/Module/Db/MySqlDbTest.php
- tests/unit/Codeception/Module/Db/TestsForDb.php
> Grab multiple rows from a database

- docs/modules/Asserts.md
- src/Codeception/Module/Asserts.php
- src/Codeception/Util/Shared/Asserts.php
- tests/unit/Codeception/Module/AssertsTest.php
This adds assertStringStartsWith and assertStringStartsNotWith to the available asserts.
> Add assertStringStartsWith

- appveyor.yml
- src/Codeception/Command/Run.php
- tests/cli/IncludedCest.php
> Fixed appveyor

- docs/modules/Asserts.md
- src/Codeception/Module/Asserts.php
- src/Codeception/Util/Shared/Asserts.php
- tests/unit/Codeception/Module/AssertsTest.php
Adds assertArraySubset to the asserts.
> Add assertArraySubset

- src/Codeception/Util/Shared/Asserts.php
> Make assertArraySubset protected

- src/Codeception/Lib/InnerBrowser.php
- tests/data/app/view/form/complex.php
- tests/unit/Codeception/Module/TestsForWeb.php
> Prevents SubmitForm Submitting Inputs In Disabled Fieldsets

- src/Codeception/Lib/Driver/PostgreSql.php
This is a better way to do the cleanup for pgsql.
> fix/postgres_cleanup alter postgres cleanup (recreate schema)

- src/Codeception/Module/Yii2.php
> Set transaction also in backupConfig when initializing yii2 module

- src/Codeception/Module/Db.php
- tests/unit/Codeception/Module/Db/TestsForDb.php
Goals:
- Add doc for updateInDatabase()
- Add insertInDatabase() that insert a new record without deleted at the end of the test like haveInDatabase()
> [Db] Update and Insert in database

- src/Codeception/Util/Fixtures.php
The goal of this PR is to add an exists method to Fixtures.
```php
if (Fixtures::exists('user1'))
{
return Fixtures::get('user1');
}
Fixtures::add('user1', 'new user');
```
> [Fixtures] Add exists method

- composer.json
> Allow sebastian/diff 2.* in composer.json

- src/Codeception/Util/Locator.php
Fix render documentation, some  methods
- isXPath()
- isID()
- isClass()
From http://codeception.com/docs/reference/Locator
> Fix documentation rendering

- .travis.yml
- src/Codeception/Lib/InnerBrowser.php
Yii2 tests are disabled until a compatible version of Yii2 is released.
> [Travis] run tests on PHP 7.2

- src/Codeception/Lib/Interfaces/Web.php
> Improved description of grabFromCurrentURL

- docs/03-AcceptanceTests.md
Really minor one - just fixing this link on the Acceptance Testing doc page.
> Fixing link on Acceptance Testing doc

- tests/unit/Codeception/Lib/Driver/DbTest.php
- tests/unit/Codeception/Lib/Driver/MysqlTest.php
- tests/unit/Codeception/Module/Db/TestsForDb.php
I merged pull request with failing tests #4468
Here are better tests.
> Db generate where clause tests

- src/Codeception/Module/Silex.php
> `app` property exposed as public in Silex module (#4531)

- src/Codeception/Subscriber/ErrorHandler.php
Hello,
Please see: https://github.com/symfony/symfony/issues/24459#issuecomment-334724907 
and https://github.com/symfony/symfony/pull/24192/files
Thank you !
> $context in ErrorHandler.php

- src/Codeception/Command/GenerateStepObject.php
Replaces  #4480
which edited wrong file.
> Updated docblock of generate::stepobject command

- src/Codeception/Module/Symfony.php
Introduce support of Symfony Flex - Symfony 3.3+ recommended way for Symfony app.
Demo app can be found at https://github.com/VolCh/symfony-flex-demo
> [Symfony] Minimal support for Symfony Flex directory and namespace str.

- src/Codeception/Module/WebDriver.php
- tests/web/WebDriverTest.php
this is in reference to issue https://github.com/Codeception/Codeception/issues/4588
> added dontSeeInPopUp function

- src/Codeception/Lib/Connector/Yii2.php
This commit fixes issue reported in Yii2 repo yiisoft/yii2-app-advanced#221
> Pass DB to Yii application as early as possible

- package/bin
> Added init command to phar file

- composer.json
- docs/modules/REST.md
- src/Codeception/Lib/Connector/Guzzle.php
- src/Codeception/Lib/Connector/Guzzle6.php
- src/Codeception/Module/REST.php
Testing API using REST module in AWS Cloud required AWS authorization. 
Creating a AWS authorization wrapper in dorequest method for guzzle.
> AWS Authorization for REST requests

- composer.json
- docs/modules/Queue.md
- src/Codeception/Lib/Driver/AmazonSQS.php
- src/Codeception/Module/Queue.php
https://github.com/Codeception/Codeception/issues/4636
> Fixed AmazonSQS client init configuration. Added version. #4636

- src/Codeception/Lib/Driver/Db.php
- src/Codeception/Lib/Driver/Sqlite.php
- src/Codeception/Lib/Generator/Actions.php
- src/Codeception/Module/Db.php
Issue: Db-Module: MySQL SSL connection #4602
> Dbdriver ssloptions

- src/Codeception/Lib/Driver/AmazonSQS.php
- src/Codeception/Module/Queue.php
> [Queue] Configuration parameter endpoint is missing in AmazonSQS

- src/Codeception/Application.php
- src/Codeception/Command/SelfUpdate.php
> Fixed undefined argv warnings, added check for register_argc_argv

- src/Codeception/Module/REST.php
- tests/unit/Codeception/Module/RestTest.php
> REST::amDigestAuthenticated throws exception if used with functional

- src/Codeception/Util/Stub.php
> Code snippet fixes

- composer.json
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-9841
> Restrict phpunit to non-vulnerable versions

- src/Codeception/Lib/Connector/Yii2.php
- src/Codeception/Module/Yii2.php
Sign cookies when the Yii2 application has cookie signing enabled
> Sign cookies #4656

- src/Codeception/Command/SelfUpdate.php
- src/Codeception/Configuration.php
`isset` allow us to pass multiple values to check.
[PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) helped me on that.
> Combine consecutive issets

- src/Codeception/Lib/Connector/Guzzle.php
- src/Codeception/Lib/Connector/Phalcon.php
- src/Codeception/Lib/Di.php
- src/Codeception/Module/Laravel5.php
- src/Codeception/Module/MongoDb.php
- src/Codeception/Module/WebDriver.php
- src/Codeception/Step.php
- src/Codeception/Util/Maybe.php
- src/Codeception/Util/Stub.php
- src/Codeception/Util/Uri.php
- tests/unit/Codeception/Module/PhpBrowserTest.php
I've cleaned the `else`s when we have already returned something :put_litter_in_its_place:
> Clean elses

- docs/reference/Configuration.md
- src/Codeception/Command/Bootstrap.php
- src/Codeception/Configuration.php
- src/Codeception/Template/Bootstrap.php
Renamed logs directory to output because it was renamed in 2.3.0
> Updated paths section in Configuration docs

- src/Codeception/Module/DataFactory.php
This is a clean pull request.
It replaces #4647
and fixes #4646
> [DataFactory] Removed redundant dependency

- src/Codeception/Module/Yii2.php
Fix interface name in grabSendEmail method comment
> Update Yii2.php (fix comment)

- src/Codeception/Coverage/Subscriber/LocalServer.php
- tests/support/CoverGuy.php
Replaces #4577 (I fixed broken tests)
Fixes #4441 
Fixes #2923
> [CodeCoverage] Removed request to main page

- .travis.yml
- composer.json
Because DataFactory module has no tests
> Removed factory-muffin from composer.json

- Dockerfile
fixes #4742 - but xdebug is only available as a beta version for now(!)
> added PHP 7.2 support, xdebug added as 2.6.0beta1

- src/Codeception/Lib/InnerBrowser.php
Because I have in some of my Helper the same code as in this method witch I can't call as it is protected
> Please set getResponseStatusCode as public

- src/Codeception/Module/Yii2.php
> Use Yii DI for resolve any upgrade on record class

- docs/11-Codecoverage.md
- src/Codeception/Coverage/Subscriber/LocalServer.php
> Remove :port for cookie domain; $this->module->amOnPage('/'); 

- src/Codeception/Command/Run.php
- tests/cli/RunSingleTestWithIncludeCest.php
- tests/data/single_test_with_include/_bootstrap.php
- tests/data/single_test_with_include/_output/.gitignore
- tests/data/single_test_with_include/_support/UnitTester.php
- tests/data/single_test_with_include/_support/_generated/.gitignore
- tests/data/single_test_with_include/codeception.yml
- tests/data/single_test_with_include/unit.suite.yml
- tests/data/single_test_with_include/unit/ExampleCest.php
- tests/data/single_test_with_include/unit/_bootstrap.php
> Fix: fail to run single test with include

- CHANGELOG-2.3.md
- src/Codeception/Codecept.php
- src/Codeception/Command/Run.php
- src/Codeception/Lib/Generator/Test.php
- src/Codeception/Module/WebDriver.php
- tests/cli/ConfigBundledSuitesCest.php
- tests/cli/ConfigNoActorCest.php
* Changelog updated
* WebDriver minor improvements
* Single suite setup improvements
> Pre 2.3.8 release

- src/Codeception/PHPUnit/ResultPrinter/HTML.php
> Fixed #4675 - HTML Report marks tests as succeeded

- docs/05-UnitTests.md
It seems to be about assertions, which are countable.
> Changing "much" to "many" in 05-UnitTests.md doc

- src/Codeception/Module/REST.php
> Add missing / to relative url from config

- .gitignore
- .travis.yml
- RoboFile.php
- appveyor.yml
- composer.json
- tests/unit/Codeception/Module/PhpBrowserTest.php
* PHPUnit 7 
* Phar build improvements
> PHPUnit 7 support

- src/Codeception/Lib/Generator/GherkinSnippets.php
Fixes silly indentation issue :)
> Fixes #4818

- src/Codeception/Module/DataFactory.php
- Add a space after start of a comment line
- remove characters before start of a comment
> Fix comments in DataFactory.php

- src/Codeception/Test/Cest.php
https://github.com/Codeception/Codeception/issues/4812
> call after hook for Cest after every test (PASSED or FAILED)

- src/Codeception/Lib/InnerBrowser.php
- tests/unit/Codeception/Module/TestsForWeb.php
Reverts Codeception/Codeception#4075
> Revert "Added new method seeOptionValueIsSelected"

- docs/12-ParallelExecution.md
use "codecept" above
again...
#3745 #3746
> typo in service name

- src/Codeception/Command/Clean.php
I have made clean recursive. Requested in #4685
> Make clean resursive

- src/Codeception/Test/Descriptor.php
- src/Codeception/Test/Loader/Cest.php
- src/Codeception/Test/Metadata.php
https://github.com/Codeception/Codeception/issues/4819
> Running tests with particular data set index

- .travis.yml
- appveyor.yml
> Fixing windows builds

- docs/modules/Yii2.md
Fix typo at line 104, missing close square bracket
> Fix typo at docs/modules/Yii2.md

- src/Codeception/Module/WebDriver.php
- tests/web/WebDriverTest.php
Simple session snapshot deletion. 
Helps you to delete session snapshot if you need to logout.
Fixes issue #4869
> Add session snapshot deletion

- src/Codeception/Module/ZendExpressive.php
sometimes the hardcoded name is not what you want :) also this will allow using different EntityManager's not just default one when needed
> Allow to specify EntityManager container key

- .travis.yml
This PR reorganizes the Travis CI tests into (lots of) jobs.
Each framework is tested separately which each supported PHP version.
Yii2 tests disabled until the Yii2 PR gets merged.
> Reorganized travis jobs

- composer.json
> Bump PHP min version to 5.6

- src/Codeception/Lib/Connector/Yii2.php
- src/Codeception/Module/Yii2.php
This should fix #4910 and add some more flexibility as well.
> Implemented alternate strategies for clearing response / request objects

- src/Codeception/Lib/Connector/Yii2.php
- src/Codeception/Module/Yii2.php
This PR adds support for reconfiguring the Yii2 module inside a test case.
It is used by the test repository (amongst others) to test event handlers.
> Support reconfiguration

- src/Codeception/Util/JsonArray.php
- tests/unit/Codeception/Util/JsonArrayTest.php
Also adds a unit test covering this case.
Fixes #4944
> Makes JsonArray convert all decoded non-arrays to array

- src/Codeception/Module/Memcache.php
- src/Codeception/Module/REST.php
- tests/unit/Codeception/Module/TestsForWeb.php
- tests/unit/Codeception/Util/JsonArrayTest.php
> Use dedicated PHPUnit assertions

- src/Codeception/Module/Db.php
Example for grabFromDatabase was incomplete.
> Documentation, grabFromDatabase, example error

- src/Codeception/Command/Run.php
Notice: Undefined index: tests in Codeception\Command\Run.php on line 389
> Fix error on single file test: headers already sent

- tests/cli.suite.yml
- tests/cli/RunCest.php
Created failing test RunCest::runJsonReport
Assert that json_decode does not return null from report.json
> Issue #5023

- docs/03-AcceptanceTests.md
- docs/06-ModulesAndHelpers.md
- docs/06-ReusingTestCode.md
- docs/07-AdvancedUsage.md
- docs/12-ParallelExecution.md
- docs/modules/AMQP.md
- docs/modules/AngularJS.md
- docs/modules/REST.md
- docs/modules/WebDriver.md
- docs/reference/Locator.md
- docs/reference/Mock.md
- docs/reference/XmlBuilder.md
> minor doc updates

- CHANGELOG-2.4.md
> bump changelog

- docs/02-GettingStarted.md
> Typo fix in docs

- ext/Recorder.php
Implementation for proposed feature described in #5014
> Added new option to Recorder extension to disable recording of specified steps

- CHANGELOG-2.4.md
- src/Codeception/Codecept.php
> Prepare 2.4.4 release

- docs/08-Customization.md
- docs/modules/Db.md
> update stale github/tree URLs in docs

- src/Codeception/Module/Db.php
Added two options:  "ssl_cipher" (list of one or more permissible ciphers to use for SSL encryption) and "ssl_verify_server_cert" (disables certificate CN verification)
> Two new options: "ssl_cipher" and "ssl_verify_server_cert"

- ext/Recorder.php
> Fixing edge-case issues with the recording extension

- ext/RunBefore.php
For [https://github.com/Codeception/Codeception/issues/5049](https://github.com/Codeception/Codeception/issues/5049)
> Adding an extension to run processes before tests

- src/Codeception/Lib/Connector/Lumen.php
for #5081
(there's no Lumen tests)
> fix Lumen file upload via REST module

- src/Codeception/Lib/Driver/Db.php
- src/Codeception/Module/Db.php
For more graceful DB closing upon exceptions.
> More explicit PDO closing upon destruction

- src/Codeception/Module/Db.php
(edit: removed the 'is already connected' check behavior)
> always disconnect before connect when reconnect is set

- ext/Recorder.php
> Fixing recorder extension issues caused by phpunit 7.2.7 update

- src/Codeception/Module/WebDriver.php
- tests/web/WebDriverTest.php
Fix  **WebDriver** module issue when `see()` and `dontSee() ` are used with array selector.
Fixes #4846
> [WebDriver] Fix #4846

- src/Codeception/Command/DryRun.php
> Added memory_limit to dryrun command

- src/Codeception/Actor.php
> Test names should be equal.

- src/Codeception/Command/Run.php
> Ensure php extension mbstring is available.

- autoload.php
- ext/Logger.php
> Added getLogger

- src/Codeception/Module/Yii2.php
> Yii2: Fix `Too many connections` issue

- src/Codeception/Lib/Connector/Yii2.php
- src/Codeception/Lib/Connector/Yii2/TestMailer.php
Have tested the fix against the test provided here: https://github.com/Codeception/yii2-tests/pull/3
> TestMailer now stores messages in the connector.

- src/Codeception/Module/REST.php
> [REST] Add response code assertions to json and xml parts

- src/Codeception/Step.php
> Removes debug

- src/Codeception/Lib/Connector/Yii2.php
Reference: https://github.com/Codeception/Codeception/pull/5173#pullrequestreview-158896553
> [Yii2] Restore getApplication() API

- src/Codeception/Module/Db.php
Fixes #5195 
I made _loadDump unconditional like it was in 2.4.
Then I fixed and improved a few other issues.
> Unconditional _loadDump in 2.5

- composer.json
Added `monolog/monolog` and `symfony/process` to the composer suggest section.
> Added additional suggestions.

- src/Codeception/Configuration.php
That fix adds explanation which directory isn't writable.
> Fix output dir exception message

- PruneTest.php
Same as #5300 , but runs push build too and that's the build Sam is trying to fix.
> Sam mousa fix test prune

- src/Codeception/Command/ConfigValidate.php
forget in PR https://github.com/Codeception/Codeception/pull/4065
> fix method call

- src/Codeception/Lib/Interfaces/Web.php
Fixes docblocks for `see()`/`dontSee()`
> Fixes docblock

- src/Codeception/Lib/Connector/ZendExpressive.php
- src/Codeception/Module/ZendExpressive.php
And try not to break Zend Expressive v2 tests
Closes #4877
> Support Zend Expressive v3

- src/Codeception/Util/JsonType.php
- tests/unit/Codeception/Util/JsonTypeTest.php
Fixes #2501 
Fixes regex filter handling in Util\JsonType
> JsonType: Allow to use : in regex filter

- .travis.yml
To fix build failures caused by building cphalcon master branch.
Thanks to @sergeyklay
> [Travis] build specific version of cphalcon

- src/Codeception/Codecept.php
- src/Codeception/Command/Run.php
- src/Codeception/Configuration.php
- src/Codeception/Subscriber/Console.php
- tests/cli/RunCest.php
Fixes #5004 
Implemented new option `--phpunit-xml` which generated XML report having the same structure as XML report generated by PhpUnit.
> PhpUnit XML report

- ext/Recorder.php
> [Docs] Fix typo in Recorder extension docs

- tests/cli/RunCest.php
These tests test code which is in phpunit-wrapper, which is a bit annoying because I have to coordinate updates of both repos.
> Updated phpunit xml report tests to verify name of per-file test suite

- src/Codeception/Module/Db.php
> issue-5367 grabFromDatabase() returns string

- composer.json
- src/Codeception/Lib/ParamsLoader.php
> Update vlucas/phpdotenv package to ^3.0 version

- docs/modules/FTP.md
- src/Codeception/Module/FTP.php
> Update Ftp module to be compatible with phpseclib v2 (Issue #5363)

- src/Codeception/Module/FTP.php
- src/Codeception/Module/Queue.php
I haven't used codeception in a while so I am no longer the best person to maintain these modules or answer questions. So I am removing the maintainer details from the docs, I haven't changed the stability values.
https://github.com/Codeception/codeception.github.com/pull/159
> Removing myself as a maintainer of these modules

- tests/cli/RunCest.php
> Fixed broken runDependentTest

- src/Codeception/Module/Doctrine2.php
See https://github.com/Codeception/Codeception/issues/5347
> Documenting `IS NULL`

- src/Codeception/Lib/InnerBrowser.php
Using button formaction attr in proceedSubmitForm method (AcceptanceTesterActions::submitForm)
> Using button formaction attr in proceedSubmitForm method

- ext/Recorder.php
Added configurable timestamp reporting for each recorded step in Recorder extension.
Closes #5239
FYI: @DavertMik 
Just as a reminder it seems that the Recorder gif had not been updated in the website to the provided GIF.
(As mentioned in https://github.com/Codeception/Codeception/pull/5221)
Would you like me to generate a new one?
> Adding timestamp information in recordings

- src/Codeception/Module.php
> Fixing Module.php constuctor and getConfig phpdoc parameter definitions

- src/Codeception/Module/Laravel5.php
Fix issues with ORM :
- #5391 (complex attributes)
- #4897 (null attributes)
> [Laravel5] Fix ORM issues

- docs/modules/Phalcon.md
- src/Codeception/Module/Phalcon.php
I have added new method seeNumberOfRecords in Phalcon module, to check number of records in the table.
> Phalcon module see number of records

- src/Codeception/Codecept.php
`2.6.0` is not a released version.
Fixes #5505
> Set the VERSION constant to 3.0.0

- src/Codeception/Module/Symfony.php
Please fix the link markup - I'm not sure whether it should be Markdown or HTML...
> Added info to seeEmailIsSent about stopFollowingRedirects

- Dockerfile
Fixing autoloader generation for 3.0 images and updating xdebug to stable version
> Fixing autoloader generation for 3.0 docker images

- src/Codeception/Configuration.php
- src/Codeception/Lib/Generator/Actions.php
> Fix double methods

- src/Codeception/Module/Cli.php
Old assertion throws deprecation warning
> Update assertion method in seeInShellOutput

- src/Codeception/Test/Loader/Unit.php
> Compatibility with PHPUnit 8.2

- src/Codeception/Module/Doctrine2.php
- src/Codeception/Test/Loader/Unit.php
Complete description of this pull request can be found in #5542.
> [Doctrine2] Fix recursive building of association queries

- docs/11-Codecoverage.md
List all currently supported drivers for collecting code coverage, for #5531.
> Mention phpdbg and pcov for code coverage in docs

- src/Codeception/Lib/InnerBrowser.php
> InnerBrowser: call deprecated getStatus method last

- src/Codeception/Lib/Connector/Guzzle.php
Fixes #5548
I haven't tested this change, it is based on this documentation: http://docs.guzzlephp.org/en/stable/request-options.html#multipart
and this code: https://github.com/guzzle/psr7/blob/1.5.2/src/MultipartStream.php#L132
> [PhpBrowser] Pass file type option to Guzzle if specified

- CHANGELOG-3.0.md
And a few very minor formatting and pretty printing issues
> Fix Link to "A/B Testing" for "silent actions"

- src/Codeception/Lib/Connector/Yii2.php
https://www.php.net/manual/en/function.preg-quote.php#refsect1-function.preg-quote-changelog
> Fixed issue on PHP7.3 because `preg_quote` now also quotes `#`.

- composer.json
- src/Codeception/Module/Doctrine2.php
- src/Codeception/Util/ReflectionPropertyAccessor.php
- tests/data/doctrine2_entities/JoinedEntity.php
- tests/data/doctrine2_entities/JoinedEntityBase.php
- tests/data/doctrine2_entities/PlainEntity.php
- tests/unit/Codeception/Module/Doctrine2Test.php
This PR fixes problem with fields of inherited entities, as described in #5569.
Fixes #5569
> [Doctrine2] Fix handling of inherited entities

- src/Codeception/Module/Doctrine2.php
- src/Codeception/Util/ReflectionPropertyAccessor.php
- tests/data/doctrine2_entities/EntityWithEmbeddable.php
- tests/data/doctrine2_entities/SampleEmbeddable.php
- tests/unit/Codeception/Module/Doctrine2Test.php
> [Doctrine2] fix handling of embeddables

- src/Codeception/Module/Doctrine2.php
- tests/data/doctrine2_entities/QuirkyFieldName/Association.php
- tests/data/doctrine2_entities/QuirkyFieldName/AssociationHost.php
- tests/data/doctrine2_entities/QuirkyFieldName/Embeddable.php
- tests/data/doctrine2_entities/QuirkyFieldName/EmbeddableHost.php
- tests/unit/Codeception/Module/Doctrine2Test.php
> Doctrine2 parameter name clash fix

- CHANGELOG-3.0.md
- docs/modules/Laravel5.md
- docs/modules/Lumen.md
- src/Codeception/Module/Laravel5.php
- src/Codeception/Module/Lumen.php
Add `make` and `makeMultiple` commands to [Laravel5] and [Lumen] modules. 
They will act like factory()->make()
> Add make commands to Laravel5 and Lumen modules

- src/Codeception/Subscriber/ErrorHandler.php
- tests/cli/ErrorHandlerCest.php
- tests/data/first_test_exits/codeception.yml
- tests/data/first_test_exits/tests/_bootstrap.php
- tests/data/first_test_exits/tests/_output/.gitignore
- tests/data/first_test_exits/tests/_support/UnitTester.php
- tests/data/first_test_exits/tests/_support/_generated/.gitignore
- tests/data/first_test_exits/tests/unit.suite.yml
- tests/data/first_test_exits/tests/unit/ExitCest.php
- tests/data/first_test_exits/tests/unit/_bootstrap.php
Closes #5595
Add test for #4604 /cc @Fenikkusu
> ErrorHandler: add test for early exits

- src/Codeception/Module/Doctrine2.php
> fix meaningless doc comment for Doctrine2::onReconfigure

- src/Codeception/Module/Doctrine2.php
- tests/data/doctrine2_entities/PlainEntity.php
- tests/unit/Codeception/Module/Doctrine2Test.php
Closes #5616, closes #5347, closes #4274, resolves #1019.
> [Doctrine2] add support for Expression and Criteria objects in queries

- composer.json
- src/Codeception/Module/Doctrine2.php
- tests/data/doctrine2_entities/PlainEntity.php
- tests/data/doctrine2_fixtures/TestFixture1.php
- tests/data/doctrine2_fixtures/TestFixture2.php
- tests/unit/Codeception/Module/Doctrine2Test.php
> [Doctrine2] add fixtures support

- src/Codeception/Module/Doctrine2.php
- tests/unit/Codeception/Module/Doctrine2Test.php
> [Doctrine2] merge functionality of persistEntity into haveInRepository

- src/Codeception/Module/Doctrine2.php
- src/Codeception/Util/ReflectionPropertyAccessor.php
- tests/data/doctrine2_entities/CompositePrimaryKeyEntity.php
- tests/data/doctrine2_entities/NonTypicalPrimaryKeyEntity.php
- tests/unit/Codeception/Module/Doctrine2Test.php
> [Doctrine2] properly handle non-typical primary keys in haveInRepository

- src/Codeception/Module/Doctrine2.php
- tests/data/doctrine2_entities/PlainEntity.php
- tests/unit/Codeception/Module/Doctrine2Test.php
> [Doctrine2] expose clear() and refresh()

- src/Codeception/Module/Doctrine2.php
- tests/data/doctrine2_entities/MultilevelRelations/A.php
- tests/data/doctrine2_entities/MultilevelRelations/B.php
- tests/data/doctrine2_entities/MultilevelRelations/C.php
- tests/unit/Codeception/Module/Doctrine2Test.php
> [Doctrine2] implement recursive entity creation

- docs/modules/Yii2.md
- src/Codeception/Module/Yii2.php
Issue #5631:
* Adds some missing articles (a / the) to improve readability
* Adds `amOnPage()` stub method to document URL in array format
> Issue #5631 improve yii2 module docs

- src/Codeception/Module/Doctrine2.php
- src/Codeception/Util/ReflectionPropertyAccessor.php
- tests/data/doctrine2_entities/EntityWithConstructorParameters.php
- tests/unit/Codeception/Module/Doctrine2Test.php
Closes https://github.com/Codeception/Codeception/issues/5632 (please also note the comments there).
> [Doctrine2] Make haveInRepository support constructor parameters

- src/Codeception/Step.php
- src/Codeception/Step/Retry.php
- src/Codeception/Step/TryTo.php
> Do not fail steps for retry and tryTo step decorators

- tests/web.suite.yml
- tests/web/WebDriverTest.php
I updated Chrome+Firefox in SemaphoreCI. 
Let's run our tests on the latest Selenium
> added firefox environment

- src/Codeception/Module/WebDriver.php
Changed the error text in `waitForJS`
Closes #4658
> change text for #4658

- src/Codeception/Module/Symfony.php
> [bugfix] add use for run console command

- composer.json
- src/Codeception/Module/Doctrine2.php
- tests/data/doctrine2_entities/EntityWithUuid.php
- tests/unit/Codeception/Module/Doctrine2Test.php
May be one part of the solution for #5691.
> [Doctrine2] support non-entity doctrine @id on the haveInRepository debug message.

- src/Codeception/Test/Descriptor.php
- tests/cli/RunCest.php
- tests/data/claypit/tests/_support/Page/DemoPageObject.php
- tests/data/claypit/tests/html_report.suite.yml
- tests/data/claypit/tests/html_report/CodeceptionIssue4413Cest.php
- tests/data/claypit/tests/html_report/_bootstrap.php
Because phpunit-wrapper runs tests from 3.0.
Tests #4413
> Merge #4413 tests to 3.0 branch

- src/Codeception/Test/Descriptor.php
- tests/cli/RunCest.php
- tests/data/claypit/tests/_support/Page/DemoPageObject.php
- tests/data/claypit/tests/html_report.suite.yml
- tests/data/claypit/tests/html_report/CodeceptionIssue4413Cest.php
Replaces #5690
I merged these changes to 3.0 branch already, because it is used to test phpunit-wrapper.
Also I released phpunit-wrapper 8.0.5 with fixes.
I will release new versions of 7.1, 6.5 and 6.0 branches later.
> Test for phpunit-wrapper fix (#4413)

- composer.json
- src/Codeception/Lib/ParamsLoader.php
Support `vlucas/phpdotenv` `v4` along with the other versions and symfony dotenv.
> Support phpdotenv v4

- composer.json
I added them to `require` by accident.
> Moved dev dependencies to require-dev

- ext/RunBefore.php
- ext/RunProcess.php
Also removes deprecation message when used with Symfony 4.2-4.4.
Fixes #5784
> RunProcess and RunBefore extensions compatible with Symfony 5

- src/Codeception/Util/Fixtures.php
New PR with updated code due to #5124 (comment)
> Cleanup fixture by name

- src/Codeception/Lib/GroupManager.php
- tests/data/group_manager_test/group_1
- tests/data/group_manager_test/group_2
- tests/data/group_manager_test/group_3
- tests/data/group_manager_test/groups_with_relative_paths
- tests/data/group_manager_test/missing_directory
- tests/data/group_manager_test/relative_paths
- tests/data/group_manager_test/test_groups
- tests/data/group_manager_test/whitespace_group_test
- tests/unit/Codeception/Lib/GroupManagerTest.php
* GroupManager throws exception if path does not exist
* realpath is applied to absolute paths and paths from group file too.
Fixes #5735 
Relates to #5674
> GroupManager improvements

- src/Codeception/InitTemplate.php
Fixes error output in upgrade4 template
Fixes #5797
> Add missing sayError method to InitTemplate

- CHANGELOG-4.0.md
- composer.json
- src/Codeception/Codecept.php
Changed version number and updated changelog
Depends on #5798 and #5799
> Prepared 4.0.1 release

- app.php
https://codeception.com/docs/07-AdvancedUsage#shell-auto-completion
no longer works in 4.0
> bringing back command completion

- src/Codeception/Command/Run.php
- src/Codeception/Subscriber/Console.php
> add --no-artifacts flag for run command

- src/Codeception/Lib/Generator/Actor.php
comment was indented by 3 spaces, should be 4.
> Fix indentation in generated Actor class

- src/Codeception/Test/Test.php
Fixes https://github.com/Codeception/Codeception/issues/5932
> Add compatibility with phpunit/php-timer:^4.0

- src/Codeception/Template/Bootstrap.php
Fix: https://github.com/Codeception/Codeception/issues/5935
Fix: #5893
> step_decorator methods are not generated #5935

- src/Codeception/Snapshot.php
Closes #5929
Readme update https://github.com/Codeception/codeception.github.com/pull/280
> Add show diff option to snapshots

- src/Codeception/Snapshot.php
- tests/cli/SnapshotCest.php
- tests/data/snapshots/tests/SnapshotNonJsonDataCest.php
- tests/data/snapshots/tests/_data/Snapshot.NotAJsonSnapshot.xml
- tests/data/snapshots/tests/_data/dummy_xml.original.xml
- tests/data/snapshots/tests/_data/dummy_xml.updated.xml
- tests/data/snapshots/tests/_support/Helper/RestoreData.php
- tests/data/snapshots/tests/_support/Snapshot/NotAJsonSnapshot.php
Split from https://github.com/Codeception/Codeception/pull/5920
Closes https://github.com/Codeception/Codeception/issues/5942
Documentation PR https://github.com/Codeception/codeception.github.com/pull/288
> Ability to store non-json snapshots

- tests/cli/SnapshotCest.php
- tests/data/snapshots/tests/SnapshotDisplayDiffCest.php
Add tests to https://github.com/Codeception/Codeception/pull/5930
> Add tests to snapshot diff display

- .travis.yml
- src/Codeception/Coverage/Filter.php
- src/Codeception/Coverage/PhpCodeCoverageFactory.php
- src/Codeception/Coverage/Subscriber/Printer.php
- src/Codeception/Coverage/SuiteSubscriber.php
- tests/cli/IncludedCest.php
- tests/data/claypit/c3.php
- tests/unit/Codeception/Coverage/FilterTest.php
> Compatibility with php-code-coverage v9

- src/Codeception/Codecept.php
- src/Codeception/Command/Run.php
- src/Codeception/Coverage/Subscriber/Printer.php
- src/Codeception/Coverage/Subscriber/RemoteServer.php
- tests/coverage/RemoteWithCoberturaCept.php
Now that PHPUnit has support for Cobertura XML, I've added support so that Codeception can make use of it.
> Added Cobertura XML coverage support

- src/Codeception/Lib/Generator/Actions.php
- src/Codeception/Lib/Generator/Actor.php
- src/Codeception/Util/ReflectionHelper.php
- tests/cli/BuildCest.php
> Generate correct default values in Actions files

- .travis.yml
Composer 2.0 should take care of everything now, mostly testing if this minor change fixes the test runs
> Remove global dependency hirak/prestissimo

- composer.json
- src/Codeception/Lib/ParamsLoader.php
Fixes #6014
Can't find existing test case for ParamsLoader.php.
> add ServerConstAdapter for dotenv v5

- src/Codeception/Event/DispatcherWrapper.php
> [4.1] Improve compatibility logic for the EventDispatcher

- .github/workflows/build.yml
Version condition was incorrent
> CI: Run tests on PHP 5.6

- src/Codeception/Subscriber/Console.php
I overlooked this change in #6107 but noticed it while rebasing #6085
> 5.0 Fix name of IncompleteTestError exception

- src/Codeception/Coverage/PhpCodeCoverageFactory.php
- src/Codeception/Coverage/SuiteSubscriber.php
- tests/coverage/LocalCept.php
- tests/data/claypit/tests/_support/Math/CalcHelper.php
- tests/data/claypit/tests/_support/Math/Divider.php
- tests/data/claypit/tests/math.suite.yml
- tests/data/claypit/tests/math/MathCest.php
- tests/data/claypit/tests/math/MathTest.php
> Add path_coverage setting to enable path and branch coverage

- src/Codeception/Coverage/Subscriber/LocalServer.php
Fixes https://github.com/Codeception/Codeception/issues/5881
> Coverage: Don't attempt to set cookie domain when it is "localhost"

- src/Codeception/Subscriber/Console.php
> Rename editorUrl setting to editor_url

- src/Codeception/Suite.php
Hi,
I would like to open this PR fixing the issue described in #6309
Thank you for you time.
> Adds strict parameter to in_array function comparing object hashes with

- src/Codeception/Subscriber/ErrorHandler.php
- tests/cli/ErrorHandlerCest.php
https://github.com/Codeception/Codeception/discussions/6330
> 0 < exit-state <= 125

- src/Codeception/Lib/Parser.php
- tests/data/namedParameter.php
- tests/unit/Codeception/Lib/ParserTest.php
> Parser fix to allow named parameters named class and namespace

- src/Codeception/Lib/Parser.php
> Better fix for PHP keywords as named parameters

- src/Codeception/Coverage/Filter.php
- src/Codeception/Coverage/Subscriber/Local.php
- src/Codeception/Coverage/SuiteSubscriber.php
- src/Codeception/Suite.php
- src/Codeception/Test/Feature/CodeCoverage.php
- src/Codeception/Test/Test.php
- tests/support/CoverGuy.php
Expected result:
Actual result:
> Do not report local code coverage for remote suites

- src/Codeception/Command/Run.php
- src/Codeception/Test/Descriptor.php
- src/Codeception/Test/Filter/NameFilterIterator.php
- tests/cli/RunCest.php
> Fix filter by data provider case name or number

- src/Codeception/Coverage/Subscriber/Printer.php
- tests/cli/RunCest.php
Fixes the issue which was breaking builds.
> Fix Code coverage HTML report compatibility with PHPUnit 10

- src/Codeception/Exception/ExtensionException.php
Fixes #6370
This patch will be merged to 4.1 and 5.0 branches
> Fix handling of previous exception in ExtensionException 

- src/Codeception/Lib/Generator/Actions.php
- tests/cli/BuildCest.php
- tests/support/CoverGuy.php
> Action generator: Handle self and parent types correctly

- composer.json
- src/Codeception/Lib/Actor/Shared/Pause.php
This REPL is much more powerful and less buggy than Hoa console
but it is not so well designed for running only Codeception code but arbitrary PHP code. Maybe that's for good.
Anyway, there is room for improvement.
> Removed HoaConsole, added PsySH as current REPL

- src/Codeception/Coverage/Filter.php
- src/Codeception/Coverage/Subscriber/Printer.php
Spotted in https://github.com/Codeception/Codeception/pull/6401#issuecomment-1074834010
> Remove BC layer for php-code-coverage < 9

- ext/Recorder.php
> Fix type error in Recorder extension

- composer.json
- src/Codeception/Lib/Console/Output.php
Using Symfony VarDumper for better debugg output
> Var dumper

- src/Codeception/Subscriber/Console.php
It may be useful for custom reporters, e.g. PHPStorm.
This change would allow PHPStorm to extend Console subscriber instead of `PHPUnit\TextUI\DefaultResultPrinter`
> Make Console printHeader and printFooter methods protected

- src/Codeception/Test/Cest.php
- src/Codeception/Test/Test.php
> Report correct status of skipped/incomplete/useless scenario based tests

- CHANGELOG-4.x.md
- src/Codeception/Command/DryRun.php
- src/Codeception/Command/Run.php
- src/Codeception/Configuration.php
- src/Codeception/Lib/Generator/Actions.php
- src/Codeception/Step.php
- src/Codeception/Subscriber/ErrorHandler.php
- tests/cli/DryRunCest.php
- tests/cli/ErrorExpectationsCest.php
- tests/cli/IncludedCest.php
- tests/data/app/view/index.php
- tests/data/app/view/info.php
- tests/data/error_handling/codeception.yml
- tests/data/error_handling/tests/unit/ErrorExceptionTest.php
- tests/data/included/codeception.yml
- tests/data/included/tests/_support/FunctionalTester.php
- tests/data/included/tests/_support/UnitTester.php
- tests/data/included/tests/_support/_generated/.gitignore
- tests/data/included/tests/functional.suite.yml
- tests/data/included/tests/functional/RootApplicationFunctionalTest.php
- tests/data/included/tests/unit.suite.yml
- tests/data/included/tests/unit/RootApplicationUnitTest.php
- tests/data/typed_helper/codeception.yml
- tests/data/typed_helper/tests/_output/.gitignore
- tests/data/typed_helper/tests/_support/Helper/Unit.php
- tests/data/typed_helper/tests/_support/UnitTester.php
- tests/data/typed_helper/tests/_support/_generated/.gitignore
- tests/data/typed_helper/tests/unit.suite.yml
- tests/data/typed_helper/tests/unit/UseTypedHelperCest.php
- tests/unit/Codeception/Subscriber/ErrorHandlerTest.php
@TavoNiievez Please review.
I will fix PHPUnit 10 compatibility separately.
> Merge 4.2 changes to 5.0

- src/Codeception/Lib/ParamsLoader.php
- tests/cli/ConfigParamsCest.php
> Loading .env file must not override existing environment variables

- CHANGELOG-4.x.md
- src/Codeception/Subscriber/BeforeAfterTest.php
- tests/cli/OrderCest.php
Depends on https://github.com/Codeception/Codeception/pull/6475
> Merge 4.2 to 5.0

- docs/modules/Phalcon1.md
- docs/modules/PhpBrowser.markdown
- docs/modules/WebDriver.md
- src/Codeception/Module/Kohana.php
- src/Codeception/Module/WebDriver.php
resolve https://github.com/Codeception/Codeception/issues/6502
> update links 1.8v

- RoboFile.php
- docs/modules/AngularJS.md
- docs/modules/PhpBrowser.md
- docs/modules/WebDriver.md
- ext/Recorder.php
- src/Codeception/Command/SelfUpdate.php
- src/Codeception/Lib/Interfaces/Remote.php
resolve https://github.com/Codeception/Codeception/issues/6510
> update links 2.5

- docs/modules/WebDriver.md
- tests/unit/Codeception/Module/PhpBrowserTest.php
- tests/unit/Codeception/Module/SoapTest.php
- tests/unit/Codeception/Module/TestsForBrowsers.php
- tests/unit/Codeception/Util/UriTest.php
resolve https://github.com/Codeception/Codeception/issues/6512
> update links 3.0

- src/Codeception/Lib/Di.php
dependency injection is missing a check for variadic support as a variadic can just be skipped and just not being passed to the constructor
> / Lib / Di / (enable) variadic defaultability

- .gitattributes
- example/codeception.yml
- example/tests/Acceptance.suite.yml
- example/tests/Acceptance/LoginCest.php
- example/tests/Functional.suite.yml
- example/tests/Functional/LoginCest.php
- example/tests/Support/AcceptanceTester.php
- example/tests/Support/FunctionalTester.php
- example/tests/Support/UnitTester.php
- example/tests/Support/_generated/.gitignore
- example/tests/Unit.suite.yml
- example/tests/Unit/UserTest.php
- example/tests/_output/.gitignore
- src/Codeception/InitTemplate.php
- src/Codeception/Lib/Generator/Actor.php
- src/Codeception/Lib/Generator/Shared/Classname.php
- src/Codeception/Lib/Generator/Snapshot.php
- src/Codeception/Lib/Generator/StepObject.php
- src/Codeception/Lib/Generator/Test.php
- src/Codeception/Template/Acceptance.php
- src/Codeception/Template/Api.php
- src/Codeception/Template/Bootstrap.php
- src/Codeception/Template/Unit.php
- src/Codeception/Util/Shared/Namespaces.php
- tests/cli/BootstrapCest.php
- tests/cli/BootstrapWithNamespaceCest.php
- tests/cli/GenerateTestCept.php
- tests/unit/Codeception/Command/GenerateCestTest.php
- tests/unit/Codeception/Command/GenerateTestTest.php
I fixed all issues raised in #6492 and generated new example test suite
> Example of generated test suite

- src/Codeception/Test/DataProvider.php
- src/Codeception/Test/Loader/Unit.php
- tests/data/data_provider/AbstractDataProviderTest.php
- tests/unit/Codeception/Test/DataProviderTest.php
> Fix DataProvider to properly load PhpUnit dataProviders from abstract classes.

- src/Codeception/Test/Feature/CodeCoverage.php
Example of failing build: https://github.com/Codeception/Codeception/runs/8171557484?check_suite_focus=true
> PHPUnit 10 compatibility: Support new CodeCoverage::stop() signature

- src/Codeception/Test/TestCaseWrapper.php
- tests/cli/RunCest.php
- tests/data/claypit/tests/unit/ResultIsPassedToDependentTest.php
> Unit tests: Pass results to dependent tests

- src/Codeception/Lib/Parser.php
- tests/data/AnonymousClassWithAttributeCest.php
- tests/unit/Codeception/Lib/ParserTest.php
> Improved handling of anonymous classes in parser

- composer.json
But I don't know what the purpose of `*@dev` was.
> Updating for new `codeception/lib-asserts`

- src/Codeception/Test/Unit.php
> Add AllowDynamicProperties attribute to Unit

- src/Codeception/Reporter/JUnitReporter.php
> Fix JUnitReporter compatibility with PHPUnit 10.3

- src/Codeception/Command/Run.php
> Update Support Ukraine link in version string

- .github/workflows/build.yml
resolve https://github.com/Codeception/Codeception/issues/6711
> update actions version

- src/Codeception/Step.php
- tests/unit/Codeception/StepTest.php
Add `instanceof Constraint` condition in `Step::stringifyArgument()`
---
Let me know if i should port for any older versions, or target `master` or a lower version.
> Fix #6714 - use Constraint::toString()

- src/Codeception/Coverage/Filter.php
- tests/unit/Codeception/Coverage/FilterTest.php
> Reimplement coverage:exclude option for PHPUnit 11

- src/Codeception/Coverage/Filter.php
- src/Codeception/Coverage/PhpCodeCoverageFactory.php
- src/Codeception/Coverage/Subscriber/Local.php
- src/Codeception/Coverage/Subscriber/LocalServer.php
- src/Codeception/Coverage/Subscriber/Printer.php
- src/Codeception/Coverage/Subscriber/RemoteServer.php
- src/Codeception/Coverage/SuiteSubscriber.php
This simplifies the code inside `src/Codeception/Coverage`. It does not add any new features.
> Simplify Coverage classes

- .github/dependabot.yml
This should help with keeping the GitHub actions updated on new releases. This will also help with keeping it secure.
Dependabot helps in keeping the supply chain secure https://docs.github.com/en/code-security/dependabot
GitHub actions up to date https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
https://github.com/ossf/scorecard/blob/main/docs/checks.md#dependency-update-tool
> chore: Included githubactions in the dependabot config (#6471)

- src/Codeception/Command/GenerateScenarios.php
Repeating https://github.com/Codeception/Codeception/pull/6758
> Update GenerateScenarios.php: Adding deprecation note

- src/Codeception/Lib/Actor/Shared/Pause.php
- src/Codeception/Lib/Connector/Shared/PhpSuperGlobalsConverter.php
- src/Codeception/Lib/Console/Colorizer.php
- src/Codeception/Lib/Console/DiffFactory.php
- src/Codeception/Lib/Console/Message.php
- src/Codeception/Lib/Console/Output.php
- src/Codeception/Lib/Console/ReplHistory.php
- src/Codeception/Lib/Di.php
- src/Codeception/Lib/Friend.php
- src/Codeception/Lib/Generator/Actions.php
- src/Codeception/Lib/Generator/Cest.php
- src/Codeception/Lib/Generator/GherkinSnippets.php
- src/Codeception/Lib/Generator/Group.php
- src/Codeception/Lib/Generator/Test.php
- src/Codeception/Lib/GroupManager.php
- src/Codeception/Lib/ModuleContainer.php
- src/Codeception/Lib/ParamsLoader.php
- src/Codeception/Lib/Parser.php
- src/Codeception/Lib/PauseShell.php
300 additions & 419 deletions.
> Simplify Lib classes

- src/Codeception/Template/Bootstrap.php
> Fix test suite names in bootstrap command

- src/Codeception/Reporter/HtmlReporter.php
- src/Codeception/Reporter/JUnitReporter.php
- src/Codeception/Reporter/PhpUnitReporter.php
- src/Codeception/Reporter/ReportPrinter.php
> Simplify reporter classes
