docs/03-ModulesAndHelpers.md

This note would have saved me some time integrating Codeception into our codebase.

Adds note that explains helper classes must end in 'Helper.php'

---

src/Codeception/Module/WebDriver.php
tests/data/app/view/form/bug1637.php
tests/unit/Codeception/Module/WebDriverTest.php

This fixes a regression in behavior that was introduced in #1468.
It includes a new unit test to ensure that this behavior can be preserved
going forward in future modifications. I preform two sets of checks so that
if the ancestor::form is catching things we don't risk selecting the wrong
element. Confirmed this works for the tests for issue #1467 as well.

Allow selectOption() to select options not inside forms.

---

src/Codeception/Lib/InnerBrowser.php
tests/data/app/controllers.php
tests/data/app/index.php
tests/data/app/view/register.php
tests/unit/Codeception/Module/PhpBrowserTest.php

The Codeception\Lib\InnerBrowser method getFormUrl() can under certain
conditions create a form URL where the path begins with double slashes.
Conditions for the error:
1. The page with the form lies on a first-level path, e.g.
example.com/register
2. The form has an action without a leading slash, e.g.
<form action="login">
This is valid and browsers understand what is meant.
On Unix the malformed action URL will look like this:
http://example.com//form-target
On Windows this is even worse because dirname() of a first-level directory
returns a backslash (\) instead of a forward slash.
See http://www.webmasterworld.com/php/3752500.htm
Thus a form URL with Codeception run on Windows will look like this:
http://example.com/\/form-target
Both malformed URLs can cause server errors, depending …

Fix double slashes in certain forms submitted by InnerBrowser::submitForm

---

src/Codeception/Subscriber/ErrorHandler.php

The default `errorLevel` is also a string, so it should be evaluated

always eval error level

---

src/Codeception/Coverage/Subscriber/LocalServer.php

When running remote coverage with multiple test suites, Coverage class gets multiple calls to *beforeSuite*, hence *applySettings* triggers *$this->c3Access* to be merged over and over again with yaml config. *array_merge_recursive* behaviour for duplicates is to create an array with two or more values, so the result is e.g 
```php
['http' => 'timeout' => [300, 300, ...]
```
, which is invalid http_stream_context options.
Same goes for *addC3AccessHeader*, which concatenates headers over and over again. While there's no harm in that, it's kind of wrong.
The whole remote coverage client would be better off by using a proper symfony http client, but this would be a bigger refactoring.

Remote context options fix

---

src/Codeception/Lib/InnerBrowser.php

Sometimes HTML select element only has value <option>like this</option>, but not the "value" attribute. So we need to return the text, much like we match it initially.

Fixing matchOption to return the option value in case there is no value attribute

---

src/Codeception/TestCase.php

We had to write
@depends Codeception\TestCase\Cest::something
PHP Warning ("undefined variable this") was triggered when I changed the error reporting in the suite.
With this change @depends works as documented.

 Anonymous function in PHP5.3 does not have $this

---

src/Codeception/Lib/Connector/Symfony2.php

Explanation:
A new `Codeception\Lib\Connector\Symfony2` object is initiated for every test (see https://github.com/Codeception/Codeception/blob/2.0/src/Codeception/Module/Symfony2.php#L104) resetting the hasPerformedRequest property but reusing the old kernel.
In my case that resulted in a user being logged in on the first request of a new test..see #1656 .

Fix Symfony2 bug #1656 where kernel is not shutdown before next test

---

src/Codeception/Module/Laravel4.php

If this line is not present for 170 tests I get (tested on Laravel 5 but it will be the same on Laravel 4):
````
[PDOException]                               
SQLSTATE[08004] [1040] Too many connections
````
For lower number of tests there is no problem of course and I don't want to increase my database connections limit.
As far as I know it's impossible to disconnect in test in ```__after``` method because in that case you will get fatal error ```Call to a member function rollBack() on null```

Added disconnecting from DB to prevent "Too many connections" issue

---

src/Codeception/Module.php

For examlpe: 
```php
$I->sendPATCH('/api/category/1', ['parent_id' => null]);
```
Encode to json:
```json
{"PARENT_CATEGORY_ID":""}
```

Type null converted to empty string

---

src/Codeception/Lib/Connector/Yii2.php

Hi.
There is a problem:
When i'm using ```sendPut``` in functional tests, ```Yii::$app->getRequest()->getBodyParams()``` is empty in controller.
It's happens because Yii2 connector is not putting ```methodParam``` field into POST array.

fix put method in Yii2 connector

---

src/Codeception/Lib/Connector/Laravel5.php
src/Codeception/Module/Laravel5.php

Laravel 5 now has a stable release, so the Laravel 5 module I created and maintained during the Laravel 5 development period can now be added to Codeception. The files in this pull request are the files from https://github.com/janhenkgerritsen/codeception-laravel5.
A sample app similar to the sample app of the Laravel 4 module can be found at https://github.com/janhenkgerritsen/codeception-laravel5-sample. This sample app uses the code in the repository mentioned above. From the sample app I removed the cli test suite, since the tests in that suite only used the Cli module and no functionality specific to the Laravel module was used.
I also added my own personal details as information about the maintainer of the module, is that ok?

Add Laravel 5 module files

---

docs/08-Customization.md
src/Codeception/Command/Bootstrap.php
src/Codeception/Command/GenerateGroup.php
src/Codeception/Command/GeneratePageObject.php
src/Codeception/Command/GenerateStepObject.php
src/Codeception/Command/Shared/FileSystem.php
src/Codeception/Configuration.php
src/Codeception/Util/Autoload.php
tests/cli/GenerateGroupCept.php
tests/cli/GeneratePageObjectCest.php
tests/cli/GenerateStepObjectCept.php
tests/cli/_bootstrap.php
tests/cli/_steps/GeneratorSteps.php
tests/helpers/Shire/Codeception/Module/EmulateModuleHelper.php
tests/unit/Codeception/Command/GenerateStepObjectTest.php
tests/unit/Codeception/Util/AutoloadTest.php
tests/unit/Codeception/Util/MockAutoload.php

Hi!
I've recently found that Codeception doesn't support neither PSR-0 nor PSR-4 autoloading for its Helpers, StepObjects etc. So I took example autoloader with tests from [here](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-4-autoloader-examples.md).
Then I added support for empty namespace prefix, so one can use `Autoload::addNamespace('', 'path')` to load `Foo\Bar\ClassName` from `path/Foo/Bar/ClassName.php`.
Finally, this autoloader is backward compatible with an old autoloader, so all existing code should work as before.
**Old default autoloading:** all classes with `Helper` suffix from `helpers` dir. Namespace doesn't matter, because Autoloader doesn't look in subdirectories.
**New default autoloading:** according to PSR-4, all Helpers in global namespace and …

PSR-4 Autoloader

---

src/Codeception/Lib/InnerBrowser.php
tests/unit/Codeception/Module/PhpBrowserTest.php
tests/unit/Codeception/Module/TestsForWeb.php

When `amOnPage` is not called and try to call some function like fillField (with XPath-rule) the codeception quiet crashed without any errors.
It happened because `crawler->filterXPath` wrapped by "`@`".
This PR provide additional check on `crawler` exist

Fix quiet crash when crawler is null

---

src/Codeception/Lib/InnerBrowser.php
tests/data/app/view/form/submitform_ampersands.php
tests/data/app/view/form/submitform_multiple.php
tests/unit/Codeception/Module/TestsForWeb.php

Removed submitForm's reliance on using parse_str and parse_url to
generate params (which caused unexpected side-effects like failing
for values with ampersands).
Modified the css selector for input elements so disabled input
elements don't get sent default values.
Modifications to ensure multiple values get sent correctly.

More dynamic submitForm

---

src/Codeception/PHPUnit/ResultPrinter/HTML.php

Test "name" will render the method test name and any data provided as
an argument to the test method.  If that data is HTML, it can
influence the browser when viewing the HTML report, namely a chance
for XSS.
Fixes #1712

HTML entity encode test "name" for HTML reports

---

src/Codeception/Lib/Driver/Db.php
src/Codeception/Lib/Driver/SqlSrv.php
src/Codeception/Lib/Driver/Sqlite.php
src/Codeception/Lib/Driver/SqliteGeneral.php
src/Codeception/Module/Db.php

We have the problem that the primary key isn't named 'id'. That means that the cleanup of the Module 'Db' not delete our entries. This fix helped us and should help everyone else who have the same problem.

Ability to have another primary key then 'id'

---

src/Codeception/Lib/Connector/Yii1.php

Now Yii1 connector has checks to detect if Yii application actually *has* a `log` component. 
This patch fixes #1753

Allow Yii1 application to live without `log` component

---

src/Codeception/Lib/Connector/Laravel5.php

This is a fix for #1748, based on the fix proposed in #1750 by @jedrzej. 
I confirmed the issue when I did a `composer update` on the sample application, and this commit fixes the issue.

Fix for undefined method Symfony\Component\HttpFoundation\Request::route()

---

src/Codeception/Module/WebDriver.php

The tag `@internal` was causing PhpStorm to consider the method as internal. Additionally, it has no meaning for this method, since there is no variable `$element` used in the method the PhpDoc describes - `waitForText`

Remove unnecessary parameter from Webdriver PHPDoc

---

src/Codeception/Lib/InnerBrowser.php
src/Codeception/Module/WebDriver.php
tests/unit/Codeception/Module/TestsForWeb.php

submitForm now accepts boolean values for checkbox fields, mapping them to the actual checkbox field value if found.
Also minor cleanup of conditionals in WebDriver's submitForm.

Allow bool values for checkboxes in submitForm

---

src/Codeception/Lib/InnerBrowser.php
src/Codeception/Lib/Interfaces/Web.php
src/Codeception/Module/WebDriver.php
tests/data/app/view/form/field_values.php
tests/unit/Codeception/Module/TestsForWeb.php

Allows quickly checking multiple form field values with an array with InnerBrowser and WebDriver.
Also updated seeInField functionality to allow comparing an empty value to an unselected combo box.
Created simple tests and updated documentation in Interfaces/Web.php (IIRC that's the only place needed? Let me know if otherwise.)
Example:
```php
$I->seeInFormFields('#myform', [
'checkbox[]' => [
'see test one',
'see test two',
],
'radio1' => 'see test one',
'checkbox1' => true,
'checkbox2' => false,
'select1' => 'see test one',
'select2' => [
'see test one',
'see test two',
'see test three'
]
]);
```
Can be paired with submitForm for easy testing:
```php
$form = [
'field1' => 'value',
'field2' => 'another value',
'checkbox1' => true,
// ...
];
$I->submitForm('#my-form', $form, …
```

Added seeInFormFields for Web tests

---

src/Codeception/Lib/Driver/Db.php

Only a small change to #1727 .
If the table is in another database the string is like \`other_database.table_name`. Removing the backtick works well:
I know that ideally should escape the string, but there are [plenty](https://github.com/Codeception/Codeception/blob/2.0/src/Codeception/Lib/Driver/MySql.php#L26) of [lines](https://github.com/Codeception/Codeception/blob/2.0/src/Codeception/Lib/Driver/Db.php#L168) [where](https://github.com/Codeception/Codeception/blob/2.0/src/Codeception/Lib/Driver/Oci.php#L8) is [not covered](https://github.com/Codeception/Codeception/blob/2.0/src/Codeception/Module/Dbh.php#L91) 
```php
$I->haveInDatabase('other_db.my_table', $data); //was working until 2.0.10
$I->haveInDatabase('my-speçial-table-ñame', $data); //never worked
```
So I think that escaping …

Support for multiple databases

---

src/Codeception/Module/FTP.php

Hello Michael,
I found an issue of FTP module:
1. Passive mode do not get config value. Line 578 => You compare `$this->config['passive’]` with enabled instead of `true` or `1`
2. (Most important) You define passive mode before login, and you have to set it just after login.
I found the solution here :
- http://stackoverflow.com/a/1612323/3437153
- http://biostall.com/phps-ftp_nlist-returning-false-even-when-files-definitely-exist
With this pull request, FTP Module is fully operational.

FTP Passive Mode

---

src/Codeception/Module/Laravel5.php

Issue: https://github.com/Codeception/Codeception/issues/1783

Add `packages` option for application packages.

---

src/Codeception/Lib/InnerBrowser.php
src/Codeception/Lib/Interfaces/Web.php
src/Codeception/Module/WebDriver.php
tests/unit/Codeception/Module/TestsForWeb.php

- Fixes #1797
- Updated function to allow submitting array parameter values like
for PhpBrowser
- Updated PhpBrowser so array of booleans could be sent - separated
into separate function
- Cleaned up WebDriver's submitForm a bit
- Added some documentation
- Added a few more tests

WebDriver submitForm allows array parameter values

---

src/Codeception/Lib/InnerBrowser.php
tests/unit/Codeception/Module/TestsForWeb.php

Textarea node doesn't have 'value' attribute, and an issue with conditions meant it wasn't working correctly.

Fix for submitForm default value for a textarea

---

src/Codeception/Lib/Connector/Guzzle.php
src/Codeception/Module/PhpBrowser.php
tests/unit/Codeception/Module/PhpBrowserTest.php

- Created deleteHeader
- Allow deleting a header with an empty value when setting (since
setting to an empty value doesn't make sense anyway)
- Added documentation for setHeader and deleteHeader
- Added simple test
Provides a solution for #1791

Added deleteHeader and docs for PhpBrowser

---

src/Codeception/Command/Console.php

./codecept console accept did not work when namespace attribute occured in codeception.yml file. Helper classes could not be in namespaces.

fix namespace ignoring when console is invoked

---

src/Codeception/Module/Laravel4.php

I would like to add support for functional testing of Laravel Artisan commands to the Laravel4 module—at least I think this is a bit more friendly than just using `$I->grabService('artisan')`, etc.

support functional testing of Laravel Artisan commands

---

src/Codeception/Module/Yii2.php

This patch enables https support for functional suites.
Also this patch fix verbose output for functional suites.
E.g.: ../vendor/bin/codecept run functional -vvv
Was:
```
Scenario:
* I am on page "/index-test.php/site/login"
[Response] 200
[Page] http://localhost/index-test.php/site/login
```
After fix:
```
Scenario:
* I am on page "/index-test.php/site/login"
[Response] 200
[Page] http://YOURDOMAIN/index-test.php/site/login
```

Fix https support and verbose output

---

src/Codeception/Util/Stub.php
tests/data/DummyOverloadableClass.php
tests/data/claypit/tests/dummy/_bootstrap.php
tests/unit/Codeception/Util/StubTest.php

The `Stub::*` methods all tend to set a `__mocked` property on the mocked classes. When attempting to mock a class that implements a `__set` method that doesn't allow (as PHP calls it) _"overloading"_, this results in a PHPUnit exception.
This PR addresses this issue by checking the class for an existing `__set` method. If such a method exists, the `__mocked` flag is not set.
This check is also used when attempting to add a non-existent property to classes with a `__set` method. These properties will be added, but a `PHPUnit_Framework_Exception` will be thrown if this fails.
The `__mocked` flag was primarily (only?) used in the `Stub::update` call (to change the mock's behavior on the fly). the `__mocked` property check has been replaced with an `instanceof …

suggested fix for issue #1785: overloading and __set bug

---

src/Codeception/PHPUnit/Listener.php
tests/cli/OrderCest.php
tests/data/claypit/tests/_helpers/OrderHelper.php
tests/data/claypit/tests/order/CanCantFailCept.php
tests/data/claypit/tests/order/OrderGuy.php

- Using can/cant causes cleanup code to be called, which causes an
exception calling subsequent tests: for instance calling canSee()
followed by amOnPage (or canSee twice).
- Fixes #1647 #1354 and #1111
- Same as pull request #1807 - but with some added test code

Fix for can/cant causing failure in 2.0

---

tests/unit/Codeception/Module/RestTest.php

Unit tests for `grabDataFromResponseByJsonPath()` are missing. Created them using tests of `grabDataFromJsonResponse()` as template.

Add unit tests for grabDataFromResponseByJsonPath()

---

src/Codeception/Lib/InnerBrowser.php
src/Codeception/Lib/Interfaces/Web.php
src/Codeception/Module/WebDriver.php
tests/data/app/view/form/submit_adjacentforms.php
tests/unit/Codeception/Module/TestsForWeb.php

- submitForm refactored to use DomCrawler's Form object, and grab
defualt values from it instead of filtering the crawler for
fields manually.
- getFormFor refactored so it creates its own crawler.  Needed so
input fields in disabled fieldsets aren't submitted
- Created getFormValuesFor to get an array of values as expected by
submitForm
- Created proceedSubmitForm which is called instead of the deleted
submitFormWithButton
- Refactored getFormUrl into getFormUrl, getAbsoluteUrlFor and
mergeUrl methods
- More docblock comments for protected/private methods
- Minor cleanup

Refactoring to merge fillField/submitForm

---

src/Codeception/Lib/Actor/Shared/Comment.php

This is just a small fix for english output. 
Right now if you do:
```php
$I->am(' Administrator');
```
You will get:
```
* As a Administrator
```
After the patch you will get:
```
* As an Administrator
```

fix $I->am when User name starts with vowel

---

src/Codeception/Lib/Console/Message.php
src/Codeception/Subscriber/Console.php

Fixed my own bug with ugly output when ```codeception run```. 
Works only for *nix terminals with ```tput```.

#1798 fix ugly output in unix terminals

---

docs/06-UnitTests.md

The unit test examples that use database functionality like the seeInDatabase() method call need to have the Db module listed in the unit suite configuration file. The module was not enabled by default after running bootstrap and generate:test, so I think it would be very helpful to mention this detail on the guide for Unit Tests. It took me a while to figure out why the test run failed with an exception about the missing function in the UnitTester class.
Thank you, Markus

Improvement to the unit test case examples

---

src/Codeception/TestLoader.php

Hello,
in our projects we have separated modules packed with tests.
When deploying to Linux server, automated scripts create
symlinks, instead of copying these tests to a directory and
run them. Symphony Finder doesnt follow these
symlinks by default, so I suggest a change to allow such behavior.
(Moved from master to branch 2.0 based on #1860)

Allow following symlinks when searching for tests

---

src/Codeception/Configuration.php

Currently log path is assumed as a sub-folder of the configuration folder which means codeception cannot be run when located in a readonly folder.

support for log absolute path

---

docs/03-ModulesAndHelpers.md
docs/04-AcceptanceTests.md
docs/10-WebServices.md
src/Codeception/Command/Bootstrap.php
src/Codeception/Configuration.php
src/Codeception/Lib/Console/Output.php
src/Codeception/Lib/ModuleContainer.php
src/Codeception/Module/AMQP.php
src/Codeception/Module/Db.php
src/Codeception/Module/Doctrine2.php
src/Codeception/Module/Facebook.php
src/Codeception/Module/Laravel4.php
src/Codeception/Module/Laravel5.php
src/Codeception/Module/Phalcon1.php
src/Codeception/Module/PhpBrowser.php
src/Codeception/Module/REST.php
src/Codeception/Module/Silex.php
src/Codeception/Module/Symfony2.php
src/Codeception/Module/WebDriver.php
src/Codeception/Module/Yii2.php
src/Codeception/Subscriber/Console.php
tests/unit/Codeception/Lib/ModuleContainerTest.php

Module configuration can be set while lising module in `enabled` sections like here:
``` yaml
modules:
enabled:
- WebDriver:
browser: firefox
- \Helper\Acceptance
```
Other examples:
https://gist.github.com/DavertMik/79a540dce15a7a0d81bd

Simplified module configuration format

---

src/Codeception/Lib/InnerBrowser.php
tests/data/app/view/index.php
tests/unit/Codeception/Module/TestsForWeb.php

see/dontSee should test against text rather than HTML content.  Solution for #1873

Strip tags for see/dontSee in InnerBrowser

---

tests/unit/Codeception/Module/WebDriverTest.php

In commit 002563602837195015ef1671154ed8775d382a78 @davert forgot to change port number to 4444 in WebDriverTest skip message.

fix port number in WebDriverTest skip message

---

src/Codeception/Actor.php
src/Codeception/Lib/Generator/Actions.php

PhpStorm IDE reports an undefined field `scenario` in generated *Actions trait.
For example here:
```
public function canSee($text, $selector = null) {
return $this->scenario->runStep(new \Codeception\Step\ConditionalAssertion('see', func_get_args()));
}
```
I think it makes sense, because there is no such field defined in the trait and you can't be sure that the trait will always be inserted into a class that has the field defined.
There is a possibility to define a field in the trait itself, but if it conflicts with the field of same name in the imported class PHP issues either E_STRICT (if the definition is the same) or E_FATAL (if it's not the same) - see http://php.net/manual/en/language.oop5.traits.php#language.oop5.traits.properties .
Therefore I suggest to declare an abstract …

Fix undefined field in generated Actions trait

---

src/Codeception/Module/Doctrine2.php

The exception was :
```
[Codeception\Exception\ModuleConfigException]
Doctrine2 module is not configured!
Doctrine2 module requires EntityManager explicitly set.
You can use your bootstrap file to assign the EntityManager:
\Codeception\Module\Doctrine2::$em = $em
```
it should answer to question #1803

when setting Symfony2 as dependency of Doctrine2, whe should not have an exception

---

src/Codeception/Command/GenerateCept.php

Currently when we generate cept file using `generate:cept` command we see following message in the terminal:
Test was created in JustTestCept.php
This message looks less informative then `generate:cest` command's message which looks like this:
Test was created in /path/to/the/project/folder/tests/acceptance/JustTestCest.php

Improved console log message for generated cept files.

---

src/Codeception/Lib/Connector/Yii1.php

Fixed issue #1933.
Based on [Yii2 code](https://github.com/Codeception/Codeception/blob/2.0.13/src/Codeception/Lib/Connector/Yii2.php#L51).

$_POST is now cleared among GET requests

---

src/Codeception/Module/Silex.php

Sliex module must extend \Codeception\Lib\Framework as well as Symfony 2 module.
In order to Rest module set $this->isFunctional to true only for Framework instance.
```
if ($this->connectionModule instanceof Framework) {
$this->isFunctional = true;
}
```

silex must extend Framework

---

src/Codeception/Lib/Connector/ZF2.php

Related to issue #1928
This change allows to use raw body in POST and other methods.
I haven't tested this change because I am not using ZF2, but I haven't introduced any new method calls and it should just work.

Pass raw body to ZF2 if it is present in request

---

src/Codeception/Lib/Connector/ZF1.php

1. Set raw request body, it is particularly necessary when using REST module with application/json content-type.
2. Catch exception and close output buffer to avoid 'risky test' mark, allows testing exceptions thrown by controllers.

ZF1 connector improvements in 2.0 branch

---

src/Codeception/Module/Doctrine2.php

Added an option to set a specific EntityManager for the Doctrine2 module. By default the EntityManager will be 'doctrine.orm.entity_manager'.

Added optional EntityManager configuration to Doctrine2 module

---

src/Codeception/Lib/InnerBrowser.php

Several commands in InnerBrowser have documentation about [array selectors](http://codeception.com/docs/modules/PhpBrowser#seeElement), however such selectors give you the **[ErrorException] Array to string conversion** exception.
I've fixed this and also added support of array selectors to other commands, which have $selector as optional parameter to make things more consistent.

Fixed array to string conversion in InnerBroser commands.

---

src/Codeception/Module/Db.php

This causes an error during test run, I think it was added during a merge of older branches and is not needed.

remove merged duplicated (and older) line

---

src/Codeception/Module/Phalcon1.php

* Improved dependency injector container check 
* Used short syntax for arrays
**Important**
* `Phalcon1::_after` now uses `isset($this->di['db'])` instead `$this->di->has('db')` — in some cases di not initialized here (for example when test fails)

Phalcon1 DI

---

src/Codeception/Lib/InnerBrowser.php
tests/data/app/view/form/example17.php
tests/unit/Codeception/Module/PhpBrowserTest.php
tests/unit/Codeception/Module/TestsForWeb.php

- Reverted changes to getFormValuesFor
- Created a different method to get the singular value for
"seeInField" testing
- Added test for multi-dimensional array submission in
PhpBrowserTest (functionality not yet implemented in WebDriver)
@DavertMik - I wanted to keep the getFormValuesFor function returning multi-dimensional arrays, so they can be overridden by calls to submitForm.  I plan to update seeInField so it accepts multi-dimensional arrays as well, so one can call submitForm/seeInFormFields using the same array (not quite there yet.)
Please have a quick look when you have a moment, and let me know if you have any concerns!
Thanks

Alternative fix for regression #1923

---

src/Codeception/Lib/Connector/Yii2.php

I have not found any measurable slowdown for 89 tests and 412 assertions even with profile and trace levels.
And It is very important to me to have logs in tests.
Here is my logger config:
```
'log' => [
'traceLevel' => 3,
'targets' => [
[
'class' => 'yii\log\FileTarget',
'levels' => ['error', 'warning', 'info', 'profile', 'trace'],
],
],
],
```

Enable logging in Yii2

---

docs/modules/MongoDb.md

The highlighting is slightly broke on the site. for "haveInCollection"

syntax highlighting fix by adding missing "<?php"

---

src/Codeception/Lib/Driver/MongoDb.php

fixed a problem with whitespaces in filenames when loading mongodb dumps #1997

fixed a problem with whitespaces in filenames when loading mongodb dumps

---

src/Codeception/Module/Phalcon1.php

In some cases Phalcon's model message has more than one field.
For example:
```php
public function validation()
{
$this->validate(new Uniqueness(
[
'field' => ['phone', 'email'],
'message' => 'User already exists!'
]
));
if ($this->validationHasFailed() == true) {
return false;
}
return true;
}
```
In this case `$message->getField()` returns:
```
Array
(
[0] => phone
[1] => email
)
```

Phalcon1: Fixed getting fields

---

src/Codeception/Lib/Connector/Guzzle.php

For now it is impossible to send Content-Type Http request header

Bug fix for Guzzle Connector headers

---

appveyor.yml
composer.lock
src/Codeception/Module/Db.php
tests/unit/Codeception/Lib/Driver/PostgresTest.php
tests/unit/Codeception/Lib/Driver/SqliteTest.php
tests/unit/Codeception/Module/DbTest.php

I refactored SqliteTest and PostgresTest to be more in line with MysqlTest:
Moved initial setup to setUpBeforeClass, 
load to setUp, 
cleanup to tearDown.

Db test refactoring

---

.travis.yml

I created branches of zf1 and zf2 tests to test master.
3 ZF1 tests will fail, because 2 commits were lost by merging changes from 2.0 to master branch.
Commits:
https://github.com/Codeception/Codeception/commit/5546a506aaa4f7573bc16315d579afb72a225848
https://github.com/Codeception/Codeception/commit/1b343730376c4cf0b5008e99e0f04863e8a4374f
Merge which lost them:
https://github.com/Codeception/Codeception/commit/92106d051a6ee447393407a03ad516e7351f6f25

Use 2.1 branch of zf1 and zf2 tests

---

docs/modules/REST.md

It appears as though the old function was left as a typo. Please reject this commit if I'm mistaken. :)

Fix docs sample code to use the correct function

---

src/Codeception/Module/Db.php
tests/unit/Codeception/Module/DbTest.php

Codeception 2.1 executes tests in random order.
If percentage of db tests is low and tests are being execute in slow environment, like Travis, database connection often gets lost.
To solve this issue, I implemented reconnect option which creates a new connection before each scenario and drops it after scenario.

Reconnect option for Db module

---

src/Codeception/Module/WebDriver.php

This allows you to pass all possible arguments to php-webdriver's create()
from settings in the suite.yml file.

Allow request_timeout_in_ms and connection_timeout_in_ms for WebDriver

---

src/Codeception/Lib/Console/Message.php
src/Codeception/Subscriber/Console.php
tests/unit/Codeception/Lib/Console/MessageTest.php

Modified Message::cut method to cut text at length specified in parameter.

Message cut length fix

---

src/Codeception/Lib/Connector/Symfony2.php

Related to #2025 
I found this change fixed all the problems I was having when using doctrine to create data in a transaction.
Unsure if it's the right solution, but means my tests now work.

Fix doctrine issues after first request is made.

---

src/Codeception/Lib/InnerBrowser.php
tests/data/app/view/form/names-sq-brackets.php
tests/unit/Codeception/Module/TestsForWeb.php

Setting values multiple times on fields with square brackets in their names resulted in the Field not being matched in matchFormField.
Radio input fields were not being set correctly in selectOptions.
Should fix #2062

Fix for InnerBrowser setting values multiple times

---

docs/modules/MongoDb.md
src/Codeception/Module/MongoDb.php
tests/unit/Codeception/Module/MongoDbTest.php

No one is using authentication in MongoDb on dev machine.
Sorry, I don't read 'CONTRIBUTING GUIDE'.

MongoDb. Remove not necessary config fields 'user' and 'password'.

---

src/Codeception/Lib/InnerBrowser.php

After submitting a form, proceedSubmitForm should set $this->forms to an empty array.
Fixes #2087

proceedSubmitForm clear forms array after submit

---

src/Codeception/Lib/Connector/Guzzle6.php

The cookies were later [removed by guzzle](https://github.com/guzzle/guzzle/blob/9c43893a8e580d8401e4210cebe038d850341012/src/Cookie/CookieJar.php#L217) because the domain did not match.

Fixed PhpBrowser::setCookie() method

---

src/Codeception/Lib/Connector/Guzzle6.php

My god, which idiot wrote the Guzzle6 class???
The flattenHeaders method completely broke my tests because it threw away every cookie except the first and since PHPSESSID was the second cookie in response, session did not work at all.
Then there is #2104 because of which setCookie did not work at all so I couldn't set PHPSESSID manually either. The bug is again in Guzzle6 class.
Oh and by the way there are problems with cookies even when using WebDriver instead of PhpBrowser. I was not able to fix that. https://github.com/Codeception/Codeception/issues/766#issuecomment-115005827

Fixed handling multiple cookies

---

src/Codeception/Lib/Connector/Guzzle.php

Generally, array_merge_recursive($a, $b) does it's bad in case $a = ['key' => 'value1']; $b = ['key' => 'value2'];
array_replace_recursive prevents creation of arrays in case of same key=>value pairs are present in both arrays.
Detailed issue:
If someone tries to update USER_AGENT should be passed to server during request, the resulting USER_AGENT header receives comma separated value:
Symfony2 BrowserKit, <HERE COMES MY VALUE>
WURFL doesn't detect properly headers with such prepend for IOS devices.
By bad luck, for Android user agent header, WURFL does it's job correctly.

Updating requestOptions generation

---

docs/modules/Laravel4.md
docs/modules/Laravel5.md
docs/modules/Lumen.md
docs/modules/Phalcon1.md
docs/modules/PhpBrowser.md
docs/modules/Silex.md
docs/modules/Symfony2.md
docs/modules/WebDriver.md
docs/modules/Yii1.md
docs/modules/Yii2.md
docs/modules/ZF1.md
docs/modules/ZF2.md
src/Codeception/Lib/Interfaces/Web.php
src/Codeception/Module/WebDriver.php
tests/data/claypit/tests/_support/_generated/AbsolutelyOtherGuyActions.php
tests/data/claypit/tests/_support/_generated/OtherGuyActions.php
tests/support/_generated/WebGuyActions.php

Corrected "Do you agree to **out** terms?" to "Do you agree to **our** terms?" where ever it showed up.
I wasn't 100% sure if some of these files were auto-generated, and if so, how to regenerate them. Figured I'd submit all the fixes for now.

Corected all instances of out to our in documentation

---

src/Codeception/Lib/InnerBrowser.php
tests/unit/Codeception/Module/TestsForWeb.php

Text fields, such as passwords or fields that contain free text, can use
ampersands and DOMNode property textContent should be set instead of
nodeValue to prevent "unterminated entity reference" errors

Fix for fillField using values that contain ampersands

---

.travis.yml

Laravel5 test suite breaks build in PHP 5.4 environment.
$ composer install -d frameworks-l5 --no-dev  --prefer-dist
Loading composer repositories with package information
ReadReading composReading composer.json of codeception/codeception (2.1)Installing dependencies
Your requirements could not be resolved to an installable set of packages.
Problem 1
- laravel/framework v5.1.6 requires php >=5.5.9 -> your PHP version (5.4.37) does not satisfy that requirement.

Don't test Laravel 5 on PHP 5.4

---

src/Codeception/Util/Uri.php

So, in config main site's URL is http://google.com/
Some of my pages are https://
But trying to access them, I get errors.
When dig into, found that all new URLs are build based on base_uri, adding path, query, if any.
Adding also scheme solved the issue.
Actual:
Uri::mergeUrls('http://google.com/';, 'https://google.com/account/')  === 'http://google.com/account/';
Expecting:
Uri::mergeUrls('http://google.com/';, 'https://google.com/account/')  === 'https://google.com/account/';

Missing HTTPS when trying to access protected pages

---

src/Codeception/Lib/Connector/Yii2.php

I have a project using Yii 2.0.2 version, but when I upgraded to 2.0.5, all my tests that contains CSRF validation starts to failed. I investigated and figured out that there was a changed in cookie handling on this commit which is part of 2.0.3 update. https://github.com/yiisoft/yii2/commit/0a6cd6190b851db89120572259ae8ca0ade9c2cb#diff-d87d70b11324cad0f14e3077c0f2c847

Yii2 cookie handling issue

---

src/Codeception/Module/WebDriver.php

Fixes `PHP Fatal error:  Call to undefined method Codeception\Module\WebDriver::elementOrFail()`
@DavertMik

Fix waitForElementChange fatal error

---

docs/02-GettingStarted.md

Fix small typo in GettingStarted documentation

---

src/Codeception/Lib/Generator/Actions.php

When not using any module in configuration, `$modules` array doesn't filled in `__construct`, so this generating warning when iterating over this array in `produce()` method.

Updated default value

---

src/Codeception/Configuration.php

Files in the '_envs' folder are currently only recognized
if they are ending with `.dist.yml`.
The environment builder creates those files without the
`.dist` in its name wich is very confusing.
Fixes Codeception/Codeception#1944

Find also environment files without `.dist` in its name

---

src/Codeception/Lib/Driver/PostgreSql.php
tests/data/dumps/postgres.sql

This commit is to fix the the point of undetected dollar quoting when $$ is not at the beginning of the line. `trim` has been removed from `strpos(trim($sqlLine), '$$')` as it's no longer required.

Fix Codeception/Codeception#2185 when $$ not at line start ONLY

---

src/Codeception/Lib/Driver/Db.php
src/Codeception/Lib/Driver/MySql.php
src/Codeception/Lib/Driver/Oci.php
src/Codeception/Lib/Driver/PostgreSql.php
src/Codeception/Lib/Driver/SqlSrv.php

Use getQuotedName() for escaping table name in DB Driver's select().
Set default quotes to double quotes.
Select methods of some implementation classes became identical to DB::select after this change, so I removed them.
Also I removed deleteQuery from SqlSrv, because it became identical to DB::deleteQuery after earlier change.

Quoted table name in Db::select, removed identical methods from child classes

---

src/Codeception/Coverage/Subscriber/RemoteServer.php

find_put_contents couldn't open stream because of wrong path. Problems appeared only for those having temp dirs with dots like for users of EasyPHP default installation.
Fixes issue: #2244

Fixed removing dots from path and temp file, causing errors in html coverage generation

---

src/Codeception/Lib/Parser.php

Due to the way for loops are implemented in php, the count function will run every iteration of the loop. Therefore, moving the count to a variable, calculated before the start of the loop, improves performance (less function calls).

Improves performance of getClassesFromFile method of the parser

---

src/Codeception/Module/Yii2.php

if "config" section not exists, all tests have failed. This commit fix it (and also style fix for long line)

fix "undefined index config" in 2.1.2 and Yii

---

composer.json

I tested different versions of Guzzle 4 and discovered that 4.1.4 is the oldest version which passes all PhpBrowserTest tests.

Changed the oldest supported version of Guzzle to 4.1.4

---

src/Codeception/Util/JsonArray.php
tests/unit/Codeception/Module/RestTest.php

Issue: https://github.com/Codeception/Codeception/issues/1788
i've investigated a bit more and found out that it would be better be go with php way - make it array_diff does http://php.net/manual/ru/function.array-diff.php
Note:
Two elements are considered equal if and only if (string) $elem1 === (string) $elem2. In words: when the string representation is the same.
but with current code it will look like simple non-strict check.
So i've changed that condition and applied tests, to proof new behaviour. 
Please verify.

fixed issue1788: removed strict check

---

src/Codeception/Module/SOAP.php

I hope it will be in 2.1, because SOAP is broken without DependsOnModule interface.

Add Interface DependsOnModule to SOAP module

---

src/Codeception/Module.php

The `is_scalar` method was causing issues when `$v` was `NULL` because, as said in [the docs](http://php.net/manual/en/function.is-scalar.php) it returns `false` on this case. The function so continued on and created an empty string, as reported on #2264

Fixing the scalarizeArray to be aware of NULL fields, closing #2264

---

src/Codeception/Lib/GroupManager.php
tests/data/whitespace_group_test
tests/unit/Codeception/Lib/GroupManagerTest.php

Hi,
Recently we had an issue where Codeception was running all of our acceptance tests when trying to use our group files. We discovered this was because there where extra blank lines at the end of some of them.
This happens because Configuration::projectDir() was appended to the file name, but the filename would be blank if there was a blank line. Codeception would then interpret the group as containing the entire project and so would run every test.
If you need anymore information to reproduce, just let me know.
Thanks!

Fix a bug where blank lines in a groups file would run every test in the project

---

src/Codeception/Module/WebDriver.php

The behavior of seeNumberOfElements and seeElement is not the same
as seeNumberOfElements does also count invisible elements.
To check for elements in DOM there is a seperate method
seeElementInDOM.
The method `seeNumberOfElementsInDOM` has been added and the behavior
of `seeNumberOfElements` has been changed to not respect invisible
elements.
Fixes #2303

WebDriver->seeNumberOfElements should only count visible elements

---

src/Codeception/Module/WebDriver.php
tests/unit/Codeception/Module/WebDriverTest.php

This PR filters cookie domains that don´t match the config URL and therefore prevents an `InvalidCookieDomainException` (which prevents all cookies from being saved).
Fixes #2250

Filter invalid cookie domains in session snapshots

---

docs/modules/Symfony2.md
src/Codeception/Module/Symfony2.php

The description of var_path is also required for symfony2 applications.
As a generic good practice tests are located in symfony2 bundles under src. Thus it is required to specify var_path too so the Symfony2 module is aware of where the bootstrap cache is loaded from. app_path alone just tells where the AppKernel is supposed to be loaded from.

Add details about required var_path configuration parameter for Symfony2 module

---

src/Codeception/Lib/Connector/Guzzle.php
src/Codeception/Lib/Connector/Guzzle6.php

I disabled followRedirect in PhpBrowser (`$this->getModule('PhpBrowser')->client->followRedirects(false)`) to test 301 response with REST module like:
$I->seeResponseCodeIs(301);
But the endpoind I want to test returns a 301 response with `<meta http-equiv="refresh" />` in body (the Symfony2 way).
So Guzzle recode the status code to 302 and my test fails.

Guzzle connector override status code to 302 if a meta refresh exists in body

---

src/Codeception/Lib/Connector/ZF1.php

I spent 2 hours trying to figure out why parameters persist between requests in the same scenario, here is the fix.

ZF1: Clear $_POST and $_GET after each request

---

docs/modules/REST.md

Typo used deprecated function instead of actul grabDataFromResponseByJsonPath

Typo change in example

---

src/Codeception/Module/Yii1.php

It was not possible to change the host from localhost to something else.
I now use the URL config to extract the host and set the HTTP_HOST for the client.

Allow other HTTP_HOSTs then localhost

---

src/Codeception/Exception/ElementNotFound.php
src/Codeception/PHPUnit/Constraint/WebDriver.php
src/Codeception/PHPUnit/Constraint/WebDriverNot.php
src/Codeception/Util/Locator.php
tests/unit/Codeception/Constraints/WebDriverConstraintTest.php
tests/unit/Codeception/Constraints/WebDriverNotConstraintTest.php
tests/unit/Codeception/Util/LocatorTest.php

The "fail" method of both Codeception\PHPUnit\Constraint\WebDriver and WebDriverNot takes in a
$selector for error reporting purposes. The $selector is assumed to be a string and interpolated
into the error message, but there are cases where the $selector is actually an array or WebDriverBy
object. When that's the case, this method triggers a "Array to string conversion" PHP notice.
I noticed this in a test case I have that calls Codeception\Module\WebDriver->see():
$I->see('Reviewers', ["css" => ".submission_nav .box.current"])
This test failed because the ".submission_nav" element disappeared, but instead of a descriptive
failure message I got "[PHPUnit_Framework_Exception] Array to string conversion".
To reduce code duplication, I extracted the logic used in ElementNotFound for …

Fix "Array to string conversion" errors

---

CHANGELOG.md
src/Codeception/Module/Symfony2.php

In Symfony2, when a method that need the profiler is called, it will fail instead of crashing.
Fixed #652

Symfony2: Fail when profile is not set.

---

src/Codeception/Lib/InnerBrowser.php

Set request body to url-encoded parameter list for non-GET requests in Framework modules (Guzzle does it itself) #2342

Set request body to url-encoded parameter list 

---

src/Codeception/Configuration.php

This should allow having something like:
_envs
&nbsp;&nbsp;&nbsp;&nbsp;browsers
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;firefox.yml
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&hellip;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;chrome.yml

Allow subfolders for environments grouping

---

src/Codeception/Lib/Connector/Lumen.php
src/Codeception/Lib/Connector/Symfony2.php
src/Codeception/Lib/Connector/Yii1.php
src/Codeception/Lib/Connector/Yii2.php
src/Codeception/Module/Lumen.php
src/Codeception/Module/Silex.php
src/Codeception/Module/Symfony2.php
src/Codeception/Module/Yii1.php
src/Codeception/Module/Yii2.php

I made a blunder in a previous pull request #2371

Interface SupportsDomainRouting is for modules, not for connectors

---

CHANGELOG.md
RoboFile.php
src/Codeception/Module/REST.php
src/Codeception/Util/JsonType.php
tests/unit/Codeception/Module/RestTest.php
tests/unit/Codeception/Util/JsonArrayTest.php
tests/unit/Codeception/Util/JsonTypeTest.php

REST module can now also check JSON data by field types. 
Idea taken from #2373
Examples:
```json
"{\"id\":11,\"retweeted\":false,\"in_reply_to_screen_name\":null,\"user\":{\"url\":\"http:\\/\\/davert.com\"}}"
```
can be matched with
```php
<?php
$I->seeResponseMatchesJsonType(['id' => 'integer:>10',
'retweeted' => 'Boolean',
'in_reply_to_screen_name' => 'null|string',
'user' => [
'url' => 'String:url'
]
]);
?>
```

Implemented comparison for json structure by types

---

src/Codeception/Module/ZF1.php
src/Codeception/Module/ZF2.php

I had an issue with client carrying over domain from test which uses domain to test which doesn't.

ZF1, ZF2: call parent::_after in _after to cleanup after each test

---

src/Codeception/Lib/InnerBrowser.php
tests/data/app/db
tests/data/app/view/form/complex.php
tests/unit/Codeception/Module/TestsForWeb.php

This should reduce code duplication and allow using `seeInField` and `dontSeeInField` with disabled form fields. Fixes #2378 
@zbateson @Naktibalda please review

Refactored grabValueFrom and seeInFields

---

src/Codeception/Step.php
tests/unit/Codeception/StepTest.php

Although WebDriverBy are acceptable arguments to many of the WebDriver module steps taken by the AcceptanceTester, the arguments are not very human-readable when output during test execution:
* I click "Facebook\WebDriver\WebDriverBy"
* I click "Facebook\WebDriver\WebDriverBy"
This change uses the Locator util to humanize the arguments, making them more readable:
* I click "css selector '.something'"
A unit test (StepTest::testGetArguments()) asserting correctness is also included.

humanize WebDriverBy step arguments

---

CHANGELOG.md
src/Codeception/Module/Laravel5.php

Add wrapper methods for Laravel 5 model factories to the Laravel 5 module:
- `haveModel($model, $attributes = [], $name = 'default', $times = 1)`
- `createModel($model, $attributes = [], $name = 'default', $times = 1)`
- `makeModel($model, $attributes = [], $name = 'default', $times = 1)`
Model factories were introduced in Laravel 5.1, so these methods can only be used if your application uses Laravel 5.1 or later.
For more details on model factories see http://laravel.com/docs/5.1/testing#model-factories.

Add wrapper methods for Laravel 5 model factories

---

src/Codeception/Lib/Driver/PostgreSql.php
tests/data/dumps/postgres.sql
tests/unit/Codeception/Lib/Driver/PostgresTest.php

Currently the search path isn't saved when importing a PostgreSQL dump
which causes problems when trying to fill a database table using `COPY`.
If the search_path isn't reset for the new connection then the import
will try to `COPY` the data into the default schema (usually `public`)
and cause the import to fail with
`pg_query(): Query failed: ERROR:  relation "..." does not exist`
I would consider this a bug fix since my imports are currently failing
without the patch, but it could change some behaviour for badly created
database dumps that always assume the search path for `COPY`s
will be set to the `public` schema. If you'd prefer I could change the
base for the merge to be `master` and not the `2.1` branch.

Save the search path when importing Postgres dumps

---

src/Codeception/Module/Yii2.php

If `$_FILES` is emptied, `\yii\web\UploadedFile::reset()` must be also called. It has a static property `$_files` that keeps previous upload even if `$_FILES` is reset.

Reset leaves previous file uploads in UploadedFile

---

src/Codeception/Lib/InnerBrowser.php
src/Codeception/Lib/Interfaces/Web.php
src/Codeception/Module/WebDriver.php
tests/unit/Codeception/Module/TestsForWeb.php

Checks the raw response rather than the tag stripped/html decoded
result.

seeInSource method for InnerBrowser/WebDriver

---

src/Codeception/Lib/InnerBrowser.php

Before:
`[Cookies] [{},{}]`
After:
`[Cookie Jar] ["a=b; domain=localhost; path=/","c=d; domain=localhost; path=/"]`

[InnerBrowser] Display cookie jar content in verbose output

---

src/Codeception/Module/WebDriver.php
tests/unit/Codeception/Module/WebDriverTest.php

WebDriver provides access to the logs for both the client and server, which are sometimes necessary
to debug test failures. This commit modifies Codeception\Module\WebDriver->_failed() to grab all
available logs and print them in human-readable format. The format is identical to what Selenium
Server uses for displaying logs in the console.

Print Selenium logs on failure

---

src/Codeception/Module/Symfony2.php

@todo Should leave it up to the user to update the php.ini instead of
setting it in code. This overwrote my correct settings.
This ini change caused an error when I used Codeception/Specify library.

Fix a root cause hiding error when Symfony2 is configured wrong

---

src/Codeception/Util/JsonType.php
tests/unit/Codeception/Util/JsonTypeTest.php

BugFix: In \Codeception\Module\REST::seeResponseMatchesJsonType now can be used 'string|null' as well as 'null|string' to specify the type

BugFix: string|null as well as null|string can be used to specify the value type

---

src/Codeception/Command/GenerateSuite.php

Suite generation command always creates bootstrap script named `_bootstrap.php` regardless of user settings. Fortunately it's easy to fix.

Make generate:suite respect bootstrap setting

---

CHANGELOG.md
src/Codeception/Lib/InnerBrowser.php
src/Codeception/Module/REST.php
tests/unit/Codeception/Module/PhpBrowserRestTest.php
tests/unit/Codeception/Module/RestTest.php

Introduced `_getResponseContent` helper method to InnerBrowser.
Used it in all REST response methods to enable tests like this.
```
$I->amOnPage('/rest/user/');
$I->seeResponseCodeIs(200);
$I->seeResponseIsJson();
```
Related ticket #2496

REST methods can be used to inspect responses of other modules

---

CHANGELOG.md
src/Codeception/Lib/Connector/Laravel5.php
src/Codeception/Module/Laravel5.php

Removed the `expectEvents` method and added `seeEventTriggered` and `dontSeeEventTriggered` methods. This is more in line with the other assertions in the module.

Refactoring of events functionality

---

src/Codeception/Module/ZF2.php

* fix issue #2519 where Doctrine2 gets different instance of the
entity manager everytime ZF2's grabServiceFromContainer method
is called

Grab service from the current app and not initialize a new one

---

docs/modules/Silex.md
src/Codeception/Module/Silex.php

It's work for me, but I think code needs some testing.

Silex Doctrine provider

---

src/Codeception/Lib/Connector/ZF2.php

ZF2 connector was setting GET and POST parameters inside ifs(), if these conditions weren't met, request object kept parameters from the previous request.
I changed it to clear parameters instead of keeping old parameters.

ZF2: empty form params and query params if new request does not set them

---

src/Codeception/Lib/Connector/ZF2.php

Ensured that Content in ZendRequest is set to null if there is no content in the current request.
Simplified parameter setting logic.

ZF2: always set raw-body, refactored parameter logic

---

composer.json
composer.lock
tests/unit/Codeception/Command/GeneratePageObjectTest.php

Replacing explode functions with preg_split alternative. 
https://github.com/Codeception/Codeception/issues/2501

Replacing explode functions with preg_split alternative

---

docs/reference/XmlBuilder.md

Semi colon at the end of the line causes XML builder to break.

Typo: Remove semicolon from XMLBuilder block

---

src/Codeception/Module/Symfony2.php

I faced a situation when I needed to load and use some of my Symfony2 project's services in _beforeSuite() to prepare some needed data, obviously, before suit is running. I couldn't do that because current implementation loads kernel and set up container only before a test (in the _beforeTest() method).
I also created an issue about that (according to https://github.com/Codeception/Codeception/wiki/Git-workflow-for-Codeception-contributors) - https://github.com/Codeception/Codeception/issues/2490
Tests passed with my changes.

Move kernel booting and container set up into _initialize() method

---

src/Codeception/Module/Memcache.php

Prevent this from happening : 
[PHPUnit_Framework_Exception]
MemcachePool::close(): No servers added to memcache connection

Memcache module: bug fix "memcache" extension init

---

src/Codeception/Module/Laravel5.php

`seeCurrentRouteIs()` will throw an exception if the routes don't match:
`[ErrorException] Object of class Illuminate\Routing\Route could not be converted to string`
It should use the `$currentRouteName` instead of the route object when creating the error message.

Fix Laravel5 module seeCurrentRouteIs crash

---

CHANGELOG.md
src/Codeception/Lib/Connector/Laravel4.php
src/Codeception/Lib/Connector/Laravel5.php
src/Codeception/Module/Laravel4.php
src/Codeception/Module/Laravel5.php

I refactored the Laravel modules due to the results of the discussion in #2596. Besides implementing the fix mentioned in that issue I also implemented several other improvements to the internals of the modules.
I also removed the `enableMiddleware` and `enableEvents` methods from the Laravel 5 module, because I think it is not necessary to be able to enable the middleware/events again in the same test after disabling them. And the implementation of `enableEvents` will not be simple due to the refactoring in this PR.

Refactor Laravel modules

---

src/Codeception/Module/Symfony2.php

Codeception/Codeception#2435
Codeception/Codeception#2470
Usage example:
```yaml
class_name: AcceptanceTester
modules:
enabled:
- Symfony2:
part: SERVICES
app_path: '../../../app'
var_path: '../../../app'
- Doctrine2:
depends: Symfony2
cleanup: false
- Asserts:
- WebDriver:
url: http://your-url.com
host: '127.0.0.1'
browser: phantomjs
window_size: 1280x800
request_timeout: 30
debug_log_entries: 100
wait: 1
capabilities:
webStorageEnabled: true
handlesAlerts: true
- \FrontendAdminBundle\Helper\Acceptance
```

implements PartedModule in Symfony2 module with services part

---

src/Codeception/Module/Symfony2.php

Router can be cached on Symfony2 framework. This option is disabled by default.
It can be enabled with:
modules:
- Symfony2:
cache_router: true
...
It's also provided a method to force cache invalidation on desire named
'invalidateCachedRouter()', to be used on the rare cases you want router to be
cached but need to manually invalidate cache before of after certain tests.

Symfony2: Cache router

---

src/Codeception/Module/Doctrine2.php

Close Doctrine2 connection after each test to prevent throwing an
exception "[Doctrine\DBAL\Exception\DriverException] An exception occured
in driver: SQLSTATE[08004] [1040] Too many connections" with a large
test suite

Fix issue #2060 - Too many connections error

---

src/Codeception/Lib/Driver/Db.php

Db module should handle "dblib" PDO driver as well. 
I tested it and figured out that populate and cleanup works well (without taking into account the fact that sql dump from mssql should be converted to appropriate fromat first).

Added support of dblib PDO driver

---

src/Codeception/Lib/Parser.php

Tests on file paths with spaces failed as the new Parser::validate() call wasn't escaping file paths.

Fixed Parser::validate to escape file paths

---

autoload.php

If another composer package already define a compat hack, Codeception can't be installed.

Check if Throwable interface already exists

---

src/Codeception/Lib/InnerBrowser.php
src/Codeception/Module/PhpBrowser.php
tests/unit/Codeception/Module/PhpBrowserTest.php

BrowserKit's CookieJar overrides Guzzle's, so I decided to use it instead of passing `cookies` option to Guzzle.
`setCookiesFromOptions` method can be used in framework modules, if there is a wish to add `cookies` option to them.

PhpBrowser: Fixed cookies option by setting cookies to BrowserKit's CookieJar #2653

---

.travis.yml
src/Codeception/Lib/Driver/PostgreSql.php
tests/data/dumps/postgres.sql
tests/unit/Codeception/Lib/Driver/PostgresTest.php

This is a PR to fix #2666. To test, I'm adding one of each kind of pgsql `type` and then individually checking that they exist before and don't exist after `cleanup()`. I'm doing the checks individually because it doesn't make sense to use the same query to check for type existence that I use to determine which types to delete (and that's the only query I have to list custom types).
Note that `range type`s aren't supported in pgsql below 9.2, so this will break the tests on pgsql 9.1 and below.

Postgres driver: cleanup() delete all custom types

---

src/Codeception/Lib/Connector/Laravel5.php

"Normal" events in Laravel return an array of listeners responses. Mocked events should also return an array so that application code does not have to account for the possibility of null being returned instead.

Laravel5: Mocked events shouls also return an array

---

src/Codeception/Module/REST.php

Fix.
if in you use :
```
$I->seeHttpHeader('X-CustomHeader', "X009");
```
In report you will see : 
```
Fail  Failed asserting that X009 matches expected null.
```
But should be :
```
Fail  Failed asserting that null matches expected X009.
```

Fixing Assertation message from null to expected value

---

docs/modules/WebDriver.md
src/Codeception/Module/WebDriver.php
tests/support/_generated/WebGuyActions.php

The old pre2.1 docs showed usage of either `\Facebook\WebDriver\RemoteWebDriver` or just `\WebDriver`, so my custom `switchToPreviousWindow()` method utilized an `executeInSelenium(\WebDriver $webdriver)` call.  Although this worked up to 2.1.0 (with facebook/webdriver up to 0.6.0 underneath), it broke on 2.1.1 (when webdriver jumped to 1.0.0+).  Changing the signature from `\WebDriver` to `\Facebook\WebDriver\RemoteWebDriver` made no difference.
The broken behavior I witnessed was that Chrome would hang on this step, and only a timeout would break it.  On IE, there was no hang... just a `[Facebook\WebDriver\Exception\NoSuchWindowException]`.
I debugged the problem down to `Argument 1 passed to Codeception\Module\AcceptanceHelper::Codeception\Module\{closure}() must be an instance of …

fix the namespace to RemoteWebDriver in the executeInSelenium() references

---

src/Codeception/Module/Laravel5.php

Previously #2706, fixed in the module itself as the .md file is automatically generated.
There's a typo for the `amLoggedAs` function documentation:
```
$I->amLoggesAs( new User );
```
should be:
```
$I->amLoggedAs( new User );
```

Fixed typo in Laravel5.php module

---

src/Codeception/Module/FTP.php

1. Add the argument of _after ()
2. $this->ftp to NULL, after ftp_close.  
If you do not do this, then _closeConnection() for ftp_close is re-executed when is called.
3. Fixed a typo flase to false

fix Bug in FTP Module

---

RoboFile.php
composer.json

PHP5.4 phar will be bundled with Guzzle 5.3 and Symfony 2.8
The main phar file will be bundled with the latest version of Guzzle 6 and Symfony 3.
Solves #2124

Generate separate phar file for PHP 5.4

---

src/Codeception/Module/Symfony2.php

#2664
Unlike seeCurrentRouteIs, this can matches without exact route parameters.
Usage example: 
```php
$I->amOnRoute('posts.create');    # admin/posts/create
$I->fillField(['name' => 'title'],  "Hello World!");
$I->click('Save');
$I->seeCurrentRouteMatches('posts.edit');    # admin/posts/123/edit
```

Add seeCurrentRouteMatches function to the symfony2 module

---

src/Codeception/Module/Sequence.php
src/Codeception/Util/sqs.php
tests/unit/Codeception/Module/SequenceTest.php

This feature is usefull for huge suites with multiple depend steps within.

Add Sequence per suite generation

---

src/Codeception/Module/REST.php

Enables a pair of methods to control automatic redirection following by the REST client, like so:
```php
$I->stopFollowingRedirects();
// ...
$I->startFollowingRedirects();
```

Add ability to control redirect following in the REST module

---

src/Codeception/Step.php
tests/unit/Codeception/StepTest.php

Backporting some changes made in https://github.com/Codeception/Codeception/pull/2777 to 2.1
Don't trim external [ if the first or the argument is array;
Display "Closure" instead of "lambda function"
Eliminated "callable function" - a full content of array (or any other callable) is displayed, 
Objects in array are replaced with class name.

Improved steps output in 2.1 branch

---

src/Codeception/Coverage/Subscriber/LocalServer.php

Sometimes coverage is empty because c3 creates coverage file later, than afterSuite executed.
Related to #1719
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/codeception/codeception/2785)

Empty coverage simple workaround

---

RoboFile.php

http://codeception.com/builds
php54. is displayed above 2.1, this patch fixes that

Don't display php54 as a minor version of Codeception in /builds

---

src/Codeception/Lib/Console/Message.php
src/Codeception/Step.php
src/Codeception/Step/Comment.php
src/Codeception/Step/Meta.php
src/Codeception/Subscriber/Console.php
tests/cli/RunCest.php
tests/unit/Codeception/StepTest.php

Example of effect:
Command: `php codecept run tests/cli/RunCest.php:Failed --steps`
Output:
```
Cli Tests (28) ----------------------------------------------------------------------
Run test with failed scenario RunCest.php
Scenario --
I am in path "tests\/data\/sandbox"
I execute command "run scenario FailedCept --steps --no-exit"
I see in shell output "Fail when file is not found at FailedCept.php\nScenario -..."
I expect to see scenario trace
I see in shell output "Scenario Steps:\n\n 2. $I->seeFileFound(\"games.zip\") at..."
PASSED 
-------------------------------------------------------------------------------------
```

Limit step output length to 1 line

---

src/Codeception/Module/REST.php

Assertion should be negative. Specified xpath shouldn't be in XML structure.

Typo in "dontSeeXmlResponseMatchesXpath"

---

src/Codeception/Actor.php
src/Codeception/Lib/Console/Message.php

Fix utf-8 encoding issue in PHP < 5.6 (mb_* functions default charset)

Fix encoding problems in PHP prior to 5.6 related to #120 and #2810

---

src/Codeception/Util/Uri.php
tests/data/app/controllers.php
tests/data/app/view/form/bug2841.php
tests/unit/Codeception/Module/PhpBrowserTest.php
tests/unit/Codeception/Util/UriTest.php

Fixes #2841 
Don't keep query string if new URI sets a path.
Don't keep anchor if new URI sets a path or a query string.

Reproduced and fixed issue #2841

---

src/Codeception/Lib/Driver/Sqlite.php

I started to have some problems while using sqlite to run tests.
Originally Sqlite constructor did the following:
```php
parent::__construct($dsn, $user, $password);
$this->filename = Configuration::projectDir() . substr($this->dsn, 7);
$this->dsn = 'sqlite:' . $this->filename;
```
The call to parent::__construct creates a connection using the dsn from the parameter, then the filename and dsn are modified prepending the projectDir.
This fails, caused a problem while running my tests because if the connection was successful, then the load failed because the path had been changed, and if I changed the path in the dsn to match the one in load, then the connection failed.
I think it is better to first prepend the projectDir and then call parent, so connection and load use the same path. …

Changed the way sqlite is managing the files

---

src/Codeception/Step.php
tests/unit/Codeception/StepTest.php

Used mb_strlen for measuring total output length and sorting parameters by length in Codeception\Step.
But started by writing a failing test.

Replaced strlen with mb_strlen in Codeception\Step

---

src/Codeception/Module/REST.php

Add default value for $url in Module\REST::execute() accoarding to 
"Note that when using default arguments, any defaults should be on the right side of any non-default arguments; otherwise, things will not work as expected." 
http://php.net/manual/en/functions.arguments.php#functions.arguments.default

REST::execute() small fix in argument defaults

---

src/Codeception/Module/REST.php

Visibility of REST::getRunningClient() changed to 'protected' to allow its using in module extends.
For example:
```php
public function grabHttpHeaders()
{
return $this->getRunningClient()->getInternalResponse()->getHeaders();
}
```
instead of:
`return $this->client->getInternalResponse()->getHeaders();`

REST::getRunningClient() made 'protected'

---

src/Codeception/Module/REST.php

REST::seeResponseMatchesJsonType() doc block fix accoarding to new method name and args.
Also need it in http://codeception.com/docs/modules/REST#seeResponseMatchesJsonType

REST::seeResponseMatchesJsonType() doc block fix

---

src/Codeception/Module/WebDriver.php

The link http://code.google.com/p/selenium/wiki/DesiredCapabilities doesn't exist anymore. I switch to the new one always from SeleniumHQ

Update WebDriver Doc

---

tests/data/rest/index.php
tests/unit/Codeception/Module/PhpBrowserRestTest.php

Closes #1650 
My patch was accepted to symfony/browserkit on 27th of January and released in 3.0.2 version,
2.* branches will be fixed in the next release cycle.

REST: Added test to prove that HTTP_HOST header can be set

---

docs/06-ReusingTestCode.md

The link at (http://codeception.com/docs/06-ReusingTestCode#PageObjects):  
was not anymore valid. I'm updating it with the one that I guess is the right new location.

Update Page Object documentation outdated link

---

src/Codeception/Lib/InnerBrowser.php
src/Codeception/Module/PhpBrowser.php
src/Codeception/Module/REST.php
tests/unit/Codeception/Module/PhpBrowserRestTest.php
tests/unit/Codeception/Module/RestTest.php

Requests from REST module are sent through `_reqest` method of InnerBrowser.
Headers managing also moved from REST to InnerBrowser.
Now InnerBrowser and REST can set and unset headers equally:
* haveHttpHeader - to set (was not available in framework modules)
* deleteHeader - to unset it (was not available in REST + framework modules)

Unified api for setting/delitting headers

---

composer.json
docs/modules/Queue.md
src/Codeception/Lib/Driver/Beanstalk.php
src/Codeception/Module/Queue.php
tests/unit/Codeception/Module/Beanstalkd_Test.php

Updated module Queue to work with pheanstalk library ~3.0; Codeception module Queue (adapter for Beanstalk)

Updated module Queue to work with pheanstalk library ~3.0

---

src/Codeception/Lib/Connector/Guzzle.php

I copied this new functionality from Guzzle6.php to Guzzle.php
#2896

Unset HTTP Auth credentials on Guzzle 5

---

.travis.yml

In dependencies=lowest environment, install the lowest supported versions of dependencies for all framework sites except Symfony.
Install matching version of symfony/symfony for frameworks-symfony when SYMFONY=X variable is set (only 2.7 and 2.8 are supported).
Run dependencies=lowest on PHP 5.5 to test all frameworks (except Symfony).

Test lowest dependencies for frameworks

---

.travis.yml
src/Codeception/Lib/Console/Message.php
tests/unit/Codeception/Lib/Console/MessageTest.php

While using utf-8 text as messages in tests output is not correct in some cases
```php
// example
public function testBlaBla($I)
{
$I->wantTo('бла бла');
}
public function testBlaBlaBla($I)
{
$I->wantTo('бла бла бла');
}
```

Correction for non ascii encoding with mb_ function

---

src/Codeception/Lib/Parser.php

When $config['settings']['lint'] is not initialized codeception throws PHP Notice, fixed it.

Fix non-init config value

---

src/Codeception/Module/SOAP.php

**Test :**
```php
$I->sendRequest('ShowUser', '<user><name>notdavert</name></user>');
$I->grabTextContentFrom("//*[local-name() = 'login']");
$I->sendRequest('ShowUser', '<user><name>eXorus</name></user>');
$I->grabTextContentFrom("//*[local-name() = 'login']");
```
**Actual Result :**
notdavert
notdavert
**Result Expected with my fix**
notdavert
eXorus
The fix consist to always rewrite xmlStructure from xmlResponse and not only when it's null because if you call a second times the xmlStructure will be the xmlStructure of the fist call.
Bug was introduced in 2.1.7

[SOAP] Fix grabTextContentFrom() after the second request

---

CHANGELOG.md
src/Codeception/Module/Symfony2.php

Created for consistency with other frameworks.
Old method `grabServiceFromContainer` has been deprecated and should be removed on future releases.

New method grabService.

---

src/Codeception/Subscriber/BeforeAfterTest.php
tests/cli/OrderCest.php
tests/data/claypit/tests/order/BeforeAfterClassWithDataProviderTest.php

Fix Issue #2934 (setUpBeforeClass not working with @dataProvider).
The method setUpBeforeClass, methods annotated with `@beforeClass`, and the _beforeSuite method did not get called if the test case only contained tests annotated with `@dataProvider`. 
This happened because such test cases were included in PHPUnit_Framework_TestSuite_DataProvider instances, which do not have hooks for setup or teardown 'before class'.
However, if a single test of the test case was not annotated, than the hooks would run, since at least one test did not get converted to PHPUnit_Framework_TestSuite_DataProvider.
I've provided a simple, though inelegant fix, and a test to guard against such bugs.
Kind regards,
Fabian

Fix setupbeforeclass bug issue 2934

---

src/Codeception/Lib/Connector/ZF2.php

While using codeception for testing a ZF2 project, we found out that files attached to a REST call were not received in Zend's action methods. After investigation, we could see that get and post parameters were attached to the Zend request object, but files were not. This fixes this issue.

[FIX] pass the zend request the files

---

CHANGELOG.md
src/Codeception/Lib/Connector/Laravel4.php
src/Codeception/Lib/Connector/Laravel5.php
src/Codeception/Module/Laravel4.php
src/Codeception/Module/Laravel5.php

This fix is similar to the fix of @Namek in #3048, however, it also applies the fix for the Laravel 5 module and adds checks for some other services.

Fix for #3028

---

docs/071-BDD.md

scenarios are described inside Features. The original doc was missing the right indentation

Fix indentation in Scenario

---

.travis.yml
CHANGELOG.md
composer.json
src/Codeception/PHPUnit/Runner.php
src/Codeception/Subscriber/ErrorHandler.php

Build is failing because Symfony-demo has some deprecated code and it need to define SYMFONY_DEPRECATIONS_HELPER='weak' to print deprecations but don't fail.

Added support for PHPUnitBridge

---

src/Codeception/Command/SelfUpdate.php
tests/unit/Codeception/Command/BaseCommandRunner.php
tests/unit/Codeception/Command/SelfUpdateTest.php

This PR fixes the issue when `self-update` updates `2.1.7` to `2.2.0-RC2` instead of `2.1.8`.

Fix self-update command to update only to stable versions

---

src/Codeception/PHPUnit/Runner.php
src/Codeception/Subscriber/Console.php
src/Codeception/SuiteManager.php
tests/cli/RunCest.php

Fix for #3033 
I'm not sure this would be the best solution to the issue, maybe a refactor of the Loader would be better, but this seems more like something that can join easily into 2.2.

Fix the count of tests printed in console when tests are filtered

---

src/Codeception/PHPUnit/Runner.php
src/Codeception/Subscriber/Console.php
src/Codeception/SuiteManager.php
tests/cli/RunCest.php

I cherry-picked this change from master to 2.1
#3034

Fix the count of tests printed in console when tests are filtered (2.1)

---

src/Codeception/Module/Symfony2.php

Now it will properly check route name and route parameters, avoiding query parameters.

[Symfony] Reworked seeCurrentRouteIs

---

src/Codeception/PHPUnit/Constraint/Page.php
tests/unit/Codeception/Module/TestsForWeb.php

InnerBrowser::see matches UTF-8 text case-insensitively

---

src/Codeception/Module/Lumen.php

In Lumen module, initializeLumen() method has been called twice on that starts. (_initialize, _before)
That causes a problem that the IoC container does not store any singleton instances which created via Facade.
Facade::clearResolvedInstance() should be called every before bootApplication().
I guess #2607 is same problem.

Fix container issue in Lumen Module

---

src/Codeception/Module/Db.php

Simple lazy/non-greedy match-all instead of complex non-capturing negative lookahead.
Still matches both single line and multiline comments. Just like it did before.
Matching single-line comments should not be required, but excluding them would make regex more complex.

#3128 Fixed stack overflow too comples regex

---

src/Codeception/Lib/Console/Message.php
src/Codeception/Subscriber/Console.php

When the test case named with double-width characters, test result's format is broken.
after this fix:

Fix format with Double-Width Characters

---

src/Codeception/Codecept.php
src/Codeception/Coverage/Subscriber/Printer.php

PR for #1592 
This should work as-is, although I'm not sure it's the 'right' way of doing it. When `--quiet` is used it also suppresses the progress of the tests, which isn't really what I would find useful, ideally I'd like to see the test progress but just hide the report. That would require a new option (something like `--no-coverage-console` or `--coverage-quiet`) and I wasn't sure if that would be okay so I thought I'd check first.

Suppress console coverage report with `--quiet`

---

docs/reference/Configuration.md
src/Codeception/Configuration.php
src/Codeception/SuiteManager.php

This address issue #3044 
Pass the backup_globals variable, if provided in the .yml file, to the test suite.

Provide method for setting backupGlobals

---

CHANGELOG.md
src/Codeception/Lib/Driver/SqlSrv.php
src/Codeception/Module/ZF1.php

SqlSrv didn't have it because it overrides generateWhereClause method.
Also I deleted misleading comment from ZF1 module.
I made these changes after reviewing  #3142

Added missing support for LIKE condition to SqlSrv driver

---

composer.json

The last version of php-code-coverage introduce the use of namepsace and broke the code coverage generation in codecept
https://github.com/sebastianbergmann/php-code-coverage/blob/4.0.0/src/CodeCoverage.php#L25

Avoid the last version of code coverage

---

composer.json

I has always been required: https://github.com/Codeception/Codeception/blob/2.1.10/src/Codeception/Command/Run.php#L380
I just made it explicit in composer.json

Curl extension is required

---

src/Codeception/Module/Db.php
tests/unit/Codeception/Module/DbTest.php

You might want to compare how many records are in a table before and after some operations. The table might not be empty to begin with.
For example:
```
$count = $I->grabNumRecords( 'book' );
$I->click( 'Save' );
$I->see( 'Field is required' );
$I->seeNumRecords( 'book', $count );
```

Added a grabNumRecords to Db module

---

src/Codeception/Lib/Connector/Phalcon.php

In the Phalcon Micro Application, when you use the middleware in `before`, and it will be return the boolean (true or false) to make the application process pass through or stop.
When I use `return false` to stop the application, the Lib of Phalcon will got the boolean in LINE 115,
```
// Here will got the boolean when middleware `before` return false.
$response = $application->handle();
```
And the Library will be broken. So I add the check and IF NOT `ResponseInterface`, get the response from `$application->response` will be ok.

Check the return value of application->handle()

---

src/Codeception/Module/SOAP.php

Hello,
This PR allow to send different request on different endpoint in the same test case.
Cest file :
```php
class testApiCest
{
public function test(ApiTester $I)
{
$I->switchEndPoint("https://api1.company.com");
$I->sendSoapRequest('UpdateUser', '<user><id>1</id><name>notdavert</name></user>');
$I->switchEndPoint("https://api2.company.com");
$I->sendSoapRequest('UpdateUser', '<user><id>1</id><name>notdavert</name></user>');
}
}
```
Helper file :
```php
public function switchEndPoint ($endpoint)
{
$this->getModule('SOAP')->_reconfigure(['endpoint' => $endpoint]);
}
```
Actual result :
- First UpdateUser on API1
- Second UpdateUser on API1
Expected result :
- First UpdateUser on API1
- Second UpdateUser on API2
With this PR it's working like expected result.
Related to #3182 (PR on …

[Module : SOAP] Implement onReconfigure() 

---

src/Codeception/Lib/Console/Message.php
src/Codeception/Scenario.php
src/Codeception/Subscriber/Console.php

* Created Message::ucfirst for utf-8 texts (it is used only once in 2.1 branch, but it will be used in more places in 2.2).
* Changes strtoupper to mb_strtoupper in Scenario::getText and Scenario::getHtml

UTF-8 improvements

---

src/Codeception/Lib/Di.php

In some cases duplicates were present in the container, for example "Codeception\Modules\Symfony2" and "\Codeception\Modules\Symfony2"

Bugfix with duplicate instances in the container

---

CHANGELOG.md
src/Codeception/Lib/Connector/Laravel5.php
src/Codeception/Module/Laravel5.php

This PR adds methods to the Laravel 5 module that enables users to register bindings to the Laravel service container, for more background see #2904.
The following methods are added to the Laravel 5 module:
```
public function haveBinding($abstract, $concrete);
public function haveSingleton($abstract, $concrete);
public function haveContextualBinding($concrete, $abstract, $implementation);
public function haveInstance($abstract, $instance);
```
I also created tests for this functionality in the Laravel 5 sample application. I will push these tests after merging this PR, because these tests will break the Codeception build if I push them without merging the new functionality.

Laravel5 add methods to register service container bindings

---

src/Codeception/Lib/InnerBrowser.php
src/Codeception/Module/WebDriver.php

Fix for "File name too long" error in failed gherkin tests with too long description

Fix for "File name too long" error in failed tests

---

composer.json
src/Codeception/Lib/Console/Colorizer.php
src/Codeception/Lib/Console/DiffFactory.php
src/Codeception/Lib/Console/MessageFactory.php
src/Codeception/Subscriber/Console.php
tests/unit/Codeception/Lib/Console/ColorizerTest.php
tests/unit/Codeception/Lib/Console/DiffFactoryTest.php
tests/unit/Codeception/Lib/Console/MessageFactoryTest.php

Fixes #3230
The diff used to show both complete strings instead of only the changed lines,
I've added a unit test for the case and refactored a bit inside the Console.php
Todo: Add color output as this got lost during the diff changes.

Diff shows only changed lines

---

src/Codeception/Configuration.php

The documentation [states](http://codeception.com/docs/06-ModulesAndHelpers#Dynamic-Configuration-With-Params) that we can load params from files named `.env` or `.env.something` but the latter doesn't work because the regex only matches filenames ending with `.env` or `.ini`

Fix loading of parameters from `.env.*` files

---

src/Codeception/Module/WebDriver.php
tests/data/app/view/form/select_second.php
tests/web/WebDriverTest.php

Hello,
Module :  WebDriver
Version : 2.2.1
Browser : Firefox
```html
<select id="select1">
<option value="select1_value1">Value1</option>
<option value="select1_value2">Value2</option>
</select>
<select id="select2">
<option value="select2_value1">Value1</option>
</select>
```
```php
$I->selectOption('#select2', 'Value2');
```
**Actual behaviour**
The value "Value2" in field "#select1" is selected
**Expected behaviour**
Failed to select the value "Value2" because it is not in "#select2" field.
**Fix**
I only replace xPath "//option" to ".//option". Like this the findElement will only search in the childs and not everywhere

selectOption - select option from different selector

---

src/Codeception/Lib/InnerBrowser.php
tests/data/app/view/form/field.php
tests/unit/Codeception/Module/TestsForWeb.php

Search input fields in constructions like
```
<label>
<b>Some label</b>
<input name="name">
</label>
```

Search field by label without "for"

---

src/Codeception/Test/Gherkin.php

Replaces #3270
Report looks like this
```xml
<testcase file="/home/davert/Codeception/tests/data/claypit/tests/scenario/File.feature" name="Run gherkin: Check file exists" feature="Check file exists" assertions="4" time="0.009753"/>
<testcase file="/home/davert/Codeception/tests/data/claypit/tests/scenario/FileExamples.feature" name="Suite configs: Check file exists | ., unit.suite.yml" feature="Check file exists | ., unit.suite.yml" assertions="1" time="0.005046"/>
<testcase file="/home/davert/Codeception/tests/data/claypit/tests/scenario/FileExamples.feature" name="Suite configs: Check file exists | ., scenario.suite.yml" feature="Check file exists | ., scenario.suite.yml" assertions="1" time="0.005625"/>
<testcase file="/home/davert/Codeception/tests/data/claypit/tests/scenario/FileExam …
```

Added JUnit report to Gherkin

---

src/Codeception/Command/GherkinSnippets.php
src/Codeception/Lib/Generator/GherkinSnippets.php
tests/cli/GherkinCest.php
tests/data/claypit/tests/scenario/subfolder/SubFile.feature

Implementation of #3119 for creating gherkin snippets for a specific feature. The new command line is similar to the syntax of `run`:
```
codecept gherkin:snippets suite [test]
```
Example:
```
codecept gherkin:snippets acceptance admin.feature
```
As discussed in #3216, the parameter can also be a folder. It will then generate snippets for the .features contained within the folder (the root folder is the test suite folder)
Example:
```
codecept gherkin:snippets acceptance admin
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codeception/codeception/3280)

Optional parameter test for command gherkin:snippets

---

CHANGELOG.md
src/Codeception/Module/Laravel5.php

Codeception 2.2 does not support Laravel 5.0, only Laravel 5.1 and later releases. For more details see #3243.

Add information about minimum supported version of Laravel 5

---

CHANGELOG.md
src/Codeception/Lib/Connector/Laravel5.php
src/Codeception/Module/Laravel5.php

The `disableEvents()` method and the `disable_events` configuration option of the Laravel 5 module did not disable model events, for more details see #2897.

Laravel5 add functionality to disable model events

---

src/Codeception/Module/Yii2.php

Accessing $rule->host fails because \yii\rest\UrlRule not have "host" attribute.

Fix checking "host" attribute in Yii2 Module / getInternalDomains()

---

src/Codeception/Module/DataFactory.php

Fixes this issue  https://github.com/Codeception/Codeception/issues/3302

Data factory - fix loading factories twice

---

docs/06-ReusingTestCode.md

cloned from https://github.com/Codeception/codeception.github.com/pull/108
doc here is incorrect:
http://codeception.com/docs/06-ReusingTestCode#Session-Snapshot
at least for current stable version (2.2.2)
[RuntimeException] Call to undefined method AcceptanceTester::loadSessionSnapshot
confirmed by [StackOverFlow post](http://stackoverflow.com/q/33273378/2314626)

[doc] PhpBrowser doesn't support session

---

src/Codeception/Module/Db.php

This adds support for all common end-of-line sequences.
Effectively it fixes problems with COPY command in SQL dump on Windows.
Splitting only by LF caused problems on Windows when SQL dump contained Windows line endings.
For example, `PostgreSql` driver expects lines to not contain any of end-of-line characters here: https://github.com/Codeception/Codeception/blob/2.2/src/Codeception/Lib/Driver/PostgreSql.php#L90
If a line ends with CR+LF then the `$sql` argument contains a string ending with CR and therefore it does never call `pg_end_copy` and `pg_close`.

Support different line endings in dump

---

src/Codeception/Lib/Connector/ZF2.php

Update the `doRequest()` method in the ZF2 module's connector to grab the application's response _after_ the application has run. 
Before this fix, the `doRequest()` method grabbed the response _before_ the application was run. This resulted in an empty response when other ZF libraries like Api Agility replaced the application's response object with their own.
Fixes issue #2936.

Update ZF2 module

---

src/Codeception/Lib/GroupManager.php
src/Codeception/SuiteManager.php
src/Codeception/Test/Loader/Cest.php

Fix #3278 
acceptance/welcomeCest.php :
```php
class welcomeCest
{
public function testCase1(AcceptanceTester $I)
{
$I->amOnUrl('https://www.google.fr');
}
/**
* @group grouptc2
*/
public function testCase2(AcceptanceTester $I)
{
$I->amOnUrl('https://www.google.fr');
}
/**
* @group grouptc3
* @example (url="https://www.google.fr")
* @example (url="https://www.bing.com")
* @example (url="https://duckduckgo.com")
*/
public function testCase3(AcceptanceTester $I, $scenario, \Codeception\Example $example)
{
$I->amOnUrl($example['url']);
}
/**
* @example (url="https://www.google.fr")
* @example (url="https://www.bing.com")
* @example (url="https://duckduckgo.com")
*/
public function testCase4(AcceptanceTester $I, $scenario, \Codeception\Example $example)
{
$I->amOnUrl($example['url']);
}
}
``` …

Group Files not working with @example

---

docs/05-UnitTests.md

Also, using `Exception::class` is generic enough for any sort of Exception implementation, and lighter than actually instantiating an exception just to get its class.

Using valid example of expectException()

---

src/Codeception/Lib/Parser.php

Fixes #3324 
I haven't tested this change - I made it using GitHub editor.

Don't fail test validation when exec function is disabled

---

src/Codeception/Lib/Interfaces/RequiresPackage.php
src/Codeception/Module.php
src/Codeception/Module/AMQP.php
src/Codeception/Module/DataFactory.php
src/Codeception/Module/Facebook.php
src/Codeception/Module/MongoDb.php
src/Codeception/Module/PhpBrowser.php
src/Codeception/Module/Redis.php
src/Codeception/Module/WebDriver.php
src/Codeception/Subscriber/Console.php
tests/unit/Codeception/ModuleTest.php

Each module implementing `RequiresPackage` can now specify its external dependencies by implementing `_requires` method. If required class can't be found and exception is thrown with proposal to add corresponding package to composer.json.
For instance, PHPBrowser module has its requirements specified
```php
public function _requires()
{
return ['GuzzleHttp\Client' => '"guzzlehttp/guzzle": ">=4.1.4 <7.0"'];
}
```
If `codeception/base` is installed you will get the the exception which suggests to install '"guzzlehttp/guzzle": ">=4.1.4 <7.0"'

Specify package requirements for module

---

.travis.yml
src/Codeception/Lib/Driver/Sqlite.php
tests/unit/Codeception/Lib/Driver/PostgresTest.php
tests/unit/Codeception/Lib/Driver/SqliteTest.php
tests/unit/Codeception/Module/MongoDbTest.php

A bunch of small improvements:
[PostgresTest] Print the reason why connection failed
[MongoDbTest] mark test as skipped if connection failed
[TravisCI] Don't install mongodb extension on hhvm, because pecl is not available
[Sqlite] Throw exception if in-memory database is used #3319

Database test improvements

---

src/Codeception/Lib/InnerBrowser.php

This PR fix #3374.
The Problem is described in the issue in detail. Basically the `REQUEST_TIME` and `REQUEST_TIME_FLOAT` headers are missing, when use the phalcon modul.
When run functional tests with coverage PHPUnit throws a exception `vendor/phpunit/php-code-coverage/src/Report/Text.php` line 132.

fix #3374 missing REQUEST_TIME server variables

---

src/Codeception/Lib/Connector/Yii2.php

[Yii2] Fixed `@webroot` directory creation

---

src/Codeception/Lib/Console/MessageFactory.php
src/Codeception/Module/REST.php
src/Codeception/Subscriber/Console.php
tests/unit/Codeception/Module/RestTest.php

This change makes behaviour of this method on PHP5 consistent with PHP7
Closes #3400

[REST] seeResponseIsJson must fail when response is empty

---

src/Codeception/Module/SOAP.php

Hello,
I'm having trouble with Tomcat API (CXF Framework) that doesn't accept SOAPAction in HTTP Header because SOAPAction is deprecated from SOAP 1.2.
It will also fix #2201 maybe
So actual user will continue without config SOAPAction and the SOAPAction header will be send with the action value
Other people like me that want to do SOAP 1.2 will put '' in SOAPAction config.

[SOAP] Add flexibility with the config SOAPAction

---

src/Codeception/Module/DataFactory.php

Correct the order of the FactoryMuffin::seed call which is `$times, $name, ...` instead of `$name, $times, ...`.
1. [DataFactory::haveMultiple call](https://github.com/Codeception/Codeception/blob/2.2/src/Codeception/Module/DataFactory.php#L254)
2. [FactoryMuffin::seed function](https://github.com/thephpleague/factory-muffin/tree/v3.0.1/src/FactoryMuffin.php#L82)

Fix DataFactory::haveMultiple argument order

---

src/Codeception/Module/SOAP.php

Hello,
When I'm using seeSoapResponseEquals or dontSeeSoapResponseEquals the print of actual and expected result will be inversed.
https://phpunit.de/manual/current/en/appendixes.assertions.html#appendixes.assertions.assertEquals
seeSoapResponseEquals("expected")
Result before fix
```
Test  tests/api/soap.php:test1
Step  See Soap Response Equals
Fail  Failed asserting that two strings are equal.
- Expected | + Actual
@@ @@
-'actual'
+'expected'
```
Result after fix
```
Test  tests/api/soap.php:test1
Step  See Soap Response Equals
Fail  Failed asserting that two strings are equal.
- Expected | + Actual
@@ @@
-'expected'
+'actual'
```

[SOAP] Actual and Expected inversed

---

src/Codeception/Util/XmlStructure.php

Hello,
$this->grabTextContentFrom("//*[local-name() = 'login']");
If [login] doesn't exist in the SOAP response you will have:
```
There was 1 error:
---------
1) soapCest: test
Test  tests/api/soapCest.php:test
[PHPUnit_Framework_Exception] Trying to get property of non-object
```
We don't know the name of property not found ... that's bad.
After the fix you will have:
```
There was 1 failure:
---------
1) soapCest: test
Test  tests/api/soapCest.php:test
Step  Grab Text Content From
Fail   element with '//*[local-name() = 'login']' was not found.
```
It's better I think.
The fix was just because query return always a DOMNodeList but empty.
http://php.net/manual/en/domxpath.query.php

[SOAP] improve error of grabTextContentFrom when xpath not found

---

CHANGELOG.md
src/Codeception/Lib/Connector/Laravel5.php
src/Codeception/Lib/Connector/Laravel5/ExceptionHandlerDecorator.php

Issue reported by @bonsi in #3420. He also provided this fix in #3421, but I created this PR because I wanted to change the order of the methods in the `ExceptionHandlerDecorator` class.

Laravel5 fix issue with error handler for Laravel 5.3

---

src/Codeception/PHPUnit/Overrides/Filter.php

Remove typehint to be consistent with PHPUnit.
PHPUnit’s [`PHPUnit_Framework_Constraint_Exception->failureDescription()`](https://github.com/sebastianbergmann/phpunit/blob/5.5.2/src/Framework/Constraint/Exception.php#L57) will pass on an object of type `Exception` or `Throwable` to `PHPUnit_Util_Filter`. Codeception is [currently](https://github.com/Codeception/Codeception/blob/2.2/src/Codeception/PHPUnit/Overrides/Filter.php#L13) only accepting objects of type `Exception`.
This will make the Codeception code fail with any `Throwable` you throw at it.
This was changed in PHPUnit 5.0.9, see sebastianbergmann/phpunit@4faa59897ba626bdc0c57c25207e7cbdf9678d9e

Remove Exception typehint

---

src/Codeception/Module/Doctrine2.php

Use \Doctrine\ORM\EntityManagerInterface instead of
\Doctrine\ORM\EntityManager to check for valid entity manager in
Doctrine2 module.

Use Doctrine\ORM\EntityManagerInterface to check for valid em instance

---

tests/unit/Codeception/Module/RedisTest.php

Because I don't like these tests failing when I run a unit suite.

Mark Redis tests as skipped if Redis server is not accessible

---

src/Codeception/Subscriber/ErrorHandler.php
tests/unit/Codeception/Subscriber/ErrorHandlerTest.php

Handle deprecation messages according to error_level setting

---

src/Codeception/Module/Asserts.php
src/Codeception/Util/Shared/Asserts.php

I created a helper and extended \Codeception\Module\REST. When using
`$I->assertInternalType`
I recognized that the default message in Util/Shared/Asserts.php was missing. I found the same problem in some Asserts in Util/Asserts.php
This pull request adds this default messages and also corrects some default values for the messages which were set to null. I you look into PhpUnit itself the default message is ALWAYS an empty string.

Fixed problems with default messages of asserts

---

src/Codeception/Subscriber/Console.php

Related to #3424
Before:
```
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
DEPRECATION: Usage of Zend\ServiceManager\ServiceManager::getServiceLocator is deprecated since v3.0.0; please use the container passed to the factory instead /home/.../codeception-zf2-tests/vendor/zendframework/zend-servicemanager/src/ServiceManager.php:164
DEPRECATION: Usage of Zend\ServiceManager\ServiceManager::getServiceLocator is deprecated since v3.0.0; please use the container passed to the factory instead /home/.../codeception-zf2-tests/vendor/zendframework/zend-servicemanager/src/ServiceManager.php:164
DEPRECATION: Usage of …
```

Display only distinct deprecation messages

---

src/Codeception/Lib/Connector/Laravel5.php

With the latest patch to this file, I accidentally removed support the files array being able to contain nested arrays of files. This fixes that blooper.

Fix support for nested arrays in the file array

---

src/Codeception/Lib/Driver/MongoDb.php
src/Codeception/Module/MongoDb.php

I was unable to load my tar.gz mongo dump and I found that there were some things missing from the files that would allow me to load my dumps. For example not using the `validateDump()` function even though it's there and the mongorestore syntax not including what database to restore to. 
While I was at it, I added the ability to `--quiet` the restore or else if you are using `cleanup` and `populate` options you will be getting the load message every time.

Fixes mongorestore command syntax and adds --quiet option to config

---

.travis.yml
CHANGELOG.md
src/Codeception/Lib/Connector/Laravel5.php
src/Codeception/Module/Laravel5.php

This should fix #3483.
My first attempt to fix this issue was to test if a method `logout` existed on the guard object, but this does not work because the method will sometimes be called via magic methods.
After that I decided to just remove the call altogether, because I could not think of a good reason why the calls were there in the first place. Probably some leftover code from an earlier version of the module. I also deleted two other method calls for the same reasons.

Remove methods from Laravel5 module _after hook

---

docs/modules/WebDriver.md

Hello,
According to the documentation 
```php
$I->amOnUrl('http://localhost/user/42/');
$link = $I->grabFromCurrentUrl();
$user_id = $I->grabFromCurrentUrl('~$/user/(\d+)/~');
```
Result will be:
link = /user/42/
user_id = 42
That's not true, result will be:
Step  Grab from current url "~$/user/(\d+)/~"
Fail  Couldn't match ~$/user/(\d+)/~ in /user/42/
So I fixed the doc with a new regex '~/user/(\d+)/~'

Update WebDriver Doc - Wrong Regex

---

src/Codeception/Module/REST.php
src/Codeception/PHPUnit/Constraint/JsonType.php
tests/unit/Codeception/Module/RestTest.php

[REST] Improved output of failed JsonType assertions

---

docs/06-ReusingTestCode.md

In all other places this example is using "Admin" class, so "Member" should be changed.

[DOC] Fix custom step class name (member => admin)

---

src/Codeception/Module/WebDriver.php

Minor, but my IDE complains that its expecting some random type `Can`, because a description was written on a doc, without a type. This adds the expected string or array.

expected type for $param set for pressKey webdriver action.

---

src/Codeception/Module/Symfony.php

[Symfony] Persist doctrine.dbal.backend_connection if Doctrine2 module is used

---

src/Codeception/Lib/Console/Colorizer.php
src/Codeception/Lib/Console/Output.php
src/Codeception/Subscriber/Console.php

I found `Symfony\Component\Console\Formatter\OutputFormatter::escape` and added it to all relevant places that I could find:
* codecept_debug
* diff output
* assertion messages and stack traces
* step parameters
Fixes #3495

Escape tags in debug output

---

docs/02-GettingStarted.md
src/Codeception/Command/Run.php

Bugfix for #3481 
Changes are low risk in that the current majority case behavior remains the same; for test names of the format dir/ClassName:testName, nothing has changed. However, this change allows the use of additional ':' characters, which can be used to more accurately filter tests by name.
This change should also cover enhancement #2736

bugfix issue 3481: fix pattern matching in run test by name

---

src/Codeception/Lib/Driver/PostgreSql.php
tests/data/dumps/postgres.sql
tests/unit/Codeception/Lib/Driver/PostgresTest.php

This fixed a problem when your sequences are not a standard format (ie. table_id_seq).

fix for then your pSQL sequences are not standard format

---

src/Codeception/Lib/ModuleContainer.php
tests/unit/Codeception/ApplicationTest.php

Bugfix for #3513 -- misspellings in doc and namespace.
Neither was referenced anywhere else, so changes are non-breaking.
Asserted that unit test passed after changes via `codecept run tests/unit/Codeception/ApplicationTest.php`

bugfix 3513: fix codception misspellings

---

src/Codeception/Module/ZF2.php

Configuration:
```
class_name: AcceptanceTester
modules:
enabled: [PhpBrowserHelper, \Helper\Acceptance, Asserts, Doctrine2, DbHelper, RestHelper]
config:
PhpBrowserHelper:
url: 'http://localhost/'
Doctrine2:
depends: ZF2
```
Error:
```
Call to a member function grabServiceFromContainer() on a non-object in 
/var/www/localhost/vendor/codeception/codeception/src/Codeception/Module/ZF2.php:157
```

Using Doctrine2 module with ZF2 as partly loaded results into an error

---

src/Codeception/SuiteManager.php

Fix issue #3472

---

src/Codeception/Coverage/Filter.php

This fixes an edge-case bug with regular filepaths (not asterixed wildcards). 
And here is the related issue describing the bug in more detail: https://github.com/Codeception/Codeception/issues/3519

Fix bug in Coverage Filter related to relative filepaths

---

src/Codeception/Module/REST.php

If the REST module is used with the Laravel5 module and the REST module is configured after the Laravel5 module in the suite configuration file, this method will overwrite the server variables set by the Laravel5 module, in this case HTTP_HOST.
My guess is that this method call should have been removed when the `DependsOnModule` functionality for the REST module was implemented, however, I am not really familiar with the REST module, so please review this change before merging.
The issue fixed with this PR is the root cause for the problem in #3263.

Fix issue with REST module resetting server parameters

---

src/Codeception/Module/SOAP.php
tests/unit/Codeception/Module/SoapTest.php

Fix #3512
**User of Codeception  <= v2.2.3**
No conflict between SOAP and REST
it will take seeResponseCodeIs of SOAP or seeResponseCodeIs of REST depends on the order of modules in yml
**User of Codeception v2.2.4**
Conflict between SOAP and REST
SOAP and REST can't be together so nobody are using both.
**User of Codeception > v2.2.4**
No conflict between SOAP and REST
it will take seeResponseCodeIs of SOAP or seeResponseCodeIs of REST depends on the order of modules in yml
seeSoapResponseCodeIs will always be the response of SOAP.
Tips : Put the REST module after the SOAP module to be sure to have:
seeResponseCodeIs => REST
seeSoapResponseCodeIs => SOAP
Related to  #3104

No more conflict between SOAP and REST

---

autoload.php
src/Codeception/Configuration.php
tests/unit/Codeception/ConfigurationTest.php

This is a fix to the issue I brought up in #3433 . 
While the code is a bit rough around the edges, it appears to conform to project guidelines, and resolves the issue. Any suggestions to make the code more elegant are welcome.

Fixed bad base path edge case

---

src/Codeception/Module/WebDriver.php
tests/data/app/view/info.php
tests/unit/Codeception/Module/TestsForWeb.php

New message matches message thrown by InnerBrowser and looks like this:
```php
$I->click('Link 2');
```
> 'Link 2' is invalid CSS and XPath selector and Link or Button element with 'name=Link 2' was not found.
Fixes #3528

[WebDriver] Improved exception message thrown when click('name') does not match any element

---

src/Codeception/Module/Yii2.php

I think it solves a problem discussed in #3520
MySQL does not supports ALTER TABLE within transactions. But the ActiveFixture model clears all data in table including a sequence before test.
If use cleanup option each unit test with nested transactions throws PDOException.

fixes #3520 nested transactions in yii2 module

---

src/Codeception/Module/Yii1.php

Yii1 configuration allows to change `urlManager` class to subclass of `CUrlManager`,
like this:
```php
[
'components' => [
'urlManager' => ['class' => 'application.components.extendedUrlManager']
]
]
```
When `Yii::app()->urlManager` returns subclass of `CUrlManger`,
`ReflectionException` will raise in `ReflectionHelper::readPrivateProperty` without third argument.

Fix private property accessible

---

src/Codeception/Module/Yii2.php

This code
``` php
// inside Cest file or Codeception\TestCase\Unit
public function _fixtures()
{
return ['posts' => PostsFixture::className()]
}
```
threw exception: "call_user_func() expects parameter 1 to be a valid callback, no array or string given"
and I fixed it up

Corrected call_user_func arguments in Yii2

---

src/Codeception/Module/WebDriver.php
tests/data/app/view/form/strict_selectors.php
tests/web/WebDriverTest.php

Hi
We've been updating some acceptance tests to use the `submitForm` method, but have hit an issue where some of our buttons don't have a `name` attribute so `submitForm` can't find them. We've been getting around this by adding names to the buttons that were missing them, but it would be nice to be able to find the button through different means so that we don't have to change our code just to write a test.
This PR adds support for strict selectors (e.g. `['id' => 'foo']`) and instances of `WebDriverBy` to be passed to `WebDriver::submitForm` as the `$button` parameter, so that the buttons can be found by more methods than just `name`.
For example, with the following HTML:
``` html
<input type="submit" id="submit" name="submitButton" value="Submit" />
```
`$button` could be any one of …

Add support for different selectors in WebDriver::submitForm

---

CHANGELOG.md
src/Codeception/Module/Laravel5.php
src/Codeception/Module/Lumen.php

The docblocks for the `have` and `haveMultiple` methods of the Laravel5 and Lumen modules were not formatted correctly. Because of this the annotations could not be read, which led to these methods not being available when only using the ORM part of the modules.

Fix docblocks for have and haveMultiple methods

---

readme.md

I got this via Mail...
> We saw your image on Docker Hub at codeception/codeception, and we thought you might like this badge for your Docker Hub page showing the image contents. 
>
> The badge that shows the number of layers and download size of your Docker image, and links to our site where you can see the contents of each layer. You can find out more about this - and why it's helpful - in this article. 
>
> If you’d like to use our badge here’s the markdown - you can simply paste this into the full description for codeception/codeception on Docker Hub.
Additional Link: https://medium.com/microscaling-systems/be-docker-image-conscious-deef8008fdce#.d5jh51wfw
Just close this PR, if you're not interested...

added Docker image layer badge

---

src/Codeception/Scenario.php

PHP Fatal error:  Call to a member function addFailure() on null in ...\Codeception\Scenario.php on line 72
Fatal error: Call to a member function addFailure() on null in ...\Codeception\Scenario.php on line 72
FATAL ERROR. TESTS NOT FINISHED.
Call to a member function addFailure() on null
in ...\Codeception\Scenario.php:72
Reproduce:
1. Run console: codecept console acceptance
2. Run in console: amOnPage('/');
3. Run in console: canSeeElement('#xxx');
... and the error should occurred.

FIX can failed in console:

---

src/Codeception/Module/Yii2.php

close db connections when running haveFixtures Yii2: pull to v2.2

---

src/Codeception/Example.php

Differentiate between missing keys and those with NULL values.

better Example::offsetExists() behavior

---

src/Codeception/Module/AngularJS.php
src/Codeception/Module/WebDriver.php
src/Codeception/Test/Test.php

Some additional improvements to #3534 
* Changed how errors are added for in test.before listeners
* Fixed AngularJS + WebDriver compatibility
* Selenium connection failure message is single line now

Improved message for connection failures in WebDriver

---

src/Codeception/Lib/InnerBrowser.php
src/Codeception/Module/WebDriver.php
src/Codeception/PHPUnit/ResultPrinter/HTML.php
src/Codeception/PHPUnit/ResultPrinter/template/scenario.html.dist
src/Codeception/PHPUnit/ResultPrinter/template/scenarios.html.dist
src/Codeception/PHPUnit/ResultPrinter/template/step.html.dist
src/Codeception/Test/Metadata.php

* added `reports` section to MetaData in tests
* WebDriver to store html and png reports to metadata
* improved styling of HTML report

HTML report to include screenshots of failures from WebDriver

---

src/Codeception/Module/Symfony.php

Fixes #3608 - [PHPUnit_Framework_Exception] implode(): Invalid argumnts passed

Fix "[PHPUnit_Framework_Exception] implode(): Invalid argumnts passed"

---

src/Codeception/Subscriber/Console.php

Hello
I run codeception on Windows
I noticed that on Windows the debug may cause a print error when large method names are used in test suites.
In the code the default width used in method detectWidth is set to 60
As the terminal width is not detected on Windows, this width remains set to 60
This causes the maxLength of the message displayed in debug to be limited to 60 characters
As soon as your method name goes above a certain size the message length grows and may go over 60
And you may have an error occuring in the Step class in method getArgumentsAsString provoked by a division by zero on line 117
I dont know if there is a way to capture the cli width on Windows with PHP. I am not sure of that.
But giving a few more characters to the defaut width value on Windows allowed me to run all …

Detect cmd/console width on Windows

---

docs/05-UnitTests.md

it's a bit redundant but I think it might be useful for those jumping straight to the unit tests page.

Added commands to run the unit tests

---

src/Codeception/Command/Run.php

Fixes #3614
This is a correct way to handle `--`
But it is potentially breaking, because commands like `codecept run --coverage-html -- unit --steps` will no longer work.
The correct way to write that one is `codecept run --coverage-html --steps -- unit`

-- separates options from arguments in codecept run

---

src/Codeception/Module/Laravel5.php

Hello again,
I've made a more simple way for seeding the database.
So now you can set these parameters in the config file :
```yml
class_name: FunctionalTester
modules:
enabled:
- Laravel5:
run_database_migrations: true      # not required to run seeding
run_database_seeder: true          # required to use this feature
database_seeder_class:             # not required ( must be an array )
- UserTableSeeder
- AnotherTableSeeder
```
If you didn't specify any seeder, the default `DatabaseSeeder` will be used.
Seeders are runned in the order of the array.
@janhenkgerritsen what do you think ?

Seeder improvement in Laravel5 Module (#3552)

---

src/Codeception/Lib/Di.php

Fix #3392 
Caused by https://github.com/Codeception/Codeception/commit/27d9994262b9649c1c1173070413dad031ccd5f6 . Namespace normalizing was added into instantiate method, but missed in getter.

fix 3392: normalize namespace in DI getter

---

src/Codeception/Module/MongoDb.php

There were an issue with MongoDb Module. Variable `$enitiy` were undefined. I suppose that author meant `$entry` and just made a typo there. It doesn't affect anything except data import using `mongotype` dump type.

Undefined variable  change to the correct  in MongoDb Module

---

src/Codeception/Lib/Driver/MongoDb.php

If someone are using MongoDb with PHP7 or HHVM, he forced to use mongofill package(https://github.com/mongofill/mongofill). Mongofill has class MongoClient in the root namespace but it does't means that it's using legacy `mongo` driver instead of current `mongodb`. In order to make it work with Codeception MongoDB module I changed the way you check if user uses legacy driver by adding additional condition. So if there is `\MongoClient` class and there is no `mongofill` substring in its version -> use legacy mode. Normal mode otherwise.
Before fixing that cleaning of the database didn't work and I've got errors on duplicate keys every test which were using db.

Mongofill support

---

src/Codeception/Subscriber/ErrorHandler.php

Call `registerDeprecationErrorHandler` method and `register_shutdown_function` on first SuiteEvent only.
Fixes #3571.

ErrorHandler fix

---

src/Codeception/Lib/Interfaces/Web.php
tests/data/claypit/tests/_support/_generated/OtherGuyActions.php
tests/support/_generated/AngularGuyActions.php
tests/support/_generated/WebGuyActions.php

This fixes an incredibly small typo in a couple of the PHPDoc blocks which have a plus sign instead of an asterisk.

Fix a minor typo with PHPDoc generation

---

src/Codeception/Module/Yii2.php

Now in Codeception Yii2 Module Documentation at http://codeception.com/docs/modules/Yii2 on Fixture section now placed code example:
```php
<?php
// inside Cest file or Codeception\TestCase\Unit
public function _fixtures()
{
return ['posts' => PostsFixture::className()]
}
```
For Cest file it does not work before this commit
Fixes #3612

Fix for issue #3612

---

src/Codeception/Scenario.php

Hi!
We use groups also to indicate that a test should, for instance, not being executed on firefox. So we do a:
`* @group non_firefox`
It would be great to have a getter for groups in the Scenario class.
Having that, we can do things like:
`        $groups = $scenario->getGroups();
`
`       if (in_array('non_firefox', $groups) and $scenario->current('browser') == 'firefox') {
$scenario->skip();
}`
Thanks for this great tool!
Lars

Allow to get groups from scenario

---

src/Codeception/Lib/Driver/Sqlite.php
tests/data/dumps/sqlite-54.sql
tests/data/dumps/sqlite.sql
tests/unit/Codeception/Lib/Driver/SqliteTest.php
tests/unit/Codeception/Module/DbTest.php

Fixes #3680 
`removeInserted` didn't work for sqlite, because I didn't know that lastInsertId returns ROWID if sqlite table has it (default behaviour).

[Sqlite] Use _ROWID_ to remove inserted rows after test

---

RoboFile.php
docs/modules/AngularJS.md
docs/modules/Apc.md
docs/modules/Db.md
docs/modules/Laravel5.md
docs/modules/Lumen.md
docs/modules/Memcache.md
docs/modules/MongoDb.md
docs/modules/Phalcon.md
docs/modules/SOAP.md
docs/modules/WebDriver.md
docs/modules/Yii2.md
docs/modules/ZF2.md
docs/reference/Autoload.md
docs/reference/Commands.md
docs/reference/Fixtures.md
docs/reference/HttpCode.md
docs/reference/JsonType.md
docs/reference/Locator.md
docs/reference/Module.md
docs/reference/Stub.md
docs/reference/XmlBuilder.md
src/Codeception/Module.php

I think it is time to add reference of public API classes. 
I started with `Codeception\Module` and created `build:docs-api` robo command to generate docs from it.
Most importantly I updated documentation generators to print Util classes and API classes nicely.
Regenerated all docs with recent updates.

Classes Reference

---

CHANGELOG.md
src/Codeception/Lib/Connector/Yii2/Logger.php

[Yii2] Fixed unintentional DB connection drop during exception logging

---

src/Codeception/PHPUnit/ResultPrinter/HTML.php

Using relative paths for HTML snapshot and screenshots in order to make them accessible on remote systems (CI). Fixes #3702

HTML report fix

---

CHANGELOG.md
src/Codeception/Lib/InnerBrowser.php
src/Codeception/Module/Yii2.php

For expample I can't use now:
```php
$I->sendAjaxPostRequest( [/*...*/], $dataPost); 
```
This fix allow to do this

Added procesing for native url formats of Yii2

---

docs/07-AdvancedUsage.md
src/Codeception/Test/Loader/Cest.php
tests/cli/RunCest.php
tests/data/claypit/tests/scenario/DataProviderCest.php

Core implementation of the `@dataprovider` annotation based on the extension **[codeception-dataprovider](https://github.com/edno/codeception-dataprovider/issues/2)**.
This implementation includes changes proposed in PR #3730.
```php
/**
* @dataprovider fileSource
*/
public function filesExists(AcceptanceTester $I, Codeception\Example $example)
{
$I->amInPath($example['path']);
$I->seeFileFound($example['file']);
}
/**
* @return array
*/
protected function fileSource()
{
return[
['path' => ".", 'file' => "scenario.suite.yml"],
['path' => ".",  'file' => "dummy.suite.yml"],
['path' => ".",  'file' => "unit.suite.yml"]
];
}
```
Unlikely the extenstion, the core implemention supports the mix of **@dataprovider** and **@example** annotations for a test.
```php
/**
* @dataprovider fileSource
* …
```

Add dataprovider annotation

---

src/Codeception/Lib/ModuleContainer.php
tests/support/UniversalFramework.php
tests/unit/Codeception/Lib/ModuleContainerTest.php

When you set in your $includeInheritedActions = false, then no actions are included at all.
This PR fixes that

Fixed action inclusion when includeInheritedActions is set to false

---

src/Codeception/Lib/Connector/Yii2.php

`mockAssetManager` prevents setting from test.config file.
https://github.com/yiisoft/yii2-app-advanced/pull/219
https://github.com/yiisoft/yii2-app-basic/pull/95
Now code from PR's doesn't work.
P.S. mock was introduced in [here](https://github.com/Codeception/Codeception/pull/3343/commits/6add1042ef297110c63adbb4281cada4e129b119)

Yii2: remove mockAssetManager

---

src/Codeception/Module/Laravel5.php

Hi,
I've added this option to cover the case when I want to test Laravel package separately. To do that, I'm using `orchestra/testbench` to bootstrap simple Laravel app. In my example, I want to use my package vendor dir instead `orchestra/testbench/fixture/vendor`.
By the way, why package name is set to `codeception/base` instead `codeception/codeception` in `composer.json`? I had some problems with installing my forked version to test if everything works as expected :)

[Laravel5] Added vendor_dir option

---

.travis.yml
src/Codeception/Lib/Driver/PostgreSql.php
tests/data/dumps/postgres-hhvm.sql
tests/unit/C3Test.php
tests/unit/Codeception/Lib/Driver/PostgresTest.php

By default Travis runs tests using HHVM 3.6, Codeception tests will never pass on it.
So I configured Travis to run tests on the latest version of HHVM (3.15.3 currently)
and fixed a few issues that I encountered on my way.
Fixes #3800

[Travis] test Codeception with the latest version of HHVM

---

src/Codeception/Step/Comment.php

Method Codeception\Step\Comment::__toString() must return a string
Fixes #3296

Codeception\Step\Comment::__toString() must return a string

---

src/Codeception/Module/Laravel5.php

This is equivalent to seeNumRecords in DB module

Added seeNumRecords to Laravel5 module

---

src/Codeception/Lib/Driver/Oci.php

(more targeted fix, in lieu of PR #3838)

expect resultset to have uppercase index

---

src/Codeception/Subscriber/Console.php

an additional improvement might be paring the output of `stty -a`

try to get terminal width from ENV variable (bash), fixes #3788

---

src/Codeception/Module/Yii2.php

I this exception while WebDriver and Yii2 enabled, but WebDriver not connected since I forgot to start it.
```
[Symfony\Component\Debug\Exception\FatalThrowableError]  
Call to a member function resetPersistentVars() on null 
Exception trace:
() at /home/[...]/vendor/codeception/codeception/src/Codeception/Module/Yii2.php:221
Codeception\Module\Yii2->_after() at /home/[...]/vendor/codeception/codeception/src/Codeception/Subscriber/Module.php:68
```
acceptance.suite.yml:
```
class_name: AcceptanceTester
modules:
enabled:
- WebDriver:
url: http://localhost/app/web
browser: chrome
restart: false
window_size: 1360x768
- Yii2:
part: init
```

Fix exception WebDriver not connected and Yii2 enabled

---

src/Codeception/Lib/Connector/Yii2.php

When an action is interrupted by an unexpected exception without closing the create transactions, a new application without closing the transactions is created. Some tables are locked and the test-run is stuck. This is the solution to this problem, just close the open transaction.

close transaction create by the controller-action

---

docs/modules/WebDriver.md
src/Codeception/Module/WebDriver.php

adds support of pageload_timeout config to WebDriver
the amount of time to wait for a page load to complete before throwing an error
calls facebook/webdriver/lib/WebDriverTimeouts.php::pageLoadTimeout($seconds)
This patch allows to reduce issues from phantomjs random freezing, especially within CI environment 
https://github.com/ariya/phantomjs/issues/11526
patch based on suggestion from  https://github.com/ariya/phantomjs/issues/11526#issuecomment-115135376

Wedriver pageload timeout

---

src/Codeception/Lib/Parser.php

A better alternative to `@exec`
Thanks to @mklemarczyk

[Parser] Use function_exists to check that exec is disabled

---

composer.json

The name used to be `codeception/codeception`, but it was changed to `codeception/base` by https://github.com/Codeception/Codeception/commit/d58d5547a7fa435ed61f8d6a9365067983709f83#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780L2
which looks like an accident.
This change could fix #3855

Changed package name to codeception/codeception

---

src/Codeception/Subscriber/GracefulTermination.php

Hi,
This PR is related to #3607 and it should enable graceful termination for PHP >= 7.1
PHP 7.1 introduced the new way to handle signals asynchronously [pcntl_async_signals](http://php.net/manual/en/migration71.new-features.php#migration71.new-features.asynchronous-signal-handling)

PHP 7.1 - Used new pcntl_async_signals function to handle graceful termination

---

src/Codeception/Lib/ParamsLoader.php

My use case: In a project we use simple `.env.php` file instead of `vlucas/phpdotenv` and want to load params (specifically APP_URL) from it instead of duplicating configs.
It also fixes a bug when trying to load params from `.env.yml` and `.env.ini` results in an error "vlucas/phpdotenv library is required to parse .env files." which makes little sense to me.

[2.2] Support php files in ParamsLoader.php

---

src/Codeception/Module/WebDriver.php
tests/data/app/view/form/field_values.php
tests/data/app/view/form/select_second.php
tests/data/app/view/form/textarea.php
tests/web/WebDriverTest.php

* support option text in `seeInField` not only value
* fix bug match with and without whitespaces see also https://github.com/facebook/php-webdriver/pull/394
* fix bug `seeInField` not working after `selectOption`

add option text to seeInField

---

src/Codeception/Module/WebDriver.php
src/Codeception/Util/Locator.php
tests/unit/Codeception/Util/LocatorTest.php

If `.classname` is passed, WebDriver will search for element using `WebDriverBy::className`
Closes #3196

WebDriver: added search by class to fuzzy search (may improve speed)

---

src/Codeception/Module/WebDriver.php
tests/web/WebDriverTest.php

Browser tabs can be managed from withing WebDriveri module. Not supported in PhantomJS
* openNewTab
* closeTab
* switchToNextTab
* switchToPreviousTab
Closes #2975

WebDriver: added actions for managing tabs

---

src/Codeception/Lib/InnerBrowser.php
tests/data/app/view/form/bug3824.php
tests/unit/Codeception/Module/PhpBrowserTest.php

I don't know what the extra `<option>` was for so I expect this PR to maybe fail a test somewhere.
Other than that it adds a test for the bug and removes the code causing the bug.
Fixes #3824

Fix bug #3824 by removing code that added extra option.

---

src/Codeception/Module/WebDriver.php

When you try to click on a link that has only numbers `$I->click('222')` you get a invalid css selector exception.
Exception
```
[Facebook\WebDriver\Exception\InvalidElementStateException] {"errorMessage":"SyntaxError: DOM Exception 12","request":{"headers":{"Accept":"application/json","Content-Length":"38","Content-Type":"application/json;charset=UTF-8","Host":"127.0.0.1:8910"},"httpVersion":"1.1","method":"POST","post":"{\"using\":\"css selector\",\"value\":\"217\"}","url":"/elements","urlParsed":{"anchor":"","query":"","file":"elements","directory":"/","path":"/elements","relative":"/elements","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/elements","queryKey":{},"chunks":["elements"]},"urlOriginal":"/session/d2fe7e50-c80e-11e6-afe3-9d1 …
```

fix click on links with only numbers DOM Exception 12

---

src/Codeception/Module/REST.php

Generated Actions class is missing `deleteHeader` when using REST module with `part` option

Added missing @part json and xml to deleteHeader

---

src/Codeception/Module/Laravel5.php

There was a problem using the Laravel5 module with an application that does not use a database, see #3942. This is fixed by commit a15da6b44e6b44bd0319bff7dc2f59a51bf3b30b.
There also was a problem with the implementation of the `run_database_seeder` functionality, see #3948. This is fixed by commit 5976db3f4e53cf56160964cd4a64a1aef20bd1ab, the database seeder now runs after the database cleanup transaction is started.

Laravel5 module fixes

---

src/Codeception/Lib/InnerBrowser.php
tests/data/app/controllers.php
tests/data/app/view/form/bug3953.php
tests/unit/Codeception/Module/PhpBrowserTest.php

[InnerBrowser] If form has no id, use action attribute as identifier

---

src/Codeception/Subscriber/Console.php
src/Codeception/Test/Descriptor.php
tests/cli/RunCest.php

When a Feature title has some special chars in it like `/` or `-` the test coloring is broken.
```
Feature: Tests-special chars
Scenario: test 1
Given I am on "/"
```

Fix test coloring

---

docs/modules/AMQP.md
src/Codeception/Module/AMQP.php

The added methods allow users to bind an (non-existent) exchange to a (non-existent) queue in AMPQ module. This is useful when you want to test some pub/sub implementation with a producer that pushes messages to an exchange (and not directly to a queue).

Add methods to bind an (non-existent) exchange to a (non-existent) queue in AMPQ module

---

src/Codeception/Module/REST.php

As per https://github.com/Codeception/Codeception/issues/1884#issuecomment-276941773

hide binary response data in debug #1884

---

src/Codeception/Module/WebDriver.php

Sometimes, when test failed because some element on page is missing I receive TimeOutException exception with empty message. Now I will pass error message to wait*() methods like $I->waitForText('foo', 10, 'Text foo was not found');

Pass error message from wait*() methods to until()

---

docs/03-AcceptanceTests.md
src/Codeception/Module/WebDriver.php
src/Codeception/Util/ActionSequence.php
tests/web/WebDriverTest.php

Closes #3936
See attached documentation and method's reference

added `performOn` method to WebDriver

---

src/Codeception/Module/REST.php
tests/unit/Codeception/Module/RestTest.php

binary output checks for REST module

---

src/Codeception/Module/WebDriver.php
tests/web/WebDriverTest.php

On ed549a9d2c5b6d4ccf940a6dcfa671cd042e8f99 an `else` statement was removed (awesome) but the author forgot to interrupt the execution flow and that is causing our test suite to fail :sob: but this fixes it.
Fixes #4001

Fix small refactoring issue

---

src/Codeception/Test/Cept.php

When \ParseError was thrown during test execution , the actual message was lost.
This change helps to debug issues like #4002

Add parse error to TestParseException in PHP7

---

docs/modules/DataFactory.md
src/Codeception/Module/DataFactory.php

Add option cleanup for DataFactory. If option cleanup in DataFactory config set to FALSE that don`t need delete records by self.
Also move create default story for new method for more flexible extend it. 
Default option cleanup is TRUE for save old behavior.

Issue #3987. Add option cleanup for skip cleanup

---

src/Codeception/Scenario.php
src/Codeception/Subscriber/Console.php
tests/cli/RunCest.php
tests/data/claypit/tests/scenario/Fail.feature

When you have run a feature file and mulitple scenarios fails.
Then in the exception message the step is always the last one.
I am not sure what `conditionalFails` means. See change.

fix printScenarioFail with multiple scenarios

---

src/Codeception/Module/Laravel5.php

This fixes the "Too Many Connections" issue when running a large test suite which has multiple connection names that point to the same database (i.e. local dev, CI pipeline).
Issue: #4031

4031: Close all Laravel DB connections after test execution

---

docs/reference/Commands.md

If you execute g:step you get an ambigous error:
> [Symfony\Component\Console\Exception\CommandNotFoundException]       
>   Command "g:step" is ambiguous (generate:stepobject, gherkin:steps). 
I corrected the docs from g:step to g:stepobject

- g:step gives ambigous warning. add distinct command to docs

---

src/Codeception/Module/Yii2.php

The same behavior on load fixtures:
https://github.com/yiisoft/yii2-codeception/blob/master/TestCase.php#L85

Fixtures behavior compability with `yii2-codeception`

---

autoload.php

A popular cause of Codeception issues is incompatibility between locally installed dependency of the project and globally installed or packaged in phar file dependency of Codeception.
This is an attempt to eliminate one of the causes - when there is a local Codeception, but developer runs a globally installed version.
Example with phar file:
```
user@pc:~$ php codecept.phar 
Codeception 2.2.8
...
user@pc:~$ cd project
user@pc:~/project$ php ~/codecept.phar
==== Redirecting to Composer-installed version in vendor/codeception ====
Codeception version 2.2.6
``` 
Inspired by https://github.com/sebastianbergmann/phpunit/commit/4fe95a5b44de678315775743125518ce41610a19

Use local composer installation if available

---

tests/cli/BuildCept.php

The following command `./codecept run cli tests/cli/BuildCept.php` gives deprecation warning.
```
DEPRECATION: Codeception: $scenario->group() has been deprecated and removed. Use annotations to pass scenario params /home/gfranke/Codeception/src/Codeception/Scenario.php:150
```

fix deprecation warning in cli test suite

---

src/Codeception/Lib/GroupManager.php

This is caused by use of `Finder::path()` at https://github.com/Codeception/Codeception/blob/2.2/src/Codeception/Lib/GroupManager.php#L43-L47 when `groups` parameter is set in codeception.yml
Finder is referencing every files in project root dir, then filters them according to string passed to `path()`. If a lot of files stand in project root dir, it can takes more than 2minutes to find a few group files.
Here's a patch to get rid of `Finder::path()`. It reduces elapsed time from several minutes to few seconds.

Looking for group files can be really slow

---

src/Codeception/Module/WebDriver.php

There's a double check on the same cookie.

Fix coverage cookie check, mentioned in #2923

---

src/Codeception/Util/Locator.php

When using the following code in a test
```
Locator::elementAt('.my-selector', 2)
```
PhpStorm reports a parameter type mismatch error due to reading the words immediately after the parameter names in the docblock as a type. This can be fixed by adding scalar types to the docblock which makes no change to the code operation.
Also fixed another warning about an unneeded fully qualified class name in the same file.

Fix bug with docblock causing incorrect parameter error in IDE

---

src/Codeception/Module/WebDriver.php
src/Codeception/Step.php
src/Codeception/Util/ActionSequence.php
tests/web/WebDriverTest.php

Fixed action sequence to include multiple actions

---

src/Codeception/Command/Bootstrap.php
src/Codeception/Command/Build.php
src/Codeception/Command/Clean.php
src/Codeception/Command/ConfigValidate.php
src/Codeception/Command/Console.php
src/Codeception/Command/DryRun.php
src/Codeception/Command/GenerateCept.php
src/Codeception/Command/GenerateCest.php
src/Codeception/Command/GenerateEnvironment.php
src/Codeception/Command/GenerateFeature.php
src/Codeception/Command/GenerateGroup.php
src/Codeception/Command/GenerateHelper.php
src/Codeception/Command/GeneratePageObject.php
src/Codeception/Command/GeneratePhpUnit.php
src/Codeception/Command/GenerateScenarios.php
src/Codeception/Command/GenerateStepObject.php
src/Codeception/Command/GenerateSuite.php
src/Codeception/Command/GenerateTest.php
src/Codeception/Command/GherkinSnippets.php
src/Codeception/Command/GherkinSteps.php
src/Codeception/Command/Run.php
src/Codeception/Command/Shared/Config.php
tests/unit/Codeception/Command/GenerateSuiteTest.php

$input->getOption('config') no longer provides a config file, it is loaded inside Application, so it's always `null` inside a command class. The custom config is already loaded by that time. This is the reason why nothing was broken ).
Also I removed the `module: config:` section from the bootstrap template. They are never used and may be confusing

Command Cleanup

---

CHANGELOG-2.2.md
src/Codeception/Lib/Connector/Laravel5.php
src/Codeception/Module/Laravel5.php

A generic solution for handling issues such as reported in #4062.
The names of the new methods are `haveApplicationHandler` and `clearApplicationHandlers`, I am open to suggestions for better names.
An example test using this functionality would be:
```
<?php
$I = new FunctionalTester($scenario);
$I->haveApplicationHandler(function($app) {
$app->make('config')->set(['test_value' => 10]);
});
$I->sendGET('/test-value');
$I->see('Test value is 10');
$I->haveApplicationHandler(function($app) {
$app->make('config')->set(['test_value' => 15]);
});
$I->sendGET('/test-value');
$I->see('Test value is 15');
$I->clearApplicationHandlers();
$I->sendGET('/test-value');
$I->see('Test value is 5'); // 5 is the default value
```

Application handler functionality

---

src/Codeception/Test/Unit.php

This is the new recommended approach to use actor classes inside unit tests:
```php
function _inject(UnitTester $I)
{
$this->i = $I;
}
function testRobotUserIsInsideDatabase()
{
$this->i->seeInDatabase('users', ['id' => 1, 'name' => 'robot']);
}
```
`$this->tester` injection into Test\Unit classes happen in a very mysterious way. While this injection still happens it should be done explicitly, using `_inject` method we already have. This will allow to specify and name properties in predictable names. This will also allow to use classes based on Actor, like PageObjects, or StepObjects.
This new recommended way will be added to docs, while old one will be removed. However, property-based old-style injection will be kept till 3.0 and probably even after it.

Auto-Inject into Test\Unit

---

CHANGELOG-2.2.md
src/Codeception/Module/Memcache.php

Sometimes when some exception happens during tests and before `_before` method is run in memcache module then in `_after` method flush is done on null causing other error.

Fixed calling flush on null

---

src/Codeception/Command/Run.php

Supports running
```
codecept run tests/unit
```
Improves recent [PhpStorm integration](https://blog.jetbrains.com/phpstorm/2017/03/codeception-support-comes-to-phpstorm-2017-1/). Now you can run a suite tests by running tests on a suite directory.

Run suite by its path

---

src/Codeception/Module/ZendExpressive.php

Migration to Zend Expressive 2.0 creates 2 new config files that must be included explicitly

[ZendExpressive] Support Zend Expressive 2.0

---

docs/modules/Silex.md
src/Codeception/Module/Silex.php

The recommended way to disable the exception handler in Silex 1.3 and Silex 2.0 docs is:
unset($app['exception_handler']);
#4082

$app['exception_handler']->disable() fails

---

.travis.yml

* Phalcon no longer support PHP 5.4
* Enabled Phalcon for PHP 7.1
* Improved install call

Enable Phalcon for PHP 7.1

---

src/Codeception/Step/ConditionalAssertion.php
tests/unit/Codeception/Step/ConditionalAssertionTest.php

Fixes #3860 
Output before:
```
1) CloseWindowCept: Close current window
Test  tests/web/CloseWindowCept.php
Step  Can dont see "Close Window"
Fail  Failed asserting that  on page /form/close_window
--> Page 2
Close Window
--> does not contain "close window".
Scenario Steps:
8. $I->see("Open Window") at tests/web/CloseWindowCept.php:11
7. $I->switchToPreviousTab() at tests/web/CloseWindowCept.php:10
6. $I->click("Close Window") at tests/web/CloseWindowCept.php:9
5. $I->seeCurrentUrlEquals("/form/close_window") at tests/web/CloseWindowCept.php:8
4. $I->canDontSee("Close Window") at tests/web/CloseWindowCept.php:7
3. $I->switchToNextTab() at tests/web/CloseWindowCept.php:6
```
Output after:
```
1) CloseWindowCept: Close current window
Test  tests/web/CloseWindowCept.php
Step  Cant see …
```

Fixed textual representation of cant steps

---

src/Codeception/Module/ZF2.php

In Cest test format suit generates exception if suit contains more than one public method:
`[PHPUnit_Framework_Exception] session_regenerate_id(): Cannot regenerate session id - session is not active`

Removed session_write_close() from ZF2 module (#4112)

---

src/Codeception/Module/Asserts.php
src/Codeception/Util/Shared/Asserts.php

Currently it's not possible to assert floating-point numbers reliably using the `assertEquals` and `assertNotEquals` methods inside the **Asserts** module.
This commit adds an additional default parameter to the above mentioned methods while following PHPUnit's method prototypes. There shouldn't be any backwards incompatible changes introduced here.

[Asserts] Add delta parameter to assertEquals() assertNotEquals() methods

---

src/Codeception/Lib/InnerBrowser.php
src/Codeception/Module/WebDriver.php
tests/unit/Codeception/Module/TestsForWeb.php
tests/web/WebDriverTest.php

attachFile method of WebDriver throws confusing message `[InvalidArgumentException] file not found or not readable:  ` when the file does not exist #4091 .
It was a fault of `realpath` function which returns FALSE when the file does not exist.
I fixed it to throw `[InvalidArgumentException] File does not exist: /path/to/tests/_data/filename.ext`.
And a different message `[InvalidArgumentException] File is not readable: /path/to/tests/_data/filename.ext`
when the file exists but is not readable.
Also I updated InnerBrowser to throw the same messages,
it used to throw `PHPUnit_Framework_AssertionFailedError` `file filename.ext not found in Codeception data path. Only files stored in data path accepted`

[Webdriver] fixed attachFile messages when the file does not exist

---

docs/07-AdvancedUsage.md
src/Codeception/Test/Loader/Cest.php
tests/data/claypit/tests/scenario/DataProviderCest.php

https://phpunit.de/manual/current/en/writing-tests-for-phpunit.html
default in phpunit is "dataProvider" support both for now ("dataprovider" need mark deprecated?)

support dataProvider - fix case

---

src/Codeception/Lib/Driver/Db.php
src/Codeception/Module/Db.php
tests/unit/Codeception/Lib/Driver/MysqlTest.php

This functionality was accidently broken by removal of sqlToRun property in 2.2.10
Replaces #4115

[Db] loadDump reports sql statement which caused error

---

src/Codeception/Module/Symfony.php

As per https://github.com/Codeception/Codeception/issues/3829 - this PR allows for not requiring bootstrap.php.cache any longer for php versions > 7 - but will still use it if is available

Make symfony bootstrap.php.cache optional for php version > 7

---

src/Codeception/Lib/Driver/Oci.php

Currently cleanup method throws exception when trying to drop object with case sensitive identifier.

Oci::cleanup() should be able to drop objects with case sensitive name

---

src/Codeception/Subscriber/Console.php
tests/cli/RunCest.php

This part of output was missing for regular steps.
```
Step  See file found "games.zip"
Fail
```
http://phptest.club/t/seeelement-wierd-fail-message/1470

Fixed output of failed step

---

src/Codeception/Module/Yii2.php

In some cases it's not needed. Additionally, environment may be named differently.

Removed environment check from Yii 2.0 module

---

src/Codeception/Test/Metadata.php
tests/unit/Codeception/ScenarioTest.php

Fixed $scenario->current('name')

---

src/Codeception/Lib/Connector/Guzzle6.php

Codeception\Lib\Connector\Guzzle6::extractFormData did not support DELETE form data.
This PR fixes #4164

Add DELETE method to supported form data request methods in Guzzle6::extractFormData

---

src/Codeception/Lib/InnerBrowser.php
src/Codeception/Lib/Interfaces/Web.php
src/Codeception/Module/WebDriver.php
tests/data/app/controllers.php
tests/data/app/index.php
tests/data/app/view/minimal.php
tests/unit/Codeception/Module/PhpBrowserTest.php
tests/web/WebDriverTest.php

Extracted from #4136.
Added `Codeception\Lib\Interfaces\Web::grabPageSource()` method. Implemented the method in `Codeception\Lib\InnerBrowser` and `Codeception\Module\WebDriver`. Added test coverage for scenarios when page is and is not loaded.
I tried to be consistent with the rest of the code base. Is `grabPageSource()` OK?
There's one problem: `Selenium` adds `xmlns="http://www.w3.org/1999/xhtml"` while `PhantomJS` does not do that. I'm not quite sure how to handle that gracefully. I'm not quite happy with the 
```php
$sourceActualRaw = $this->module->grabPageSource();
$sourceActual = str_replace('xmlns="http://www.w3.org/1999/xhtml"', '', $sourceActualRaw);
```
and `isPhantom()` is `protected`...

Add a method to `Codeception\Lib\Interfaces\Web`

---

src/Codeception/Lib/Driver/MongoDb.php

Hello,
I think this is a better way for decide wich mongo have to use. If you use both legacy _mongo_ and the current _mongodb_, the legacy value will be false.
Issue #4174

improve mongo legacy check

---

src/Codeception/Lib/Driver/MongoDb.php
tests/data/dumps/mongo.js
tests/unit/Codeception/Module/MongoDbTest.php

I've made changes in the MongoDb module, because the hostname and dbname variables were got wrong values when the dsn contain any [connection string option](https://docs.mongodb.com/manual/reference/connection-string/) (like connectTimeoutMS).
MongoDbTest has been extended.
I reported the issue #4179 a couple of days before.

Mongo parsing dbname

---

src/Codeception/Lib/Connector/Yii1.php

When you try to make request end with slash
`$I->amOnPage('/en/sign-in/');`
you will get changed request to `/index-test.php/en/sign-in`

Allow to make requests end with slash

---

src/Codeception/Module/Doctrine2.php

Consider the following
```php
$I->seeInRepository(
'OrderItem',
array(
'order' => array(
'recipient_email'=> self::MEMBER_EMAIL
)
)
);
```
Generates the following query:
```
SELECT s FROM OrderItem s INNER JOIN s.order order WHERE order.recipient_email = :order__recipient_email
```
Currently fails with expected literal due to the use of the word order as an alias.
The suggested change would produce
```
SELECT s FROM OrderItem s INNER JOIN s.order _order WHERE _order.recipient_email = :_order__recipient_email
```
Fixes #4194

Safe prefix aliases for buildAssociationQuery()

---

src/Codeception/Module/WebDriver.php
tests/unit/Codeception/Module/TestsForWeb.php

[WebDriver] seeLink compares relative links correctly

---

src/Codeception/Lib/Connector/Yii1.php

If you have enabled pretty url and try to set only host in url
```
modules:
enabled:
- Yii1:
appPath: ./../../public/index-test.php
url: http://localhost/
```
you will get warning (and exception in error handler) `strpos(): Empty needle`

Allow to set only host

---

src/Codeception/Step.php
tests/unit/Codeception/Command/GenerateScenarioTest.php
tests/unit/Codeception/ScenarioTest.php
tests/unit/Codeception/StepTest.php

When you add e.g.:
```php
$I->executeJS('/* AAA </td> BBB <td> CCC */');
```
to test it will broke HTML report because "td" end tag will be generated like is.

FIX broken HTML report

---

src/Codeception/Configuration.php

When you run:
`php vendor\codeception\codeception\codecept run -vvv --override="paths: log: tests/_output/Acceptance_TestCest_test" --xml=report.xml tests\acceptance\TestCest:test`
it generates report and error screenshots to tests/_output and not to tests/_output/Acceptance_TestCest_test
... and override by configuration also does not work - this commit fix only override by parameter. Try add to tests/acceptance.suite.yml:
```yml
env:
development:
paths:
log: tests/_output/runner1
```
and run:
`php vendor\codeception\codeception\codecept run -vvv --env=development --xml=report.xml tests\acceptance\TestCest:test`
it generates report and error screenshots to tests/_output and not to tests/_output/Acceptance_TestCest_test

FIX log path override

---

src/Codeception/Module/Doctrine2.php

Fix https://github.com/Codeception/Codeception/issues/4211

fix haveFakeRepository in the doctrine module

---

docs/01-Introduction.md
src/Codeception/Module/Redis.php

According to Document ( http://codeception.com/docs/modules/Redis ) and comments of module source, it says Codeception flushes the database "At the beginning of every suite" ( `cleanupBefore: 'suite'` ) . However default setting of `cleanupBefore` is set to "At the beginning of every test" ( `cleanupBefore: 'test'` ), so description of documentation is not actually true.
And flushing database without any attention seems dangerous behavior, so I turned default configuration to safe-side.
* If this change accepted, Document ( http://codeception.com/docs/modules/Redis ) have be updated.

Redis module default configuration must be more foolproof.

---

src/Codeception/Util/JsonArray.php
tests/unit/Codeception/Module/PhpBrowserRestTest.php

Replaced fatal error with Assertion Failed "JSON response is not an array: ...".
Fixes #4202

[REST] seeResponseContainsJson doesn't crash when json response is not array

---

docs/09-Data.md
docs/modules/Doctrine2.md
src/Codeception/Lib/Interfaces/DataMapper.php
src/Codeception/Module/Doctrine2.php

Hi,
using Codeception for a Symfony 2 project, I faced an issue with Doctrine association. 
In short, an entity "Car" have an association to an entity "Driver". I use gherkin syntax, and I have two "Given" directives to describe that:
```
Scenario: Karl drives a car
Given I have these drivers:
| id  | name |
| d1 | Karl    |
And I have these cars:
| id | plate             | driverId |
| c1 | AB-123-CD | d1           |
```
In my Tester code, these Given directives are runned by this code:
```
<?php
/**
* @Given I have these drivers:
*/
public function theDriversExist(TableNode $table) {
$hash = $table->getHash();
foreach($hash as $row){
$driverAttributes = [
"id" => $row['id'],
"name" => $row['name']
];
$this->haveInRepository(Driver::class, $driverAttributes);
}
}
/**
* @Given I have …
```

Add in Doctrine module the possibility to grab Doctrine entities

---

docs/07-AdvancedUsage.md

See https://github.com/Codeception/Codeception/pull/4225#issuecomment-302549188
BTW: Is http://codeception.com/docs/07-AdvancedUsage not updated in real-time from `07-AdvancedUsage.md`? I still see the old version there...

Deleted example for *public* dataprovider function

---

composer.json

My builds on Travis are failing because composer autoloading doesn't work correctly for PHPUnit 6.
```
PHP Fatal error:  Interface 'PHPUnit_Framework_Test' not found in ...\vendor\codeception\codeception\src\Codeception\TestInterface.php on line 7
```
So far the only fix I found was to add `"files": ["vendor/codeception/codeception/shim.php"]` to my `autoload-dev` in composer.json. This commit should fix the issue.

Fix autoloading with PHPUnit 6

---

src/Codeception/Module.php
src/Codeception/Module/Cli.php
src/Codeception/Module/Db.php
src/Codeception/Subscriber/Module.php
tests/unit/Codeception/Module/PhpBrowserTest.php
tests/unit/Codeception/Module/TestsForWeb.php

While refactoring Db module I accidentally hit the old API and this made accidentally call database cleanups before each test without considering a `cleanup` option. This happened because `_cleanup` method was called before each test as part of the initialization process of a module (no one used it actually).

Db cleanup fix

---

src/Codeception/Lib/Interfaces/Web.php

params are not optional, but mandatory: https://github.com/Codeception/Codeception/blob/2.3/src/Codeception/Lib/Interfaces/Web.php#L282

Fixing error

---

composer.json

#4277
A real fix is necessary, but this is good as a temporary measure.

Temporary constraint for symfony/console to stop builds breaking

---

RoboFile.php
src/Codeception/Command/SelfUpdate.php

* Updated desciption of php54 build in Releases page
* phar selfupdate downloads php54 build if php version <7.0
* Install dependencies for PHP 7.0.0 before packaging phar file
Closes #4269

Robofile changes

---

src/Codeception/Lib/InnerBrowser.php

Don’t skip empty strings in headers.

---

docs/06-ModulesAndHelpers.md
tests/facebook/FacebookTest.php

Removed `_cleanup()` in  Facebook tests and in reference

Fixed Facebook test, removed _cleanup() from module docs

---

src/Codeception/Module/WebDriver.php

Hello,
Currently, makeScreenshot of WebDriver require a name to save a file.
This little PR accept noname.
$I->makeScreenshot('edit_page'); //saved to: tests/_output/debug/edit_page.png
$I->makeScreenshot(); //saved to: tests/_output/debug/2017-05-26_14-24-11.png
What do you think ?

Update WebDriver:makeScreenshot to accept noname

---

src/Codeception/Module/Symfony.php

When extracting roles from security collector, you can simply utilize the getValue method of Data class, when it exists.

Symfony::extractRawRoles() failed on security collector from Symfony >= 3.3

---

src/Codeception/Module/WebDriver.php

This allows launching tests using ChromeDriver only (without Selenium).

Added ChromeDriver-only config to WebDriver setup

---

src/Codeception/Lib/Interfaces/MultiSession.php
src/Codeception/Module/PhpBrowser.php
src/Codeception/Module/WebDriver.php
tests/web.suite.yml
tests/web/WebDriverTest.php

* added `start` option to disable autostart of a browser for tests. (can be useful for Cloud testing setups)
* added _capabilities method for setting desired capabilities in runtime
* `_initializeSession` and `_closeSession` added to public api of WebDriver
* added _closeSession null option to close the default session
* added few more environments to web.suite.yml

Webdriver method for setting capabilities, starting and closing session

---

src/Codeception/Lib/Interfaces/Web.php

Please double-check if this is true! And what does `dontSeeInField` do?: `!==` or `does not contain`?

Clarified docblock of `seeInField`

---

src/Codeception/Lib/Interfaces/Web.php

Changed from `string` to `int`.
Array syntax as recommended at https://www.phpdoc.org/docs/latest/guides/types.html#arrays

Fixed error

---

docs/02-GettingStarted.md

I don't know if this is the right place. But there should be a short introduction like this. Please make this section (i.e. anchor) the link target for codeception.com "User Centric Tests => Learn more"
Details:
* grab: Is there an easier exmple you can think of? One that doesn't require the Asserts Module?
* Missing in the list is "have" and maybe "expect". Maybe I can convince you to change those :-) See https://github.com/Codeception/Codeception/issues/4257
I'd like to rewrite the next section (Actors) too. Questions:
* I guess the term "Actor" is a leftover from previous versions of Codeception? More precise: Today, it's not really important (anymore) to know the term "Actor", is it?
* What do you mean by "Actor classes are not written but generated from suite configuration." => That …

Explain the naming philosophy

---

src/Codeception/Lib/Interfaces/Web.php
src/Codeception/Module/WebDriver.php

The `|` letters were rendered as a table

Minor formating

---

docs/09-Data.md

This fixes a simple mistake in a link to "Db module reference"

Corrected A Link In Data Docs

---

src/Codeception/PHPUnit/Constraint/Page.php

It used to return empty string which could cause an error
`[Error] Call to a member function append() on string`

PageConstraint:uriMessage always returns Message

---

src/Codeception/Module/WebDriver.php
src/Codeception/Util/Locator.php
tests/data/app/view/form/timeout.php
tests/web.suite.yml
tests/web/WebDriverTest.php

This should dramatically improve the stability for tests.
Whenever an element is required and is not on a page, setting `wait: 5` will make Codeception wait for 5 seconds to find it. 
This should simplify tests, and reduce a number of waiters:
```php
$I->waitForElement('#click-me', 5);
$I->click('#click-me');
```
can be simplified to
```php
$I->click('#click-me');
```
with `wait: 5` in config.
*(use CSS ids or strict locators to make this work with click)*
In the same way `$I->seeElement()` will wait for an element to appear before failing.
This should not affect the performance as implicit waits are added only when element is requried to continue a test.
---
Technical note:
Currently `wait` option corresponds to turning on Selenium [Implicit …

[WebDriver] Smart wait for elements.

---

src/Codeception/Module/Doctrine2.php
src/Codeception/Module/Laravel5.php
src/Codeception/Module/Phalcon.php
src/Codeception/Module/Yii2.php

Following the proposal from @ThomasLandauer  https://github.com/Codeception/Codeception/issues/4326#issuecomment-309429330
I added debug notifications when transaction is started for tests.
Probably the message should be improved, so suggestions are welcome

Print debug information for started/stopped transactions in tests

---

composer.json
ext/RunProcess.php

This extension allows in a simple way to start and stop background processes. 
It is useful for launching Selenium, PhantomJS, etc.

Added RunProcess extension

---

src/Codeception/Lib/Driver/Db.php
src/Codeception/Module/Db.php
tests/unit/Codeception/Module/Db/TestsForDb.php

Hello,
For my acceptance I need sometimes to update record in the database, so I added a new function to be able to do that in the module Db:
```php
$I->updateInDatabase('users', ['banned' => 'true'], ['id' => '123']);
```
What do you think ? I know it's better to start test with a clean database but I have a complex database that is coming from the production (anonymized) and I test it like a blackblox from the web. I can't populate all my database with only testing data.

[Db] Add update in database

---

wercker.yml

Wercker builds are often terminated by timeout.
I removed some of CLI tests so now they should work faster

Changed Wercker builds to run only RunCest tests

---

src/Codeception/PHPUnit/ResultPrinter/HTML.php

Fixes broken HTML report: When arguments of function contains html content, it should get encoded properly.
Fixes #3819

Fix broken HTML report #3819

---

src/Codeception/Lib/InnerBrowser.php
src/Codeception/Module/WebDriver.php
tests/unit/Codeception/Module/TestsForWeb.php

Adds support for associative arrays in seeInFormFields for both functional and acceptance tests.
`$I->seeInFormFields('form', ['foo' => ['bar' => 'baz']);`
Small issue: if a user does `$I->seeInFormFields('form', ['missing' => ['foo', 'bar']])` the error message will now be "Form element with '//*[@name='missing[0]']' was not found." But there's no way to know if the user was actually looking for a field with the name of "missing[0]".

Support associative arrays in seeInFormFields

---

src/Codeception/Lib/InnerBrowser.php
tests/data/app/view/form/checkbox_default_value.php
tests/unit/Codeception/Module/PhpBrowserTest.php
tests/unit/Codeception/Module/TestsForWeb.php

Currently if you use `submitForm` in functional tests passing a checkbox with the value of true and that checkbox doesn't have a value attribute in the HTML page, that field will have the value of an empty string in the resulting request because `setCheckboxBoolValues` just gets the value attribute of checkboxes. This pull request modifies it to check if the checkbox does have a value attribute, and if it doesn't it uses "on" as value.

[InnerBrowser] Submit default values of checkboxes

---

src/Codeception/Module/PhpBrowser.php
tests/unit/Codeception/Module/PhpBrowserTest.php

If path component was empty, it used previous url
Fixes #4383

[PhpBrowser] fixed second or later amOnUrl with empty path component

---

src/Codeception/Lib/InnerBrowser.php
tests/unit/Codeception/Module/TestsForWeb.php

Makes InnerBrowser's seeInField check for options' texts and trimmed texts on top of checking their values. This makes it behave the same as WebDriver as requested in #3905.
When an option's text is also its desired value, this avoids having to add a value anyway just to make `seeInFormFields` pass.
I did not add a test for the non trimmed text in TestsForWeb and left WebDriverTest::testSeeInFieldSelect as it is since it seems that the check for non trimmed values should be skipped with Selenium.

[InnerBrowser] Make seeInField check options' texts

---

src/Codeception/Lib/InnerBrowser.php
tests/unit/Codeception/Module/TestsForWeb.php

Using the Laravel5 module I have the issue that associative array inputs are duplicated, for example `<input name="foo[bar]">` results in both the `foo` and `foo[bar]` keys in the request. I added a check in `getFormPhpValues` to remove the spurious keys and leave the actual array only.
This issue doesn't occur in the framework modules which call `remapRequestParameters` (Phalcon, Universal, Yii, Yii2. Symfony and Zend may have the same issue) which then calls `http_build_query` on the request parameters and then `parse_str` on the query string. Same for PhpBrowser since Guzzle calls `http_build_query` on the `form_params` and `query` you pass to it. This has the side effect of leaving only the correct key since `"foo[bar]" = ''` and `'foo' = ['bar' => '']` have the same representation in …

[Laravel5] Don't duplicate associative array fields

---

composer.json
src/Codeception/Module/WebDriver.php

webDriver->getCapabilities() is available in facebook/php-webdriver >=1.3.0 which requires PHP 5.5
closes #4435

[WebDriver] Fixed fatal error in _before on PHP 5.4

---

src/Codeception/Module/WebDriver.php

$capabilityFunction should return array, otherwise on second test run you got:
```
[PHPUnit_Framework_Exception] Argument 1 passed to Facebook\WebDriver\Remote\DesiredCapabilities::__construct() must be of the type array, object given
```

_capabilities documentation fix

---

src/Codeception/Module/WebDriver.php

Use case: sometimes we want to wait for less than a second.

Make wait() in Webdriver module accept fractional amount of seconds

---

src/Codeception/Lib/ParamsLoader.php

This PR changes the params loader to use the `$_SERVER` global when loading from a `.env` file instead of `$_ENV`. The global `$_ENV` is [not populated by default](https://github.com/php/php-src/blob/master/php.ini-production#L618) on most installations of PHP, so users who try to use Codeception without any changes to their `php.ini` will not have params expanded into the corresponding values. I previously asked about this in [the PR which refactored the ParamsLoader to this state](https://github.com/Codeception/Codeception/pull/3786#discussion_r118803073) but didn't get a response, so decided to make a PR and fix some issues I've been having.
There is not much difference between `$_ENV` and `$_SERVER` in a CLI context, and `$_SERVER` is already being returned by `loadEnvironmentVars()`, …

Changing params loader to use $_SERVER global instead of $_ENV

---

src/Codeception/Module/MongoDb.php

Method `$response->getInsertedId()` already returns string. In case there is not a string `_toString()` will be called

Mongo haveInCollection fix

---

src/Codeception/Lib/Connector/Symfony.php

- Problem:
When I have several request within one test, my services have different _entity_managers_, which results in bugs.
- Problem cause:
When _profiler_ service is being loaded, dozens of services are instantiated. Some of them needs _entity_manager_, which has not been instantiated by that time, so it is null, and so container creates new one. Then we set _persistent_services_ (which include _entity_manager_), so all the other services will get _entity_manager_ from _persistent_services_, not the one created during _profiler_ enabled.
- Solution:
Set the persistent services and **then** enable the profiler.

Symfony/fix_profiler_loading 

---

src/Codeception/Template/Acceptance.php
src/Codeception/Template/Api.php

Hi there 👋 
After following the setup guide on a fresh project I got hit with a warning:
```
$ ./vendor/bin/codecept init api
Let's prepare Codeception for REST API testing
? Where tests will be stored? (tests) 
? Start url for tests (http://localhost/api) 
PHP Warning:  file_put_contents(tests/_support/_generated/.gitignore): failed to open stream: No such file or directory in /home/nico/Projects/myawesomeproject/vendor/codeception/codeception/src/Codeception/InitTemplate.php on line 204
> Created test directories inside at tests
> Api helper has been created in tests/_support/Helper
> ApiTester actor has been created in tests/_support
> Actions have been loaded
> Created global config codeception.yml inside the root directory
> Created a demo test ApiCest.php
INSTALLATION COMPLETE 
Next …
```

Create the _generated folder before writing a .gitignore file there

---

src/Codeception/Exception/TestParseException.php
src/Codeception/Lib/Parser.php
src/Codeception/Test/Cept.php

add line number to debug easier

add line number to TestParseException exception message

---

docs/12-ParallelExecution.md
src/Codeception/Module/Yii2.php

See https://github.com/yiisoft/yii2/issues/14757

Use `andWhere` instead of `where`

---

shim.php

Adds an extra shim check before aliasing all PHPUnit classes. Maybe we should consider adding a check for every class to avoid similar problems?
Fixes #4479 
The problem is caused by https://github.com/Codeception/Verify/pull/31 and additionally, it is reported in https://github.com/Codeception/Verify/issues/32

Fix aliasing issue with Codeception/Verify.

---

src/Codeception/PHPUnit/Overrides/Filter.php

This mirrors what PHPUnit does when filtering stack traces (since 2008).
It inject a "fake" frame into the top of the stack trace with the actual line where the unexpected exception was thrown. This makes the stack traces much more usable. Fixes #3200.

Inject exception file and line number frame into stack trace

---

src/Codeception/Module/WebDriver.php

Hello,
Sometimes when I load session snapshot it seems not working (user is log in but with very strange behaviour). I can't reproduce this every times but in my project I found this fix that work better.
I think when we need to load the cookies we need to delete all cookies before to be sure to not have a mix of different cookie in the same browser.
First browser
> cookieA
> cookieB
> => saveSessionSnapshot
Second browser
> cookie1
> cookie2
> => loadSessionSnapshot 
Actual result:
cookie1, cookie2, cookieA, cookieB
Expected result:
cookieA, cookieB

[WebDriver] Add deleteAllCookies before loadSessionSnapshot

---

tests/unit/Codeception/Lib/Console/DiffFactoryTest.php

In order to be compatible with different versions of sebastian/diff

Simplified DiffFactoryTest

---

src/Codeception/Module/AMQP.php

Because PhpStorm displayed typehints as `\_generated\AMQPMessage`
`_generated` namespace is used in generated action files.

[AMQP] Use fully qualified names in typehints

---

src/Codeception/Util/JsonType.php
tests/unit/Codeception/Util/JsonTypeTest.php

[REST] Fixed JsonType crash when key 0 is not an array

---

src/Codeception/Module/Doctrine2.php

I use the following config:
```
modules:
enabled:
- DataFactory
depends: Doctrine2
- Doctrine2
```
which results in getting the following error:
` [League\FactoryMuffin\Exceptions\SaveMethodNotFoundException] The save method 'persist' was not found on the model: 'League\FactoryMuffin\Stores\RepositoryStore'.  `
The reason is the sequence of modules - `DataFactory::_before` executes sooner then `Doctrine2::_before` , so `DataFactory` has `null` as `$em`.
As a workaround you can change the sequence of modules.
This PR solves the issue.

check if entity manager has been retrieved

---

src/Codeception/Lib/Connector/Guzzle.php
src/Codeception/Lib/Connector/Guzzle6.php
src/Codeception/Lib/Connector/ZF1.php
src/Codeception/Lib/Connector/ZF2.php
src/Codeception/Lib/Connector/ZendExpressive.php
src/Codeception/Lib/InnerBrowser.php

Updates to [Fix Underscore Bug in HTTP Headers #4520](https://github.com/Codeception/Codeception/pull/4520)
So this is an enhancement to accommodate special chars in the headers like underscore. 
I can now pass in a header with html encoded character example`client&#95;id` and later during header extraction decode the html character `client_id`.
The html decoding will only work if encoded chars are passed in else the functionality is unaffected.

Header Enhancements

---

src/Codeception/Lib/Generator/Cest.php
tests/unit/Codeception/Command/GenerateCestTest.php

Hi I've added support to allow for suites to have different namespaces from the main configuration namespace, while the actors still use the main namespace.
The specific use case for me was that I wanted to have a different namespace for each of my test suites, but still have the Actors be in the /tests/_support folder.
Sample suite configuration:
```
suite_namespace: 'tests\unit'
class_name: 'UnitTester'
```
Sample global configuration:
```
namespace: 'tests'
```
This pull request solves that by adding a new suite_namespace setting in the suite. This should not cause any breaking changes.

Cest generator: suite namespaces

---

docs/reference/Configuration.md

Thought I'd have a stab at improving the text here, mainly from a spelling/grammar/style point of view.  Also corrected the example name format for suite config dist files, from `suitename.dist.yml` to `suitename.suite.dist.yml`.

Improvements to Config Templates section in docs

---

.travis.yml

Because `pecl install mongodb`
fails with `pecl/mongodb is already installed and is the same as the released version 1.3.0`

[Travis] Force installation of mongodb

---

src/Codeception/Lib/Driver/PostgreSql.php
src/Codeception/Lib/Driver/SqlSrv.php

* SqlSrv driver wraps each part of identifier with []
* Removed getQuotedName method from PostgreSql driver, because it was functionally identical to method in parent class (" quotes are used by PostgreSql, but they are also used by parent Db class)
Fixes #4542

[Db] improved getQuotedName in SqlSrv driver

---

src/Codeception/Test/Unit.php

There has some update on [PHPUnit 5.7.23][]. It's solve the exception with empty message but adjust default behavior, so that we should fix default value on `setExpectedException()` method for this update.
[PHPUnit 5.7.23]: https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-5.7.md#5723---2017-10-15

Fixed setExpectedException() default value for PHPUnit 5.7.23

---

src/Codeception/Module/PhpBrowser.php
tests/unit/Codeception/Module/PhpBrowserTest.php

Headers option is processed by the module instead of passing it to constructor of Guzzle Client
Fixes #4576

[PhpBrowser] User-Agent can be set in config

---

src/Codeception/Module/WebDriver.php
tests/data/app/view/form/anchor.php
tests/web/WebDriverTest.php

Make it possible to click on a button by title. For example when you have a form button with only a font icon
```
<button type="submit" class="btn btn-default" title="save">
<i class="fa fa-save"></i>
</button>
```

add click by button title

---

src/Codeception/Lib/InnerBrowser.php
tests/data/app/view/info.php
tests/unit/Codeception/Module/PhpBrowserTest.php

This PR fixes https://github.com/Codeception/Codeception/issues/4509

Fix `see` when source code contains `<=` JS operator

---

src/Codeception/Suite.php

Fixes #4598 
Skipping the last test was completely unnecessary.
The test with missing dependency is marked as skipped later on anyway.
```
DebugIssueCest: Test1
Signature: DebugIssueCest:test1
Test: tests/functional/DebugIssueCest.php:test1
Scenario --
SKIPPED: This test depends on test5 to pass
DebugIssueCest: Test2
Signature: DebugIssueCest:test2
Test: tests/functional/DebugIssueCest.php:test2
Scenario --
PASSED
DebugIssueCest: Test3
Signature: DebugIssueCest:test3
Test: tests/functional/DebugIssueCest.php:test3
Scenario --
PASSED
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Time: 2.15 seconds, Memory: 15.75MB
There was 1 skipped …
```

Don't skip last test if some test has missing dependency

---

src/Codeception/Module/MongoDb.php

Allow .tgz extensions to pass validation

---

src/Codeception/Coverage/Subscriber/RemoteServer.php

Fixes #4610 
```yml
namespace: frontend\tests
```
produced something like `...frontend.tests...`
```sh
php-code/frontend/tests/_output/frontend.tests.acceptance.remote.coverage.xml
```

fix remote coverage name with slash

---

src/Codeception/Lib/Generator/Actions.php

fix #4613 
! n.b.:
I not check on BC broken or any other usage cases

remove use section from template actions in build cli command

---

src/Codeception/Lib/Connector/Yii2.php

Global event handlers should not persist between tests.
The `if` statement is needed since the `offAll()` function exists only since 2.0.10 of the framework.
Ping @samdark

[Yii2] Reset global event handlers

---

src/Codeception/PHPUnit/ResultPrinter/HTML.php

Fixes #4110 
Reset failures when the test ends.
Prevents tests with the same signature inheriting the failures from previous runs.

ResultPrinter\HTML: Reset failures when test ends (fix #4110)

---

src/Codeception/Module/REST.php

A quick bug fix that I just realized I forgot to push with last PR.
I was checking the config from initial setup. I was not checking the config once the array merge was done. This could lead to unnecessary exceptions to be thrown.

AWS Rest Config Bug Fix

---

tests/data/params/codeception_self.yml
tests/data/params/tests/dummy.suite.yml

Deprecated usage of % at the beginning of an unquoted string since symfony/yaml:3.1, throw ParseError since symfony/yaml:4.0.0

Fix deprecated YAML syntax

---

src/Codeception/Command/Run.php
tests/cli/CodeceptionYmlInTestsDirCest.php
tests/data/codeception_yml_in_tests_dir/_bootstrap.php
tests/data/codeception_yml_in_tests_dir/_output/.gitignore
tests/data/codeception_yml_in_tests_dir/_support/UnitTester.php
tests/data/codeception_yml_in_tests_dir/_support/_generated/.gitignore
tests/data/codeception_yml_in_tests_dir/codeception.yml
tests/data/codeception_yml_in_tests_dir/unit.suite.yml
tests/data/codeception_yml_in_tests_dir/unit/ExampleCest.php
tests/data/codeception_yml_in_tests_dir/unit/_bootstrap.php

Apply a workaround to fix #4432.
This allows having codeception.yml inside the tests directory by setting `paths`: `tests: .`
Fixing this issue properly requires a lot more work. The current CodeCeption implementation uses only basic string matching and does not expect "empty" tests path in multiple places. See for example Run->matchTestFromFilename() and Configuration::isEmpty()

Fixes #4432

---

.travis.yml
codecept
composer.json
src/Codeception/Command/CompletionFallback.php
tests/cli/DataProviderFailuresAndExceptionsCest.php

I am starting to work on support of Symfony 4.0.0-BETA1

Allow Symfony 4 components

---

tests/cli/IncludedCest.php

The build was broken by PHP Code Coverage bugfix of  issue 455 in version 5.2.4: 
`Fail  No text '<class name="BillEvans" namespace="Jazz\Pianist">' in currently opened file`
Actual output: `<class name="Jazz\Pianist\BillEvans" namespace="Jazz\Pianist">\n`
https://github.com/Codeception/Codeception/pull/4648

Fix test broken by php-code-coverage 5.2.4

---

src/Codeception/Subscriber/Console.php
tests/cli/RunCest.php
tests/data/claypit/tests/scenario/PartialFailedCest.php

Hello,
Context: In one cest file with three tests (1 success and 2 failed)
Actual result: 
```
There were 2 failures:
---------
1) PartialFailedCest: Test case two
Test  tests/scenario/PartialFailedCest.php:testCaseTwo
Step  See file found "testcasethree.txt"                  <==== bug here
Fail  File "testcasetwo.txt" not found at ""
Scenario Steps:
2. $I->seeFileFound("testcasetwo.txt") at tests/scenario/PartialFailedCest.php:14
1. $I->amInPath(".") at tests/scenario/PartialFailedCest.php:13
---------
2) PartialFailedCest: Test case three
Test  tests/scenario/PartialFailedCest.php:testCaseThree
Step  See file found "testcasethree.txt"
Fail  File "testcasethree.txt" not found at ""
Scenario Steps:
2. $I->seeFileFound("testcasethree.txt") at tests/scenario/PartialFailedCest.php:20
1. …
```

Wrong failed step

---

src/Codeception/Lib/Connector/Yii2.php

https://github.com/Codeception/Codeception/issues/4587
Before performing any request via REST module, I must obtain JWT token, that will allow me to perform request. Component, that generate JWT tokens use `Yii::$app->request->getUserIP()` and `Yii::$app->request->getHostInfo()`,  implementation of which [was changed in 2.0.13 release](https://github.com/yiisoft/yii2/pull/13780). Now it call `Yii::$app->request->getHeaders()`. `getHeaders()` method is create `HeaderCollection`, that will be cached inside private field.
For example I have such code:
```php
$token = Yii::$app->jwtProvider->getToken();
$I->amBearerAuthenticated($token);
$I->sendPost('/api/secure/resource', ['key' => 'value']);
$I->canSeeResponseCodeIs(200);
```
But you can simulate this problem more easier:
```php …
```

Perform Yii2 application reset before performing request in functional tests

---

src/Codeception/Subscriber/ErrorHandler.php
tests/unit/Codeception/Subscriber/ErrorHandlerTest.php

I have been working on getting my testing setup within a CI. I was looking at the output of one such run when I realized that the test did not appear to be finishing, but was not giving any errors. After digging into it, I learned that one of my Junior Developers created a new class following some of the legacy code in the system. They put includes inside a class file (rather than relying on the PSR-4 Autoloader). One of these includes was a script to check a user's login/session and redirecting them to the homepage if they weren't logged in. Because a call to exit without params is equivalent to exit(0), my CI system thought that the test completed succesfully when it didn't actual do so.
This change is an attempt to catch such instances in the future. I use a shutdown function defined …

Adding Logic In Case Of Exit

---

src/Codeception/Coverage/DummyCodeCoverage.php

Need to add 4th parameter "$ignoreForceCoversAnnotation = false" in DummyCodeCoverage::stop method for keeping signature from "SebastianBergmann\CodeCoverage\CodeCoverage"
Fixed error:
" Declaration of Codeception\Coverage\DummyCodeCoverage::stop($append = true,  
$linesToBeCovered = Array, array $linesToBeUsed = Array) should be compati  
ble with SebastianBergmann\CodeCoverage\CodeCoverage::stop($append = true,   
$linesToBeCovered = Array, array $linesToBeUsed = Array, $ignoreForceCovers  
Annotation = false)"

Issue-4663 fixed signature in DummyCodeCoverage::stop

---

tests/data/no_actor_suites/tests/BasicTest.php
tests/unit/Codeception/Module/MongoDbLegacyTest.php
tests/unit/Codeception/Module/MongoDbTest.php
tests/unit/Codeception/TestLoaderTest.php
tests/unit/Codeception/Util/StubTest.php
tests/web/WebDriverTest.php

I've refactored some tests, using:
- `assertCount` instead of `count` function;
- `assertObjectNotHasAttribute`, `assertObjectHasAttribute` and `assertArrayHasKey` instead of `isset` function;
- `assertContains` instead of `array_search` function.

Refactoring tests

---

src/Codeception/Lib/InnerBrowser.php
src/Codeception/Module/WebDriver.php
src/Codeception/Test/Descriptor.php

Add `Descriptor::getTestSignatureUnique()`, to create unique names for tests using examples where `Descriptor::getTestSignature()` is not unique.
Add use of the new unique descriptor to implementations of `PageSourceSaver` and `ScreenshotSaver` where filenames are being created to provide a unique filename for each failure.
Fixes #4672

Descriptor: getTestSignatureUnique

---

src/Codeception/Lib/Driver/SqlSrv.php

If your DSN for MS SQL (sqlsrv) specifies the `Database` param as the last option then the regex for the Database name find it due to the semicolon not being optional.

[Db] Database in DSN regex matching fix

---

composer.json
shim.php

Add class aliases used by Codeception\Util\Stub
Allows to install PHPUnit 6.5
Fixes #4715

Compatibility with phpunit-mock-objects 5.*

---

docs/12-ParallelExecution.md

Based on the examples in the documentation i adjusted the group names from p* to paracept_*. Otherwise the examples wont work.

[BUGFIX] Adjust group names from p* to paracept_* 

---

src/Codeception/Module/Lumen.php

Got this message when bootstrap file can't be found. The message does not point to the direct problem.

fix(Lumen): Undefined property: Codeception\Module\Lumen::$module

---

src/Codeception/Lib/Generator/Actions.php

If a module uses dependencies (like PhpBrowser for Facebook), these methods are not included for the hash calculation of the newly created actor trait (Actions::produce()).
During the hash check in AutoRebuild::updateActor() the hash is calculated with the included values. Therefore the Actor trait will be generated every time.
The difference between the two calculations is, that in SuiteManager:createSuite ModuleContainer::all() is called to populate the modules in the SUITE_INIT event, while the Actions class is relying on ModuleContainer::create(), which returns just the currently created module, but injects the dependencies to the internal modules array (Which id accessible by ModuleContainer::all()).
Creating the Actor on every run causes errors during parallel test execution. While …

Invalid Actor Hash Generation if dependencies are used

---

src/Codeception/Module/ZendExpressive.php

Previous PR #4464 was rejected because of missing tests. I've made two tests with single and multiple POST requests that creates entities in database. Now it is in this repository: https://github.com/artmnv/codeception-zend-expressive-tests/tree/doctrine-tests
I don't send PR in source repository because there is no 2.3 branch.
Feel free to ask additional help.

Add Doctrine2 integration to ZendExpressive module

---

.travis.yml
appveyor.yml
tests/unit/Codeception/Module/PhpBrowserTest.php

Pull request #4799 fails due to AppVeyor and Chocolatey installing PHP 7.2 and not constrained to any version. This entire file assumes PHP 7.1, so I added what I believe is the constraint for Chocolatey/cist. 
Disclaimer: I am not familiar with Chocolatey or AppVeyor so I'm kind of taking a stab in the dark, well an educated guess have you.

Appveyor.yml to specify php 7.1 and PhpBrowserTest fixes

---

src/Codeception/Module/REST.php

Fixed an issue when passing a file to sendPOST() method without name, size or type parameter.
Reproduced by:
```
$I->sendPOST('url', [], [
'uploadedFile' => [
'tmp_name' => 'path to existing file',
],
]);
```
Note: clone of #4779 but forked from 2.3

Fix REST module formatFilesArray function

---

src/Codeception/Module/DataFactory.php

- add `make` method to DataFactory that will return an instance without creating a record in the DB.
- add missing type definitions in DataFactory's DocBlocks

Add `make` method to DataFactory

---

src/Codeception/Lib/Interfaces/Web.php
src/Codeception/Module/WebDriver.php
tests/web/WebDriverTest.php

Is it right, that Codeception automatically generate this method in the AcceptanceTesterAction.php with the codecept build command?
```
/**
* [!] Method is generated. Documentation taken from corresponding module.
*
*
* @see \Codeception\Module\WebDriver::clearField()
*/
public function clearField($field) {
return $this->getScenario()->runStep(new \Codeception\Step\Action('clearField', func_get_args()));
}
```
Closes  #4726

Add clear field method

---

src/Codeception/Command/Clean.php

Fix the bug when output dir is not exist and run Clean command.
The follow messages is error output:
```
$ php vendor/bin/codecept clean -vvv
Cleaning up output /Users/miles/GitHub/104corp/104isgd-common-php//build...
In FileSystem.php line 17:
[UnexpectedValueException]                                                                                                                     
RecursiveDirectoryIterator::__construct(/Users/miles/GitHub/104corp/104isgd-common-php//build): failed to open dir: No such file or directory  
Exception trace:
RecursiveDirectoryIterator->__construct() at /Users/miles/GitHub/104corp/104isgd-common-php/vendor/codeception/codeception/src/Codeception/Util/FileSystem.php:17
Codeception\Util\FileSystem::doEmptyDir() at …
```

Fix clean command bug when output dir is not exist

---

src/Codeception/Step.php

A fix for #4854 unnecessary escaping in operation arguments logging. It's removing string escaping from the log:
before
[08:01:23.753] Wait for element visible {"xpath":"\\/\\/a[contains(text(),\\"Forgot your password?\\")]"} (13s 336ms)
17:01:03 I click {"xpath":"\\/\\/a[contains(text(),\\"Forgot your password?\\")]"}
after this fix
[08:01:23.753] Wait for element visible {"xpath":"//a[contains(text(),"Forgot your password?")]"} (13s 336ms)
17:01:03 I click {"xpath":"//a[contains(text(),"Forgot your password?")]"}

A fix for #4854 unnecessary escaping in operation arguments logging

---

src/Codeception/Step.php

Hi DavertMik
I’ve fixed Bug #2759 in the branch named “Issue-2759” in my fork. The problem wasn't DB module specific and was affecting all step description of parameters processed by Codeception\Step::humanize().
e.g. https://github.com/allure-framework/allure-codeception/issues/41  
Thanks!

Fixed humanize for utf8 strings

---

src/Codeception/Configuration.php

codeception.dist.yml:
```
paths:
tests: tests/codeception
output: tests/codeception/_output
data: tests/codeception/_data
support: tests/codeception/_support
envs: tests/codeception/_envs
actor_suffix: Tester
namespace: tests\codeception
groups:
api: [tests/codeception/acceptance/Module/Api]
```
Tests:
```
C:\site.ru\tests\codeception\acceptance\Module\Api\User\CheckEmailAvailabilityCest.php
```
Run tests:
```
$ codecept run acceptance -g api --no-ansi --no-interaction 
Testing started at 13:53 ...
Codeception PHP Testing Framework v2.3.8
Powered by PHPUnit 6.5.6 by Sebastian Bergmann and contributors.
[Groups] api 
Time: 445 ms, Memory: 8.00MB
No tests executed!
Process finished with exit code 0
```
Tests not found, but they are.
During debugging, I found that in …

Fixed making for $settings['path'] in Configuration::suiteSettings() on Windows

---

src/Codeception/Util/Uri.php
tests/unit/Codeception/Util/UriTest.php

PHP's parse_url fails on specific relative URLs.
If the absolute URL is passed, it parses as expected.
PHP Known bug: https://bugs.php.net/bug.php?id=70942
Discussion thread: https://github.com/Codeception/Codeception/issues/4847
```php
$I->amOnPage('/units/view/1/page:2');
```
Behaviour before:
```bash
1) AdminDevicesCest: Check i can see a particular device and all its scans
Test  tests/rServices/AdminDevicesCest.php:checkUnitScans
[InvalidArgumentException] Invalid URI /units/view/1/page:2
```
Behavior after:
```bash
I am on page "/units/view/1/page:2"
[Request Headers] []
[Page] /units/view/1/page:2
[Response] 200
```
Before patch
```bash
Unit Tests (10) ----------------------------------------------------------------------------------------------------------------
✔ UriTest: Url …
```

2.4 bug 4847

---

src/Codeception/Events.php
src/Codeception/Subscriber/Console.php
tests/cli/RunCest.php
tests/data/claypit/tests/unit/WarningTest.php

This PR requires following PRs for **phpunit-wrapper** :
- codeception/phpunit-wrapper#21
- codeception/phpunit-wrapper#22
Better support of PHPUnit warning status:
- add new event `test.warning`
- display 'W' instead of success for warning test cases

Improve support of PHPUnit warning status

---

docs/07-AdvancedUsage.md

Improved documentation **Advanced Usage** for clarifying usage of data provider (#4887) : new section "Dataprovider Annotations"
Additionally, the following sections have been promoted to level 2 instead of level 3: 
- Dependency Injection
- Example Annotation
- Before/After Annotations

Update Advanced Usage documentation for dataprovider

---

.travis.yml
CHANGELOG-2.4.md
src/Codeception/Lib/Connector/Yii2.php
src/Codeception/Module/Yii2.php

- No more static variables
- No more database connection caching (that didn't actually work)
- Support for multiple database connections / database services with names other than 'db'
This needs more testing; I've tested it in a few of my production apps.
Also somewhere in the docs we should update the "contract" about application state:
1. When a test starts you get a fresh application.
2. Just before a request is executed the `Request` and `Response` component are reloaded.
3. Application state is persisted after the request and reused for the next request (as long as it is not in the `Request` or `Response` component.
4. All PDO based connections are supported as long as they are subclasses of `yii\db\Connection` and fire the `AFTER_OPEN` event.
Database handling (for transactions)
1. …

Yii2 rework, new PR same changes.

---

.travis.yml
src/Codeception/Lib/Connector/Yii2.php

Certain kinds of exceptions (`ExitException`) lead to a code path where the response object was unset.
Test case was added to test repo.

Fixed an issue with exit exceptions

---

src/Codeception/Subscriber/GracefulTermination.php

Hi!
Latest available HHVM doesn't have `pcntl_async_signals()` on board, but mimics PHP 7.1, which was assumed to have. I added basic function_exists() check to prevent function-does-not-exist errors. This probably should be ported to older minor releases.

Added safety check for runtimes emulating php 7.1+ but not supporting pcntl_async_signals()

---

src/Codeception/Lib/Connector/ZF2/PersistentServiceManager.php

Fixed compatibility for ZF2 ServiceManager. Without that, you got an error:
```
Codeception PHP Testing Framework v2.4.1
--
11-Apr-2018 20:17:17 | Powered by PHPUnit 5.7.14 by Sebastian Bergmann and contributors.
11-Apr-2018 20:17:20 | PHP Fatal error:  Declaration of Codeception\Lib\Connector\ZF2\PersistentServiceManager::get($name) must be compatible with Zend\ServiceManager\ServiceManager::get($name, $usePeeringServiceManagers = true) in /data/vendor/codeception/codeception/src/Codeception/Lib/Connector/ZF2/PersistentServiceManager.php on line 8
```

Fixed compatibility with ZF2 ServiceManager

---

src/Codeception/Module/Yii2.php

Restored the null check that was deleted in https://github.com/Codeception/Codeception/commit/08e487b0854bcc1f8a8478a5d5b7cf9713cbbc76#diff-938f756d763fc21aace78bb43ea26870L238

Restore null check for client in Yii2 (fix #4929)

---

src/Codeception/Lib/Connector/Yii2.php
src/Codeception/Module/Yii2.php

Some modules keep references to the Yii2 Client object.
I wrongly assumed that the Yii2 Module was the only one, and thus I did application cleanup in upon client destruction.
Application destruction is now done in `_after()`.
An issue was fixed with the `$pdoCache` never getting filled.

Manual app reset

---

src/Codeception/Event/FailEvent.php
src/Codeception/Subscriber/Console.php

#4936 
I try to migrate from 2.3 to 2.4 an I got a errors like 
```sh
An Error occurred while handling another error:
yii\web\HeadersAlreadySentException: Headers already sent in /repo/vendor/phpunit/phpunit/src/Util/Printer.php on line 109. in /var/www/html/vendor/yiisoft/yii2/web/Response.php:366
Stack trace:
#0 /var/www/html/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders()
#1 /var/www/html/vendor/yiisoft/yii2/web/ErrorHandler.php(135): yii\web\Response->send()
#2 /var/www/html/vendor/yiisoft/yii2/base/ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(TypeError))
#3 [internal function]: yii\base\ErrorHandler->handleException(Object(TypeError))
#4 {main}
Previous exception:
TypeError: Argument 3 passed to …
```

remove typehint for php7 compability

---

src/Codeception/Module/Laravel5.php

Hi,
Recently I started noticing out of memory problem during Codeception run in my Laravel 5 project. After some profiling & investigation, I found out that Faker library used in Laravel factories causing some of those problems.
For now Laravel module doesn't support factories yet, but if we plan to do that we'd probably need to take care of this memory leak. Here is a ticket for it - #3849 
I expect this PR to be low risk because I'm just removing something from Service Container that is initialized one more time in next request.
I made some manual tests in my project on 96 tests, most of them are using factories:
Before:
```
Time: 12.31 seconds, Memory: 404.00MB
OK (96 tests, 380 assertions)
```
After:
```
Time: 13.43 seconds, Memory: 134.00MB
OK (96 tests, 380 assertions)
```

Fix memory leak when using Laravel factories inside Codeception

---

src/Codeception/Module/Symfony.php

It's not possible to set a Kernel different of the AppKernel, and I have
two kernels an Admin and an Api, and I need use ApiKernel to run tests.
This commit makes a checking if kernel defined exists in the path.
Because the previous version it gets the first kernel in my case it gets
AdminKernel and always returns Kernel not found, because the Kernel defined is different of the loaded kernel 
http://symfony.com/doc/3.4/configuration/multiple_kernels.html

Bug fix with multiple kernels

---

docs/07-AdvancedUsage.md
docs/reference/Configuration.md
src/Codeception/Configuration.php
src/Codeception/Test/Loader.php

Closes https://github.com/Codeception/Codeception/issues/5008
In addition to the standard test format classes (Cept, Cest, Unit, Gherkin), allow the user to specify their own test format classes, and configure the system to load these as well.

Add your own test format classes to the loader

---

src/Codeception/Module/Asserts.php
src/Codeception/Util/Shared/Asserts.php
tests/unit/Codeception/Module/AssertsTest.php

Adding new `assertXXX` methods..
The methods check for `NotTrue / NotFalse`, e.g., if you want to check, if a value is `not true`.. A simple `assertFalse()` may not suitable in this case, because the value also may be `null` or whatever..
The new `assert` methods from PHPUnit allow for the latter!
I also added Tests for the new assertions

adding new assert methods

---

src/Codeception/Lib/InnerBrowser.php
src/Codeception/Module/REST.php
tests/unit/Codeception/Module/PhpBrowserTest.php

This PR adds new assertions to check, if a `HttpStatusCode` is between a certain range (e.g., `4xx`) and provides "wrappers" for common blocks..
For example:
- `seeStatusCodeIsSuccessful()` checks for `2xx`
- `seeStatusCodeIsClientError()` checks for `4xx`
and so on..

new REST / InnerBrowser Asserts

---

ext/Recorder.php

Wasn't work as-is.
+ May be add snippet 
``` yaml
extensions:
enabled:
- Codeception\Extension\Recorder:
module: AngularJS # enable for Angular
delete_successful: false # keep screenshots of successful tests
```
to some file in /docs/ ?

Typo fix in phpdoc

---

src/Codeception/Module/Symfony.php

This should resolve #5058.
I did not modify nor test nor docs.
The test for this I could not find. The [contributing page](https://github.com/Codeception/Codeception/blob/2.4/CONTRIBUTING.md) says that docs are autogenerated from dockblocks.

Symfony test email count

---

CHANGELOG-2.4.md
autoload.php
src/Codeception/Configuration.php
tests/cli/ConfigExtendsCest.php
tests/data/config_extends/codeception.common.yml
tests/data/config_extends/codeception.yml
tests/data/config_extends/tests/_output/.gitignore
tests/data/config_extends/tests/_support/UnitTester.php
tests/data/config_extends/tests/_support/_generated/.gitignore
tests/data/config_extends/tests/unit.suite.common.yml
tests/data/config_extends/tests/unit.suite.yml
tests/data/config_extends/tests/unit/UnitCest.php
tests/unit/Codeception/ConfigurationTest.php

This pull requests adds support of absolute paths in `extends` property on configs and adds tests that the new feature works.

Allow absolute paths in `extends` property of configs

---

src/Codeception/Module/Laravel5.php

This PR changes the `Laravel5` module in order to use `assert()` rather than `fail()` to indicate if something worked / did not work..
Note that this PR is "work in progress"..

[WIP] Start using assert() and not fail()

---

docs/modules/Db.md
src/Codeception/Lib/Driver/Db.php
src/Codeception/Lib/Driver/Oci.php
src/Codeception/Module/Db.php

(and Oracle implementation)
The point here is to avoid false negative test error-failures that might occur due to database object locks.  In particular, I'm seeing occasional `ORA-00054: resource busy and acquire with NOWAIT specified or timeout expired` occurrences during the before-test dump-populate step, when running a `--group failed` follow-up execution after a previous execution recorded errors.
In my case, I'm hoping having a 10-30sec lock wait (rather than the default no-wait of 0) might avoid these `ORA-00054`s.

add config option for session lock wait setting

---

src/Codeception/Module/WebDriver.php
tests/data/app/view/form/anchor.php
tests/web/WebDriverTest.php

Make it possible to click on a input by title. For example when you have a form input with only a font icon.
```
<input type="submit" class="btn btn-success" value="&#xf011;" title="Login" />
```
<a class="jsbin-embed" href="http://jsbin.com/bevotayuga/1/embed?html,css,output">JS Bin on jsbin.com</a>

match title in input fields

---

src/Codeception/Module/REST.php
tests/unit/Codeception/Module/RestTest.php

Simple fix I think. I'm 99.9% sure this was a typo when the phpunit wrapper was added.

Fixes a missing _ for _getResponseContent() in seeXmlResponseEquals

---

src/Codeception/Codecept.php
src/Codeception/Subscriber/Dependencies.php
src/Codeception/Suite.php
src/Codeception/Test/Cept.php
src/Codeception/Test/Cest.php
src/Codeception/Test/Interfaces/Dependent.php
src/Codeception/Test/Unit.php
tests/data/claypit/composer.lock

Replaces #5097 
We have our own methods for dependencies collection so it's easier to rename ours than maintain compatibility with constantly changing PHPUnit signatures.

fixed compat with phpunit 7.2

---

src/Codeception/Test/Descriptor.php

is_callable() cannot be used if $testCase implements __call().
instanceof TestInterface should be the correct check,

Fixes https://github.com/Codeception/Codeception/issues/4913

---

src/Codeception/Module/Yii2.php

There are some cases when `_after` method can be called without calling `_before`, that leads to null-pointer exception. For example, `_after` can be called from error handler during unhandled exception proceeding.

Prevent NPE in Yii2 module

---

src/Codeception/Module/WebDriver.php

As same in saveSessionSnapshot, at the moment of load the snapshot, I think we need to avoid the deletion of all cookies. we need to delete all of them except those related to COVERAGE.

[WebDriver] Keep coverage cookies in LoadSessionSnapshot

---

docs/12-ParallelExecution.md

The opt() methods should be option(), and there was a syntax error (`unexpected ;` on line 290).

Fix errors in parallelRun() codeblock (docs)

---

src/Codeception/Command/Run.php

It wasn't documented, so it doesn't appear in https://codeception.com/docs/reference/Commands
Closes #5129

[Docs] Documented no-rebuild option of run command

---

autoload.php

because PHP 5.4 is no longer supported.
PHP 5.5 and newer versions have native implementation.

[Autoload] Removed json_last_error_msg declaration

---

docs/11-Codecoverage.md
src/Codeception/Coverage/Subscriber/Printer.php

on init of 
`\SebastianBergmann\CodeCoverage\Report\Text` 
in 
`Codeception\Coverage\Subscriber\Printer`
Result is full BC and would result in a new coverage config option. So we can have for large projects a compact console output on CI/CD pipelines.
```
coverage:
enabled: true
low_limit: 30
high_limit: 60
show_uncovered: false
show_only_summary: true
```

make coverage 'show_only_summary' configurable

---

src/Codeception/Lib/Connector/Guzzle6.php
src/Codeception/Lib/Connector/Yii2.php
src/Codeception/Module/PhpBrowser.php
src/Codeception/Module/Yii2.php
tests/unit/Codeception/Module/PhpBrowserTest.php

This PR moves some of the implementations from the module to the connector.
The public interface of the module remains unchanged but internally more is handled by the connector.
This prevents unneeded loading of the application.

Yii2: Move implementations to connector

---

src/Codeception/Lib/Connector/Yii2.php

This fixes an issue when using a response with nonempty `$content` and an empty `$stream`.
This could be the cause of #5131 .

Fixed issue with empty response stream in Yii2

---

src/Codeception/Module/Phalcon.php

This PR introduces support for finding null fields when using `findRecord`. When you currently want to search for a record where a certain field has a null value it will fail.
Another things this PR fixes is the usage of bind parameters (introduced in #5158). This was giving a `Wrong number of parameters` exception because the properties were not wrapped in an array, so only the 'conditions' were passed into the `findFirst()` instead of an array containing both conditions and parameters.

Phalcon find null support

---

src/Codeception/Lib/ParamsLoader.php
tests/cli/ConfigParamsCest.php
tests/data/params/codeception_xml.yml
tests/data/params/params.xml

Added Symfony XML like parameter file support.
Example XML file:
```xml
<parameters>
<parameter key="KEY1" type="string">val1</parameter>
<parameter key="KEY2">val2</parameter>
<parameter key="KEY3" type="collection">
<parameter key="KEY4" type="string">false</parameter>
<parameter key="KEY5" type="bool">true</parameter>
<parameter key="KEY6" type="constant">PHP_VERSION</parameter>
</parameter>
</parameters>
```

Added symfony xml support for parameter files.

---

src/Codeception/Lib/InnerBrowser.php
tests/unit/Codeception/Module/TestsForWeb.php

The `contains` keyword in xpath matches also partial content.
The documentation states:
```php
$I->seeLink('Logout','/logout'); // matches <a href="/logout">Logout</a>
```
But now it also matches `<a href="/logout/foobar">Logout</a>`

seeLink: fix partial href matching

---

src/Codeception/Module/Db.php
src/Codeception/Module/WebDriver.php

When using namespaces in tests, and building the `*TesterActions` classes, PHPStan throws an error that it cannot find `<MyNamespace>\TestInterface` as well as `<MyNamespace>\actions`.
This fixes those issues.

Fixes PHPStan issue

---

docs/03-AcceptanceTests.md
docs/modules/AngularJS.md
docs/modules/Laravel5.md
docs/modules/Lumen.md
docs/modules/Phalcon.md
docs/modules/PhpBrowser.md
docs/modules/Silex.md
docs/modules/Symfony.md
docs/modules/WebDriver.md
docs/modules/Yii1.md
docs/modules/Yii2.md
docs/modules/ZF1.md
docs/modules/ZF2.md
docs/modules/ZendExpressive.md
src/Codeception/Lib/Interfaces/Web.php

The regex to match the root url is not correct.
`$` stands for end in regex
`^` is beginning in regex

correct regex to root url

---

src/Codeception/Module/WebDriver.php
tests/web/WebDriverTest.php

I needed a way to wait on a button to become clickable, and noticed that WebDriver already has a `WebDriverExpectedCondition::elementToBeClickable()` method available. Pretty easy win!
Fixes #5216.
Note: I was unable to get the `web` suite working, so I was unable to actually test this through `WebDriverTest`, but I actually built this into my own app before submitting here. It looks like that suite isn't running in TravisCI? I was hoping I'd be able to at least let CI tell me if I got it right.
I tried running this through the `docker-compose` steps in [the readme](https://github.com/Codeception/Codeception/blob/2.5/tests/README.md), but I'm unsure if docker automatically spins up chromedriver and the rest of the necessary steps. When I tried running `docker-compose run --rm codecept run …

Add waitForElementClickable

---

src/Codeception/Module/REST.php

Because config example wasn't rendered correctly
https://codeception.com/docs/modules/REST#amAWSAuthenticated

[REST] Updated docblock of amAWSAuthenticated

---

src/Codeception/Lib/ParamsLoader.php

Since version 4, Symfony the default app skeleton uses .yaml files

use param files .yaml like .yml

---

src/Codeception/Lib/Connector/Phalcon.php

The Phalcon Response class's content is null by default. If you use $response->redirect, the content stays null. When using functional testing, the null causes an error due to typehint requirements. This fixes that issue.

Accounting For Null Content In Phalcon Response Object (IE: Redirect)

---

src/Codeception/SuiteManager.php

I noticed that the 'Command Did Not Finish Properly' feature I added previously was having adverse effects when an exception was thrown in the beforeSuite or afterSuite methods of a module. This was occurring even though the exception occurred. In my mind, an Exception should disable the Command Did Not Finish  Properly as it is to be handled by the normal error trapping. I've wrapped the Suite Event that fires the tests and the after-tests with a try/finally so that the after suite will still get called if an exception occurs. This will prevent the display of the original exception as well as the following 'Command Did Not Finish Properly'

Adding Finally To Ensure Suite After Always Runs, Even If Exception

---

src/Codeception/Module/Lumen.php

Added Lumen 5.5+ (5.3+ backward compatible) support for getRoutes method in Lumen module.
On Lumen 5.5+ do a breaking change on commit https://github.com/laravel/lumen-framework/commit/7018d57d684e7e63bcef9576bc718e9ad75feb0c
This change generate a fatal error on method $this->amOnRoute('simple-route');
```bash
[Error] Call to undefined method Laravel\Lumen\Application::getRoutes()
```

Lumen 5.5+ (5.3+ backward compatible) support for getRoutes method

---

docs/11-Codecoverage.md
src/Codeception/Coverage/Subscriber/LocalServer.php
src/Codeception/Coverage/SuiteSubscriber.php
tests/coverage/LocalWithWorkDirCept.php
tests/data/claypit/tests/remote_server.suite.yml
tests/support/CliHelper.php

This PR adds the ability to use coverage locally when utilizing docker or other forms of mounted/shared directories. It otherwise gives you the ability to run coverage without having to resort to remote coverage, provided you can use some form of shared mount when testing.
I use docker for most of my stuff. This includes both on my local computer and for my GitLab Pipelines (CI). When running coverage, if you are using docker, you have no choice but to set coverage up as a remote server. This of course means you will not get merged coverage. The only way you can use local coverage with a docker setup is to either run codeception through a docker container (And map everything to be the same paths) or to update the working directories of docker to be the same locally and within the …

Adding Ability To Translate Remote Paths To Local (IE: Docker)

---

ext/Recorder.php

See https://github.com/Codeception/Codeception/pull/5221#issuecomment-430548993
Parent issue: #5177

Failing gracefully if webDriver is not hydrated in Recorder extension

---

docs/modules/Phalcon.md
src/Codeception/Module/Phalcon.php

The Phalcon Module uses the supplied MemorySession class for the session object. The problem I've found with this is that I tend to extend session and add helper methods to the extensions. These end up breaking in testing because the methods aren't there. To get around this, I have to add extra module code to override the session after init.
This PR adds a new config to the module to allow setting the class name to use for the session. It also updates it so that Phalcon users can use the built in service override of Phalcon's DIC.

Updating Phalcon Module To Be Able To Override MemorySession Class

---

src/Codeception/Module/Doctrine2.php

This fixes tests in which other transactions are created but not closed for various reasons.

Rollback all nested transactions created within test (#5107)

---

tests/data/rest/index.php
tests/unit/Codeception/Module/PhpBrowserRestTest.php

Symfony/browser-kit now makes requests to host specified in Host header
So it is no longer possible to test Host header by making requests to localhost

Fixed broken tests

---

src/Codeception/Module/Db.php
tests/data/snapshots/tests/_support/_generated/DataTesterActions.php
tests/unit/Codeception/Module/Db/TestsForDb.php

I noticed that undocumented method `isPopulated` appears in [documentation](https://codeception.com/docs/modules/Db#isPopulated), but the only reason why it is public is that it is used in Codeception tests.
So I'm hiding it by renaming it to `_isPopulated`.

[Db] hide isPopulated method

---

appveyor.yml
codecept.bat

I simplified the `codecept.bat` file and removed `@var_name@` variables. The `@var_name@` vars should be replaced during a PHAR build. I think that `@var_name@` vars are not universal, and I am also not sure that they make sense (or even used) right now.
It's using `%PHP_PEAR_PHP_BIN%` because that's a global variable which may be set by PEAR. I just figure, if it's available anyway, why not use it; and in the other case, it will just try php, assuming most Windows users will have added that to their `PATH`.
These changes should be covered by ` appveyor.yml:test_script` (I hope).

Correct Windows entrypoint (codecept.bat)

---

docs/06-ModulesAndHelpers.md

Small fix - remove redundant word from docs

Small fix - remove redundant word from docs

---

src/Codeception/Test/Loader/Cest.php
tests/data/SimpleWithDataProviderArrayCest.php
tests/data/SimpleWithDataProviderYieldGeneratorCest.php
tests/unit/Codeception/TestLoaderTest.php

Some days ago I wanted to write a data provider for test examples using `yield` instead of returning an array directly. This way the data provider method returns a `Generator`. Sadly this resulted in an exception:
```[PHPUnit\Framework\Exception] array_merge(): Argument #2 is not an array```
I'd really like Codeception to be able to work with `yield` in data providers, too, so I took some time to look into it. Basically I added a check if what we get from the data provider method is a Traversable (e.g. a Generator) and if so, convert it to a plain old array which in turn works with the `array_merge`. Additionally I added some tests for this, too.
I'm not sure if this is the 'correct' way like I implemented the tests. I just looked at the existing tests and tried to adopt what was already …

Make @dataProvider work with yield/generators

---

src/Codeception/Module/Doctrine2.php

After last release the cleanup property on Doctrine2 module is not working when you try to reconfigure the module.

[Doctrine2] Making cleanup property work after on reconfigure

---

src/Codeception/Step.php
tests/unit/Codeception/StepTest.php

@DavertMik Are you able to have a look at this and review? I understand @SamMousa suggested removing `__mocked` property but not sure if that's would be an "easy fix", so just checking if class is implementing `PHPUnit\Framework\MockObject\MockObject` interface.
Closes #5163

Bugfix issue #5163

---

src/Codeception/Module/Db.php

Previously only the presence of SQL counted:
https://github.com/Codeception/Codeception/blob/5fee32d5c82791548931cbc34806b4de6aa1abfc/src/Codeception/Module/Db.php#L405-L408
The code edited in https://github.com/Codeception/Codeception/pull/5140 forgot that SQL can also be completely absent

Db: don't clear database for empty dump

---

src/Codeception/Lib/Connector/Symfony.php

I have an issue. When i work with DataFactory and Doctrine2 modules, and when my testing services uses EntityManager - the instances of entity managers are different. Therefore DataFactory EntityManager knows about created entities through have() method. But my EntityManager is not. Also Doctrine2 cleanup service is not working, because all of them (DataFactory, Doctrine2, my service) use different connections and transactions. Because of this i have alot of bugs during testing.
I have investigated the issue. The reason is - codeception Symfony module rebooted the kernel and on first request services that was in kernel's container are lost. But this kernel's container still uses for App services.
There is code for persistent services, but, this is not works for first request. Because of …

Fix "already initialized service", "reboot kernel issue"

---

src/Codeception/Lib/Connector/ZendExpressive.php
src/Codeception/Module/ZendExpressive.php

While testing my new Zend Expressive project, I experienced a few issues where execution of one test affected result of another.
I quickly discovered that it happens because the same Application and Container are used in all tests.
Clearing container looks like complicated and dirty task, especially because Zend Expressive support multiple DI containers.
Creating new Container and Application is much easier solution.
In order to avoid breaking existing tests, I kept old behaviour as a default and introduced 2 new options:
* recreateApplicationBetweenTests
* recreateApplicationBetweenRequests

[ZendExpressive] options to reload application between tests and requests

---

src/Codeception/Module/WebDriver.php

It will help to debug issues like #5193
Example of output:
```
- WebDriverTest: Am on subdomain
Curl error: Curl error thrown for http POST to /session with params: {"desiredCapabilities":{"browserName":"chrome"}}
Failed to connect to 127.0.0.1 port 4444: Connection refused
WebDriver::debugWebDriverLogs method has been called when webDriver is not set
WebDriver::_saveScreenshot method has been called when webDriver is not set
WebDriver::_savePageSource method has been called when webDriver is not set
Screenshot and page source were saved into '/c/Projects/Codeception/tests/log/' dir
E WebDriverTest: Am on subdomain
```

WebDriver: print curl error to debug output if webdriver failed to connect

---

src/Codeception/Util/ArrayContainsComparator.php
tests/unit/Codeception/Util/ArrayContainsComparatorTest.php

ArrayContainsComparator do not Intersect correctry Empty expected nested array

---

src/Codeception/Lib/Connector/ZendExpressive.php

Because `Dflydev\FigCookies\Cookies::fromRequest($request);` reads cookies from header.
Cookies can be retrieved using `$request->getCookieParams()`, but this change helps if someone makes the same mistake as I did.

[ZendExpressive] Set Cookie header in request

---

src/Codeception/Lib/Connector/Symfony.php

Improvement over #5262
This way persistent services keep working for Symfony 3 the way they worked before.
Exceptions thrown by Symfony 4 are caught and ignored.
Closes #5362

Fix persistent service for Symfony 3

---

src/Codeception/Lib/ParamsLoader.php

`vlucas/phpdotenv` is a `require-dev` dependency for Codeception, so it does not enforce constraint on projects that are using Codeception.
Fot this reason we must keep backwards compatility with `vlucas/phpdotenv` v2.
Fixes https://github.com/lucatume/wp-browser/issues/210
Fixes #5380

Restore compatility with vlucas/phpdotenv v2

---

docs/07-BDD.md
src/Codeception/Test/Loader/Gherkin.php

This PR will add the possibility to dynamically load context for Gherkin tests. When using the suggested method of adding contexts to your ```codeception.yml``` file. This soon will become a long list of context files and quite a pain to maintain. 
By adding the following line to configuration contexts will automatically be loaded:
```yaml
gherkin:
contexts:
path: tests/_support/Steps
namespace_prefix: Steps
default:
- AcceptanceTester
```
Unfortunately this cannot be solved via a Customer loader, because the GherkinSnippet class directly instantiates the Gherkin loader instead of the specified Gherkin loader. Something that could be fixed but with a lot more work.

Add possibility to dynamically load contexts

---

src/Codeception/Lib/Connector/Laravel5/ExceptionHandlerDecorator.php

shouldReport() declaration has been added to [Illuminate\Contracts\Debug\ExceptionHandler in Laravel 5.8](https://github.com/laravel/framework/blob/3949bd8bb9697e005ebf4ac3d8eacd6c190e6930/src/Illuminate/Contracts/Debug/ExceptionHandler.php#L23)

[Laravel] Fix missing declaration shouldReport

---

src/Codeception/Lib/Connector/Lumen.php

in version 5.6.*, lumen introduced the same design pattern to boot all services providers like Laravel.
The providers aren't booted until the request  is started
@see https://github.com/laravel/lumen-framework/commit/42cbc998375718b1a8a11883e033617024e57260
```php
<?php
use App\Example;
class ApiExampleCest
{
public function openPageByRoute(\ApiTester $I)
{
// exampleId = 1
$exampleId = Example::select('id')
->first()->id;
$I->amOnPage('/' . $exampleId);
$I->expect('one item is in response');
$I->seeResponseContains('Lumen (5.8.0) (Laravel Components 5.8.*)');
}
}
```
without Laravel\Lumen\Application::boot
```bash
$ ./vendor/bin/codecept run api
Api Tests (1) ------------------------------------------------------------------------------------
E ApiExampleCest: Open page by route (0.01s) …
```

[Lumen] add support for Laravel\Lumen\Application::boot

---

src/Codeception/Command/Build.php

Don't make any sense to run the `output->writeln` method before the `produce` method, cause `$actionsGenerator->getNumMethods()` will always return zero (`Action::$numMethods` property is not populated before running `Actions::produce()`).
I just changed the order of the execution, so you first generate the methods, and then you check for generated methods.

Fixing the bad build command message.

---

src/Codeception/Module/ZendExpressive.php

I set it to `false` in 2.5 to avoid breaking anyones tests when this functionality was introduced.

[ZendExpressive] recreateApplicationBetweenTests is on by default in 2.6

---

src/Codeception/Module/WebDriver.php

Workaround for bug #5401 to ensure cookie expiry value is not null which breaks in chromedriver 2.46
Sorry about the unrelated whitespace change.

Ensure cookie expiry value is not null

---

src/Codeception/Lib/GroupManager.php
tests/data/gherkinGroup1
tests/data/gherkinGroup2
tests/data/refund2.feature
tests/unit/Codeception/Lib/GroupManagerTest.php

A possible solution for the issue described in #5457. I have a couple of open questions though.
* I am not familiar with the Codeception framework. Is `Codeception\Lib\GroupManager` the best place to address this issue or is there a better place?
* I would like to write some tests to verify this issue. Can someone point me to a similar test to help me get started?
* My use of `strcasecmp` looks like it will fail for multibyte strings. Are there suggestions on better alternatives? One I saw (that I linked to in a comment in the code) suggests using `mb_strtolower` instead.
Any help, tips or advice would be appreciated. Thanks.

Proposed solution for #5457 gherkin scenarios not loaded from group file

---

src/Codeception/Module.php
src/Codeception/Module/REST.php

- add a new config `shortDebugResponse` to limit large API responses at CLI in REST module

[REST] Short API responses in debug mode

---

src/Codeception/Module/FTP.php

When switching to phpseclib version 2, all global constants were changed to class constants. This PR reflects that change as well.
Additionally, this PR updates the `$filepath` property in `FTP::_writeToFile()` to be the remote server's file path. This matches how `FTP::_openFile()` behaves.

Update phpseclib Constant

---

src/Codeception/Module/WebDriver.php

A cookie with ['name' => 'test', 'value' => 0] would get it's value stripped, causing an "undefined index: value" notice in php-webdriver's Cookie.php

Avoid removing required fields in cookies.

---

Dockerfile

Closes #5325
Docker image updated:
- updated php-cli to 7.3
- updated xdebug to 2.7.0RC2 (stable version rather than beta),
- added zip functionality so composer could install from dist rather than source
- added classmap-authoritative option to composer for extra performance
- added no-interaction option to composer as without .lock files we'll pull latest version matched by .json definition, therefore build can fail any time if there's an interactive update [which is rare, but happens]
As requested, this is the same change as https://github.com/Codeception/Codeception/pull/5412 , but this is branched from upstream 2.6.

Updating docker PHP version to 7.3

---

src/Codeception/Lib/Driver/SqlSrv.php

Because it has no meaningful differences from the same functionality in the parent class.
This removal allows to use more comparison operators in where condtions.
Closes #4988

[Db] Remove generateWhereClause method from SqlSrv

---

src/Codeception/Module/WebDriver.php
tests/web/WebDriverTest.php

It is a minor issue which could affect a handful of Codeception 2.5 users
Closes #5456

2.5 Fixed loadSessionSnapshot with php-webdriver 1.1.3

---

src/Codeception/Subscriber/ErrorHandler.php

Previously only E_ERROR was considered fatal, this change adds E_COMPILE_ERROR and E_CORE_ERROR to the list.
Replaces #5452
Provided example was caused by E_COMPILE_ERROR.
I haven't managed to reproduce the issue, all compile errors were handled by PHP to me,
but I didn't test exact case with Page objects.
This logic is consistent with DidNotFinish logic:
```php
if (!$this->suiteFinished && (
$error === null || !in_array($error['type'], [E_ERROR, E_COMPILE_ERROR, E_CORE_ERROR])
)) {
throw new \RuntimeException('Command Did Not Finish Properly');
```

ErrorHandler prints info about more fatal error types

---

src/Codeception/Module/WebDriver.php

Missing `'` in an example which break the style

Update WebDriver documentation - typo in example

---

tests/unit/Codeception/Util/StubTest.php

Unit tests for Stub refer to deprecated methods:
```
7x DEPRECATION: Stub::never is deprecated in favor of \Codeception\Stub\Expected::never
13x DEPRECATION: Stub::atLeastOnce is deprecated in favor of \Codeception\Stub\Expected::atLeastOnce
13x DEPRECATION: Stub::once is deprecated in favor of \Codeception\Stub\Expected::once
20x DEPRECATION: Stub::exactly is deprecated in favor of \Codeception\Stub\Expected::exactly
```
> :warning:  Deprecation messages are not displayed in the execution summary of `codecept run unit`, unless the execution is interrupted/terminated before completion.

Fix depracted methods in Stub unit tests

---

src/Codeception/Module/ZF2.php

Zf2.5+ is modular, can't always rely that the console package is installed.

Add check for console class before calling it

---

docs/06-ModulesAndHelpers.md

Add missing `%` around `DB_PASSWORD` example

fix: Correct env substitution in Db module example

---

src/Codeception/Module/REST.php
tests/unit/Codeception/Module/RestTest.php

Redo url parts concatenations the right way.
Moved forward slash prefixing out of the branch to the main level of the function as that would be more consistent behaviour between cases when config['url'] set and empty... though I would rather remove that slash prefixing altogether L583-L585.
This is redo of https://github.com/Codeception/Codeception/pull/5474

Test and do not add leading slash when there is one already #5473

---

src/Codeception/Subscriber/ErrorHandler.php

Let's hide this annoying message as this has no deal to Codeception users

hiding Symfony 4.3 deprecation warning

---

src/Codeception/Lib/InnerBrowser.php
tests/data/app/view/form/bug5547.php
tests/unit/Codeception/Module/PhpBrowserTest.php

InnerBrowser: selectOption can match by text when option has no value attribute

---

src/Codeception/Module/FTP.php

The `_directory()` method in `FTP` was missing its return statement, meaning all paths were being expanded from root, rather than the client's current working directory.

[FTP] Make sure _directory() will return its directory

---

src/Codeception/Module/Phalcon.php

This allows using column names like `from` or `left`
See: https://docs.phalconphp.com/3.4/en/db-phql#escaping-reserved-words

Phalcon ActiveRecord: escape all column names using []

---

src/Codeception/Lib/Driver/Sqlite.php

This patch will safely close sqlite connections even if PHP's Garbage Collection is holding a refrence to a PDO instance referencing the same database file.
We noticed this issue in a medium size Zend Expressive installation while executing multiple acceptance tests. The PHP garbage collection was not able to close/unset all PDO references until the whole PHP process closes... So every time the Sqlite cleanup was executed the file wasn't truncated correctly. Instead a already open connection in PHP's garbage collection was blocking any write operations and has reverted the truncation of the sqlite database every time.
To challenge such issue the most effective way was to execute `gc_collect_cycles()` right after the cleanup method of the Sqlite Driver. At this point the PHP garbage …

Fix sqlite connection close when holding reference in PHP's GC

---

docs/03-AcceptanceTests.md

See https://github.com/Codeception/Codeception/blob/3.0/src/Codeception/Lib/Actor/Shared/Retry.php:
"Interval will be doubled on each unsuccessful execution."

Fix doc for retry behaviour doubling wait interval

---

docs/12-ContinuousIntegration.md

The link went to '../master/..' instead of the last stable '../3.0/..'

Update .travis.yml link

---

src/Codeception/Lib/InnerBrowser.php

maxRedirects parameter can be read either from public getter (valid for current vendor/symfony/browser-kit/Client.php - 4.3.*@dev) or from private property via reflection (original unchanged behaviour)
Fixes #5576

maxRedirects parameter can be read from public getter

---

docs/12-ParallelExecution.md

In the text Firefox is mentioned whereas in the code sample below Chrome is used.

Fix: mismatch between text and code example

---

Dockerfile

PHP has now has new builds with buster bases.
Docker file has been changed to use those builds instead of stretch.
While I was in there, I also made a cheeky little xdebug update to latest.
This build has been tested with 2 bigger projects of mine, one is lower level (API), and the other is e2e (selenium) based.
Both seemed to be fine without any further changes.

Switching to buster php build

---

Dockerfile

Now that the buster based PHP images are the default, and now that the existing default tags have been switched to from stretch, It makes sense to relax the docker tag to major version only.

Relaxing docker php image tag version

---

composer.json

Move hoa/console to the middle of dependency list, because removing last dependency makes composer.json invalid.
Fixes #5604

Fix codeception/base

---

src/Codeception/Lib/GroupManager.php

Hi there, 
I was trying to add some groups to my suites but I encountered a weird case: some groups were unable to load tests, and some were able to do.
After some investigation, I found out that this case occurs :
- when you set your suite path to `.`
- when you define groups directly in your suite config file
🙈 no problem happens if you use annotation directly in your test files.
The binary does not run the tests.
```bash
application@356115a48d2a:/app$ php vendor/bin/codecept run -g api-package
Codeception PHP Testing Framework v3.0.0
Powered by PHPUnit 7.5.9 by Sebastian Bergmann and contributors.
Running with seed:
[Groups] api-package
Api Tests (0) ------------------------------------------------------------------------------------------------------------------------- …
```

Improve file path detection for groups

---

.travis.yml
src/Codeception/Lib/Connector/Yii2.php
src/Codeception/Module/Yii2.php

Yii2 module allows you to either
1. Preserve application state after a request was handled, the default behavior, useful for white box inspection
1. Or reset the whole application in between requests inside a single test, with `recreateApplication` set to true
While the first approach may be faster and opens the possibility to test internal state, I had impassable issues with third party libraries that don't get the developer proper ways to clear state and mimic real stateless multiple requests.
So I must use `recreateApplication` to get fast functional tests work, but as mentioned in https://github.com/Codeception/Codeception/pull/5173/files#r220501466 now this options is basically useless since session is close and thrown away if `recreateApplication` is enabled.
This PR aims to restore …

[Yii2] Allow to preserve session with recreateApplication enabled

---

RoboFile.php

buildPhar is a public method which can be used for building custom phar files
buildPhar7 is part of release process and builds phar file specifically for PHP 7.0.0
Example of usecase for custom phar file: #5620

Separate build:phar from build:phar7

---

composer.json

Which doesn't use shim file and supports only PHPUnit 6.5+
Fixes #5508

Support Stub 3.0

---

src/Codeception/Subscriber/ErrorHandler.php

Fix https://github.com/Codeception/Codeception/pull/5555
The original code was never called.

[Symfony] Fix symfony 4.3 deprecation removal

---

src/Codeception/Module/Asserts.php
src/Codeception/Util/Shared/Asserts.php
tests/unit/Codeception/Module/AssertsTest.php

* assertEqualsCanonicalizing
* assertNotEqualsCanonicalizing
* assertEqualsIgnoringCase
* assertNotEqualsIgnoringCase
* assertEqualsWithDelta
* assertNotEqualsWithDelta
Backported them to PHPUnit 5.7 - 6.5 too.

[Asserts] Added specialized assertEquals methods

---

shim.php
src/Codeception/Lib/Connector/Guzzle.php
src/Codeception/Lib/Connector/Laravel5.php
src/Codeception/Lib/Connector/Lumen.php
src/Codeception/Lib/Connector/Phalcon.php
src/Codeception/Lib/Connector/Symfony.php
src/Codeception/Lib/Connector/Universal.php
src/Codeception/Lib/Connector/Yii1.php
src/Codeception/Lib/Connector/Yii2.php
src/Codeception/Lib/Connector/ZF2.php
src/Codeception/Lib/Connector/ZendExpressive.php
src/Codeception/Lib/InnerBrowser.php
src/Codeception/Module/REST.php
src/Codeception/Module/SOAP.php

#5532
Preparation for Symfony 5, also removes deprecation message when Symfony 4.3 components are used.
HttpKernelBrowser alias must be set in module file because Symfony/HttpKernel package isn't loaded yet by the time shim.php runs because it isn't dependency of Codeception.

Use Symfony5 class names in connectors

---

src/Codeception/Util/ReflectionPropertyAccessor.php
tests/unit/Codeception/Module/Doctrine2Test.php

As pointed out [here](https://github.com/Codeception/Codeception/pull/5633#issuecomment-523851706) my PR seems to have broken `haveInRepository` in that it doesn't work with preconstructed entities anymore if their constructor has non-optional parameters and you don't provide those properties when calling `haveInRepository`. :man_facepalming: 
As I already offered a pretty simple solution in a commend as a suggestion [here](https://github.com/Codeception/Codeception/pull/5662#issuecomment-523906151) and said PR was rejected as too complex, I'm now offering my suggested (hopefully simple enough) solution along with a test as a PR :)

[Doctrine2] Bugfix: calling haveInRepository with preconstructed entity requires providing constructor parameters

---

src/Codeception/Module/Doctrine2.php
tests/data/doctrine2_entities/CircularRelations/A.php
tests/data/doctrine2_entities/CircularRelations/B.php
tests/data/doctrine2_entities/CircularRelations/C.php
tests/unit/Codeception/Module/Doctrine2Test.php

Fixes #5663.
Other than in #5664, I only fixed the debug message creation for entities with composite keys of entities in bidirectional ManyToOne relations.

[Doctrine2] Make debug message in haveInRepository support entities with composite keys of entities in bidirectional relations

---

src/Codeception/Module/Doctrine2.php

`grabFromRepository` returns the result of `getSingleScalarResult`, which according to the documentation returns `mixed`, but the PHPDoc currently says the return type is `array` which in most cases it isn't.
https://www.doctrine-project.org/api/orm/2.6/Doctrine/ORM/Query.html#method_getSingleScalarResult

[Doctrine2] Fix return type of grabFromRepository

---

src/Codeception/Lib/InnerBrowser.php

The `Content-Type` header [may contain a charset](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type#Syntax), which caused XML and JSON .fail files to have a .html extension.
Content-Type: application/json; charset=utf-8
Also changed that if a REST API outputs text/plain content, the .fail file gets the .txt extension.

Fix for file extension of .fail files

---

src/Codeception/Lib/InnerBrowser.php
tests/cli/RunCest.php
tests/data/claypit/tests/_support/AcceptanceTester.php
tests/data/claypit/tests/phpbrowser_html_report.suite.yml
tests/data/claypit/tests/phpbrowser_html_report/CodeceptionIssue5568Cest.php

Fixes #5568
Bug was introduced via https://github.com/Codeception/Codeception/commit/cca5463cdefd12120783bca94081496f02f226e9 for "Improved output for failed tests" or "Print artifacts on test failure"
Fix: In addition to saving the PhpBrowser as report 'response', also again save it as report 'html' (which is then picked up by HTML report generator in https://github.com/Codeception/phpunit-wrapper/blob/04a825f35706fce8be1c51bb975c20b450aa4571/src/ResultPrinter/HTML.php#L139-L150)
Add reproducer test case in RunCest based on new "phpbrowser_html_report" test suite

Fix missing HTML snapshots of failing PhpBrowser acceptance tests in HTML Report after update to v3.0.x 3.1 (#5568)

---

src/Codeception/Module/Symfony.php

As @ThomasLandauer  reported via https://github.com/Codeception/Codeception/issues/5073 quite some time ago, `grabService` seems to be somewhat broken for newer Symfony versions (>= 4.1 ?).
With Symfony 4.1 a special service container was added that can be accessed via `test.service_container` for testing purposes which also provides access to private services:
https://symfony.com/doc/current/testing.html#accessing-the-container
I also added a test to the symfony-demo project at https://github.com/Codeception/symfony-demo/compare/master...burned42:add_service_container_test and if this PR will get accepted then I'd also open a PR for that branch. 
I tried to let the CI run with these tests with:
* above mentioned branch: https://travis-ci.org/burned42/Codeception/builds/592171088
* branch …

[Symfony] Make grabService use the special test service container if available

---

docs/modules/Db.md
src/Codeception/Module/Db.php

fix grabFromDatabase description in docs

---

src/Codeception/Module/WebDriver.php

fixes #5696
Current result:
```
I load session snapshot "snapshot"
[Cookies] [{"name":"yp","value":"1571926489.ygu.1","path":"/","domain":"ya.ru","expiry":1569420892,"secure":true,"httpOnly":false},{"name":"yandex_gid","value":"177","path":"/","domain":"ya.ru","expiry":1569420892,"secure":true,"httpOnly":false},{"name":"zm","value":"m-white_yaru.css%3As3home-static_FSsLNuVhmDl3rxvbm-qvz0ZjVdk%3Al","path":"/","domain":"ya.ru","expiry":1569420892,"secure":true,"httpOnly":false},{"name":"mda","value":"0","path":"/","domain":"ya.ru","expiry":1569420892,"secure":true,"httpOnly":false},{"name":"yandexuid","value":"9868385691569334489","path":"/","domain":"ya.ru","expiry":1569420892,"secure":true,"httpOnly":false},{"name":"i","value":"QusP9QfwDnr5s5+Zvdp1lHzsPFy3jQFyJ81z2fdnVx6kVtKwrFroy450dp8iXl …
```

[Webdriver] fix cookies debug

---

src/Codeception/Coverage/Filter.php

coverage: do not fail when excluded directory not exists

---

src/Codeception/Configuration.php

Somehow I got the following error:
_Call to undefined function Codeception\codecept_is_path_absolute() in /project/tests/vendor/codeception/codeception/src/Codeception/Configuration.php:278_
This patch uses the PathResolver.

Use path resolver for bootstrap file detection

---

app.php
autoload.php
codecept
package/bin

Historically Codeception Application was initialized in 2 different places -
`codecept` file is the main entry point when Codeception is installed using composer,
`package/bin` replaces it in phar file.
The most signifficant difference between them is that `codecept` file starts with `#!/usr/bin/env php`.
Second difference is that `codecept` includes `autoload.php` itself, but phar stub includes `autoload.php` before `package/bin`. It seems like accidental difference.
Over the time some differences accumulates by accident - phar file missed custom commands and shell auto-completion.
To avoid such accidents in the future, I moved Application initialization to `app.php` and included in from both places.
In the future, phar file will be able to include `app.php` directly instead of including …

Initialize Codeception application in a single place

---

.travis.yml
appveyor.yml
composer.json

They must be very loose and have stability set to dev
because they are circular dependencies and stricter rules would make branch builds of those modules fail.
If we need to add some restrictions in the future, they must be added as conflicts

Declare module dependencies in require-dev

---

src/Codeception/Lib/Actor/Shared/Pause.php
src/Codeception/Lib/Console/ReplHistory.php
tests/unit/Codeception/Lib/Console/ReplHistoryTest.php

It's currently very cumbersome to retrieve successful commands performed in Interactive Mode. You often have to copy and paste commands line by line, and the commands do not have a trailing semi-colon.
This PR improves the interactive shell by adding 4 new keyboard shortcuts to allow the user to quickly stash and unstash the last run command.
1. Pressing F5 stashes the last run command.
2. Pressing F8 displays all the stashed commands with trailing semi-colons, so that it can be quickly pasted back into your IDE.
3. Pressing F10 clears the stashed commands.
4. Pressing F6 toggles 'auto-stashing', which will automatically stash a command if it successfully executes.
The following screenshot illustrates how it works:
I have not written any test cases for this because I'm not sure about to …

New Feature: Add ability to stash/unstash commands in interactive mode.

---

src/Codeception/Event/DispatcherWrapper.php

Previous detector used class from symfony/event-dispatcher-contracts
so it wasn't precise enough.
TraceableEventDispatcherInterface was a part of event-dispatcher,
so it is more accurate
Fixes Codeception/Codeception#5796

Improved detection of event-dispatcher version

---

src/Codeception/InitTemplate.php
src/Codeception/Template/Api.php
src/Codeception/Template/Bootstrap.php

Fixes `bootstrap` and `init` commands.
They are failing to create actors after installing modules, because modules are not autoloadable.
Fixes issue reported in #5806

Template fixes

---

ext/Recorder.php

When you have special chars in your scenario titles the recorder can't create the directory.
example `Scenario: Simple Login/Logout`

fix recorder filename with special chars

---

autoload.php
src/Codeception/Command/Build.php

Description
-----------
When hosting composer dependencies outside of the standard vendor directory (similar to https://github.com/Codeception/Codeception/issues/5495) I have been getting the following error when running the build command:
```
dev/dependencies/vendor/bin/codecept build -c dev/tests/codeception
==== Redirecting to Composer-installed version in vendor/codeception. You can skip this using --no-redirect ====
Building Actor classes for suites: acceptance, api
-> AcceptanceTesterActions.php generated successfully. 110 methods added
\AcceptanceTester includes modules: WebDriver, Db, Percy, \Helper\Acceptance
In ModuleContainer.php line 110:
Module REST is not installed.
Use Composer to install corresponding package:
composer require codeception/module-rest --dev
```
This is of …

Add input definition for --no-redirect in build command

---

src/Codeception/InitTemplate.php

Details on issue #5868.
Check if the composer.json have a [vendor_dir](https://getcomposer.org/doc/06-config.md#vendor-dir) and then use this path on the method updateComposerClassMap of the class InitTemplate, used on the `codecept bootstrap`.

Check the composer option config.vendor_dir when updating composer

---

src/Codeception/Lib/Generator/Actions.php

The idea is that if the module specifies a return type hint, we generate actions that also have this hint. This way there are proper code completion and type checks in IDEs.
E.g.:
```php
<?php declare(strict_types=1);
namespace Foo\Bar;
use Codeception\Module;
class CustomModule extends Module {
public function haveCustomModuleAction(): \DateTimeInterface {
return new \DateTimeImmutable();
}
}
```
```yaml
#foo.suite.yml
class_name: FooTester
modules:
enabled:
- \Foo\Bar\CustomModule
```
```php
<?php declare(strict_types=1);
class FooCest {
public function foo(FooTester $I) {
$I->haveCustomModuleAction()->format(DATE_ATOM);
}
}
```

Added return type hint to the generated actions above PHP 7.0

---

src/Codeception/Configuration.php

Closes https://github.com/Codeception/Codeception/issues/5817
This change prevents an issue where the config array gets duplicated every time the mergeConfigs array is called causing the array to balloon in size in memory and the test suite to slow down as it progresses.
Original issue raised by and fix suggested by @tweber68

Prevent merged config array ballooning in memory

---

src/Codeception/Lib/Generator/Actions.php

Fixes #5877 
When Codeception generates a method action for a method which returns a `void` type, the method still uses the `return` keyword causing a PHP error:
```
Fatal error:  A void function must not return a value
```
This PR makes the `return` keyword variable, so that when we're dealing with a method which has a return type of `void`, we don't use the `return` keyword at all.

Ensure that the return keyword is not used when method returns void type

---

src/Codeception/Lib/Generator/Actions.php

Build: Use non-deprecated method to get return type hint

---

src/Codeception/Test/Feature/AssertionCounter.php

I've been missing this functionality, since I'm using mockery for mocks, and I'd like to be able to include the expectations as assertions in the count.
For the PHPUnit (see link: https://github.com/sebastianbergmann/phpunit/blob/master/src/Framework/TestCase.php#L1309) project, there is this function on the test cases.
For a Cest I had to do the following in an extension 
```php
<?php
//...
if ($container = Mockery::getContainer()) {
$expectationCount = $container->mockery_getExpectationCount();
Mockery::close();
if ($test instanceof Cest) {
// This is... beyond whacky-hacky
$accessor = new ReflectionPropertyAccessor();
$numAssertionsOnClass = $accessor->getProperty($test, 'numAssertions');
$accessor->setProperties($test, ['numAssertions' => $numAssertionsOnClass + $expectationCount]);
} …
```

Add the function addToAssertionCount to the Assertion trait

---

readme.md

Update the copyright date below `License` section, since it was somehow stuck in 2019 😮

Bump README copyright date to 2020

---

autoload.php

This follows on from https://github.com/Codeception/Codeception/pull/5857
I can properly build my suite with `--no-redirect` but I cannot run them without an error
Build ✅
```
$ dev/dependencies/vendor/bin/codecept build -c dev/tests/codeception --no-redirect
Building Actor classes for suites: acceptance
-> AcceptanceTesterActions.php generated successfully. 121 methods added
\AcceptanceTester includes modules: WebDriver, Db, Redis, Percy, \Helper\Acceptance
```
Run ⚠️
```
$ dev/dependencies/vendor/bin/codecept run acceptance --no-redirect --fail-fast -c dev/tests/codeception/ --env chrome-desktop -vvv
PHP Notice:  Undefined offset: 3 in /Users/lukerodgers/src/project/dev/dependencies/vendor/codeception/codeception/src/Codeception/Application.php on line 156
PHP Stack trace:
PHP   1. …
```

Update autoload.php to support --no-redirect

---

Dockerfile

This PR follows the discussion at https://github.com/Codeception/Codeception/issues/5969
It just adds `mysqli` php extension by default in the docker image, specifically with the goal to enable it to support tesing WordPress application out of the box.
/cc @schmunk42

Add `mysqli` php extension to docker image

---

ext/RunFailed.php

Correct path was used at the bottom of docblock, but this line at the top is misleading.
This docblock is used to generate https://codeception.com/extensions#RunFailed page.

RunFailed: fix path to file in the docblock

---

src/Codeception/Configuration.php

Use `codecept_is_path_absolute` function, which supports windows `C:\` style paths instead of using unix-specific condition.
Fixes https://github.com/infection/infection/issues/1296
I haven't had time to test it yet.

Support absolute output dir path on Windows

---

src/Codeception/Coverage/Subscriber/LocalServer.php

Might have something to do with https://github.com/Codeception/Codeception/issues/5989
But for us running it locally never works and fails with
This solves it.

Switch off c3Request call if 'remote' set to false

---

src/Codeception/Test/Gherkin.php
tests/cli/GherkinCest.php
tests/data/claypit/tests/_support/ScenarioGuy.php
tests/data/claypit/tests/scenario/AmbiguousStep.feature

This fixes #5864
I've decided to hook into the existing step validation code and not throw an exception but use the already present behavior of marking a step as incomplete.

Fail on ambiguous step definition

---

src/Codeception/Codecept.php
src/Codeception/Configuration.php
tests/cli/RunEnvironmentCest.php
tests/data/claypit/tests/_envs/envLayer1.yml
tests/data/claypit/tests/_envs/envLayer2.yml
tests/data/claypit/tests/messages.suite.yml

* The logic was flawed because it prevented environments to modify the config subsequently if they where not complete.
* Only the last configured environment won and controlled the resulting configuration set. This should be fixed now.

Remove complicated merge logic for environment configurations.

---

ext/Logger.php

- `.log` extension is added to suite log files
-  create logger with a full test name in the `beforeTest`

More practical ext logger

---

.travis.yml
composer.json
src/Codeception/Lib/Di.php
src/Codeception/Lib/Parser.php
src/Codeception/Step/Retry.php
src/Codeception/Util/ReflectionHelper.php
tests/unit/Codeception/Lib/DiTest.php

unit and cli test suites passed with PHP 8.0.0rc1 on my computer.
There is no PHP 8.0 on Travis yet.
Changes:
* Updated namespace parser in Codeception\Lib\Parser.
* Replaced deprecated ReflectionParameter::getClass() with workaroud.
* Removed default value of 2nd parameter (out of 4th) in Codeception\Step\Retry.
* DiTest::testFailDependenciesNonExistent matches different message on PHP 8.
TODO:
* Test all modules with PHP 8.0 and update version contraint in composer.json
Closes #5993

PHP 8.0 compatibility

---

src/Codeception/Util/ReflectionHelper.php
tests/unit/Codeception/Util/ReflectionHelperTest.php
tests/unit/Codeception/Util/ReflectionTestClass.php
tests/unit/Codeception/Util/ReflectionTestClass56.php
tests/unit/Codeception/Util/ReflectionTestClass70.php

A recent fix for #5987 added support for action parameter defaults, primarily used for generating actor traits from what I see.
This PR makes sure `ReflectionHelper::getDefaultValue()` returns fully qualified names for class constant defaults referencing "self".
In addition, it adds unit tests and makes sure empty defaults have the same type as the parameter they belong to if null is not allowed (even though that may not cause issues just yet).
*Note: This was developed & tested using PHP 7.4.3 while >=5.6.0 is supported according to composer.json (true?). Minor changes might be needed for full compatibility. Travis CI should report potential issues.*
**Our test suite broke completely after upgrading Codeception from  v4.1.8 to v4.1.9 - likely to be the case for other users as well, so …

BUG FIX: Use fully qualified name for class constant defaults

---

src/Codeception/Util/ReflectionHelper.php
tests/unit/Codeception/Util/ReflectionHelperTest.php
tests/unit/Codeception/Util/ReflectionTestClass56.php
tests/unit/Codeception/Util/ReflectionTestClass70.php

Need to prepend a '\\' on imported class constants also, not just constants from the same class (which was already fixed by #6016).
Fixes the issue from #6024

Prepend backslash on class constant default values

---

src/Codeception/Util/ReflectionHelper.php
tests/unit/Codeception/Util/ReflectionHelperTest.php

Some of our tests have started failing with latest versions of Codeception because the DI code is trying to find an `int` class.﻿

Fix PHP types being treated as a classes

---

src/Codeception/Test/Loader/Gherkin.php

Allows to load methods from namespaced helper files when namespace has traling backslash,
e.g. `namespace: tests\` in https://github.com/Codeception/yii2-tests/blob/master/cases/closeConnections/codeception.yml
Fixes #6032

Gherkin Loader: Strip trailing backslash from namespace

---

src/Codeception/Util/Shared/Namespaces.php

When someone pass path as a class name, e.g. ./foo
Fixes #5818

Ignore . namespace in generators

---

src/Codeception/Lib/GroupManager.php

Makes it easier to understand missing file error:
Before: `GroupManager: File or directory /home/vagrant/my-project/tests/unit/SomeUnitTest.php does not exist `
After: `GroupManager: File or directory /home/vagrant/my-project/tests/unit/SomeUnitTest.php set in group failed does not exist`

GroupManager: Show which group contains missing file

---

src/Codeception/Command/Run.php

`Running with seed:` removed :white_check_mark:
Before | After
------------ | -------------
`Running with seed:` removed :white_check_mark:
Before | After
------------ | -------------
color added :white_check_mark:
Before | After
------------ | -------------

Update "running with seed" in the CLI report

---

src/Codeception/Lib/ModuleContainer.php
src/Codeception/Module.php
tests/unit/Codeception/Lib/ModuleContainerTest.php

had the problem that i wasn't able to connect to a module, which i included in the config. took quite a while to debug. it was a simple diff in the case `LockPick ` vs `Lockpick`
so i added some code to add a  suggestion which module could be meant to the error message. 
```
[ModuleException] Codeception\Module: Module \C33s\Codeception\Module\LockPick couldn't be connected 
```
vs
```
[ModuleException] Codeception\Module: Module \C33s\Codeception\Module\LockPick couldn't be connected (did you mean '\C33s\Codeception\Module\Lockpick'?)
```
have not adapted any tests yet, wanted to wait for comments if you would merge this before.

suggestion on missing modules

---

src/Codeception/Exception/ConditionalAssertionFailed.php
src/Codeception/Exception/ConfigurationException.php
src/Codeception/Exception/ContentNotFound.php
src/Codeception/Exception/ElementNotFound.php
src/Codeception/Exception/ExtensionException.php
src/Codeception/Exception/InjectionException.php
src/Codeception/Exception/MalformedLocatorException.php
src/Codeception/Exception/ModuleConfigException.php
src/Codeception/Exception/ModuleConflictException.php
src/Codeception/Exception/ModuleException.php
src/Codeception/Exception/ModuleRequireException.php
src/Codeception/Exception/ParseException.php
src/Codeception/Exception/RemoteException.php
src/Codeception/Exception/TestParseException.php
src/Codeception/Exception/TestRuntimeException.php

- Use strict types in `src/Codeception/Exception`.
- Add type hints to Exceptions.

[5.0] Update code standards in Exceptions

---

src/Codeception/Subscriber/Module.php
tests/unit/Codeception/Subscriber/ModuleTest.php

Run Module `after...` hooks in reverse order so a module can use it's dependencies in `after...`
Fixes #6061

ISSUE-6061: Run Module after.. and fail hooks in reverse order

---

src/Codeception/Command/Run.php
tests/cli/CodeceptionYmlInRandomDirCest.php
tests/data/codeception_yml_in_random_dir/random/subdir/codeception.yml
tests/data/codeception_yml_in_random_dir/tests/_bootstrap.php
tests/data/codeception_yml_in_random_dir/tests/_output/.gitignore
tests/data/codeception_yml_in_random_dir/tests/_support/UnitTester.php
tests/data/codeception_yml_in_random_dir/tests/_support/_generated/.gitignore
tests/data/codeception_yml_in_random_dir/tests/unit.suite.yml
tests/data/codeception_yml_in_random_dir/tests/unit/ExampleCest.php
tests/data/codeception_yml_in_random_dir/tests/unit/_bootstrap.php

Detect the suite from a test file or path relative to the current working directory.
This fixes the issue that the suite cant be detected when `codeception.yml` is in any subdirectory, and subsequently also fixes the issue when it's inside the tests directory, for which there was a single use case fix in place.

detect the suite from a test path relative to the current working dir

---

src/Codeception/Coverage/Filter.php
src/Codeception/Coverage/PhpCodeCoverageFactory.php
src/Codeception/Coverage/Subscriber/Local.php
src/Codeception/Coverage/Subscriber/LocalServer.php
src/Codeception/Coverage/Subscriber/Printer.php
src/Codeception/Coverage/Subscriber/RemoteServer.php
src/Codeception/Coverage/SuiteSubscriber.php
src/Codeception/Event/FailEvent.php
src/Codeception/Event/PrintResultEvent.php
src/Codeception/Event/StepEvent.php
src/Codeception/Event/SuiteEvent.php
src/Codeception/Event/TestEvent.php

- Use strict types in `src/Codeception/Coverage` and `src/Codeception/Event`.
- Add type hints to Coverage Subscribers and Events.
- Longer aliases for ambiguous class names.
- Fix naming in `src/Codeception/Coverage` and `src/Codeception/Event`.

Update code standards in Coverage and Event

---

src/Codeception/Subscriber/ErrorHandler.php
tests/unit/Codeception/Subscriber/ErrorHandlerTest.php

Fixes #6090
Codeception ErrorHandler wasn't very useful for investigating notices and warning, because it didn't show where the warning happened.
```
In ErrorHandler.php line 83:
[PHPUnit\Framework\Exception (8)]  
Undefined variable: file           
Exception trace:
at /var/www/p2pr/vendor/codeception/codeception/src/Codeception/Subscriber/ErrorHandler.php:83
Codeception\Subscriber\ErrorHandler->errorHandler() at /var/www/p2pr/vendor/codeception/module-symfony/
```
After applying this change, error message will tell the file and line of code where the warning originated.
```
[PHPUnit\Framework\Exception] Undefined variable: a at tests/unit/Codeception/Subscriber/ErrorHandlerTest.php:29
```

Show origin of warning in error message

---

src/Codeception/Util/ActionSequence.php
src/Codeception/Util/Annotation.php
src/Codeception/Util/ArrayContainsComparator.php
src/Codeception/Util/Autoload.php
src/Codeception/Util/Debug.php
src/Codeception/Util/FileSystem.php
src/Codeception/Util/Fixtures.php
src/Codeception/Util/Locator.php
src/Codeception/Util/Maybe.php
src/Codeception/Util/PathResolver.php
src/Codeception/Util/ReflectionHelper.php
src/Codeception/Util/ReflectionPropertyAccessor.php
src/Codeception/Util/Shared/Namespaces.php
src/Codeception/Util/Soap.php
src/Codeception/Util/Template.php
src/Codeception/Util/Uri.php
src/Codeception/Util/Xml.php
src/Codeception/Util/XmlBuilder.php
src/Codeception/Util/XmlStructure.php
tests/unit/Codeception/Util/MockAutoload.php

- Use strict types in `src/Codeception/Util`.
- Add some type hints to Utils.
- Fix naming in `src/Codeception/Util`.

Update code standards in Utils

---

src/Codeception/Lib/GroupManager.php

* Fix GroupManager::normalizeFilePath changes with GroupManager::checkIfFileExists argument change in 0e110ef96 (merged in v4.1.15). A line was missed in the change and caused errors.
* Fix #6099

Fix GroupManager::normalizeFilePath

---

src/Codeception/Command/Run.php
tests/cli/RunCest.php
tests/data/dir_matches_suite/codeception.yml
tests/data/dir_matches_suite/tests/_output/.gitignore
tests/data/dir_matches_suite/tests/_support/ApiTester.php
tests/data/dir_matches_suite/tests/_support/_generated/.gitignore
tests/data/dir_matches_suite/tests/api.suite.yml
tests/data/dir_matches_suite/tests/api/SuccessCest.php

Original purpose of this change was to make `codecept run api` work when there is `api/` directory in project root and api suite in tests.
I looked into related issues and made the following commands work too:
`codecept run tests`
`codecept run ^*LoginWithWrongPassword$`
`codecept run tests:^*LoginWithWrongPassword$`
`codecept run tests/:^*LoginWithWrongPassword$`
Closes #6103
Closes #5278

Fix `run suite` when suite name matches directory

---

src/Codeception/Step/Action.php
src/Codeception/Step/Argument/FormattedOutput.php
src/Codeception/Step/Argument/PasswordArgument.php
src/Codeception/Step/Assertion.php
src/Codeception/Step/Comment.php
src/Codeception/Step/Condition.php
src/Codeception/Step/ConditionalAssertion.php
src/Codeception/Step/Executor.php
src/Codeception/Step/GeneratedStep.php
src/Codeception/Step/Incomplete.php
src/Codeception/Step/Meta.php
src/Codeception/Step/Retry.php
src/Codeception/Step/Skip.php
src/Codeception/Step/TryTo.php

- Use strict types in `src/Codeception/Step`.
- Add some type hints to Steps.

Update code standards in Steps

---

src/Codeception/Coverage/Subscriber/Printer.php
src/Codeception/Coverage/SuiteSubscriber.php
src/Codeception/Subscriber/AutoRebuild.php
src/Codeception/Subscriber/BeforeAfterTest.php
src/Codeception/Subscriber/Bootstrap.php
src/Codeception/Subscriber/Console.php
src/Codeception/Subscriber/Dependencies.php
src/Codeception/Subscriber/ErrorHandler.php
src/Codeception/Subscriber/ExtensionLoader.php
src/Codeception/Subscriber/FailFast.php
src/Codeception/Subscriber/GracefulTermination.php
src/Codeception/Subscriber/Module.php
src/Codeception/Subscriber/PrepareTest.php
src/Codeception/Subscriber/Shared/StaticEvents.php
src/Codeception/Subscriber/Shared/StaticEventsTrait.php

Update code standards in Subscribers

---

src/Codeception/Event/FailEvent.php
src/Codeception/Test/Cept.php
src/Codeception/Test/Cest.php
src/Codeception/Test/Descriptor.php
src/Codeception/Test/Feature/AssertionCounter.php
src/Codeception/Test/Feature/CodeCoverage.php
src/Codeception/Test/Feature/ErrorLogger.php
src/Codeception/Test/Feature/IgnoreIfMetadataBlocked.php
src/Codeception/Test/Feature/MetadataCollector.php
src/Codeception/Test/Feature/ScenarioLoader.php
src/Codeception/Test/Gherkin.php
src/Codeception/Test/Interfaces/Dependent.php
src/Codeception/Test/Interfaces/Descriptive.php
src/Codeception/Test/Interfaces/Plain.php
src/Codeception/Test/Interfaces/Reported.php
src/Codeception/Test/Interfaces/ScenarioDriven.php
src/Codeception/Test/Loader.php
src/Codeception/Test/Loader/Cept.php
src/Codeception/Test/Loader/Cest.php
src/Codeception/Test/Loader/Gherkin.php
src/Codeception/Test/Loader/LoaderInterface.php
src/Codeception/Test/Loader/Unit.php
src/Codeception/Test/Metadata.php
src/Codeception/Test/Test.php
src/Codeception/Test/Unit.php
src/Codeception/Util/Annotation.php

Update code standards in src/Codeception/Test

---

ext/DotReporter.php
ext/Logger.php
ext/Recorder.php
ext/RunBefore.php
ext/RunFailed.php
ext/RunProcess.php
ext/SimpleReporter.php
src/Codeception/Extension.php

- Use strict types in `src/ext`.
- Add some type hints to Extensions.

Update code standards in Extensions

---

src/Codeception/Command/Clean.php
tests/cli/IncludedCest.php

I came across an issue with the clean command when [multiple applications](https://codeception.com/docs/08-Customization#one-runner-for-multiple-applications) are set up using the `include` property in the global `codeception.yml`.
**Content of `codeception.yml`** 
```yml
include:
- applications/*/
- plugins/*/
```
**Before the changes:**
```bash
Cleaning up output /var/www/html/tests/_output/...
Cleaning up output /var/www/html/tests/_output/...
Cleaning up output /var/www/html/plugins/someRandomPlugin/tests/_output/...
```
**After the changes:**
```bash
Cleaning up output /var/www/html/tests/_output/...
Cleaning up output /var/www/html/applications/someRandomApplication/tests/_output/...
Cleaning up output /var/www/html/plugins/someRandomPlugin/tests/_output/...
```
Let me know if that …

Fix the loading of project configuration before cleanup

---

.github/workflows/build.yml
src/Codeception/GroupObject.php
src/Codeception/Test/Cept.php
src/Codeception/Test/Gherkin.php
src/Codeception/Test/Test.php
tests/data/claypit/tests/_data/VerbosityLevelOutput.php

This issue was introduced by renaming some variables, $e is passed to hooks below.
It is impossible to test for this issue, because Codeception is self-testing and the test can't fail if all assertions are passing.
We could implement more robust test suite by moving some cli test to separate suite which is directly executed by PHPUnit, but it requires a lot of effort.

Don't suppress failed assertions

---

src/PHPUnit/ConsolePrinter.php
src/PHPUnit/Constraint/Crawler.php
src/PHPUnit/Constraint/CrawlerNot.php
src/PHPUnit/Constraint/JsonContains.php
src/PHPUnit/Constraint/JsonType.php
src/PHPUnit/Constraint/Page.php
src/PHPUnit/Constraint/WebDriver.php
src/PHPUnit/Constraint/WebDriverNot.php
src/PHPUnit/FilterTest.php
src/PHPUnit/Util/Log/JSON.php
src/PHPUnit/Util/Log/TAP.php

- Use strict types in `src/PHPUnit/ConsolePrinter`, `src/PHPUnit/Constraint`, `src/PHPUnit/FilterTest`, `src/PHPUnit/Util/Log`.
- Add some type hints to `src/PHPUnit`.

Update code standards to some src/PHPUnit classes

---

src/Codeception/Lib/Generator/Cest.php
src/Codeception/Lib/Generator/Test.php

Test and Cest generators generate namespace on the same line as opening tag.
e.g.
```php
<?php namespace foo;
```
This change changes it to
```php
<?php
namespace foo;
```

Add line break between opening tag and namespace in generated files

---

src/Codeception/Util/FileSystem.php
tests/cli/CleanCest.php
tests/cli/IncludedCest.php

Because they are often used in _output directories.
Relates to #6117

Clean: Do not delete .gitkeep files

---

src/Codeception/Lib/Generator/Actions.php
tests/cli/BuildCest.php

* Don't crash on union type in PHP 8
* Generate return union types
* Generate parameter typehints
* Fix tests, because they were running assertions agaist source file instead of generated file
Closes #6122

Action file generator improvements

---

src/Codeception/Command/DryRun.php
src/Codeception/Lib/GroupManager.php
src/Codeception/Subscriber/BeforeAfterTest.php

I accidently discovered that Codeception was using name of non-existant class in conditions.
PHPUnit_Framework_TestSuite_DataProvider class was renamed to PHPUnit\Framework\DataProviderTestSuite in PHPUnit 6.0.0, but Codeception code was updated to use PHPUnit\Framework\TestSuite\DataProvider in conditions.
2 things are obvious:
1. We have no tests covering these cases.
2. It hasn't caused any issues that are worth reporting.
Wouldn't it be better to delete the code in these blocks? It was dead for 5 years.

4.1 Use correct name of DataProviderTestSuite in conditions

---

src/Codeception/Command/DryRun.php
src/Codeception/Lib/GroupManager.php
src/Codeception/Subscriber/BeforeAfterTest.php
tests/cli/DryRunCest.php

These conditions used wrong class name since release of PHPUnit 6.0, so this code was is effectively dead for 4 years.
I fixed conditions in #6136 but now I think that it was a wrong way to handle this issue.
The only place where Codeception creates DataProviderTestSuite is in [Test\Loader\Cest](https://github.com/Codeception/Codeception/blob/4.1.18/src/Codeception/Test/Loader/Cest.php#L79) but dry-run command does not receive it.
I think that DataProviderTest Suite is handled well by [Test\Loader\Unit](https://github.com/Codeception/Codeception/blob/4.1.18/src/Codeception/Test/Loader/Unit.php#L63-L68) and [Codeception\SuiteManager](https://github.com/Codeception/Codeception/blob/4.1.18/src/Codeception/SuiteManager.php#L114-L119)

4.1 Remove dead DataProviderTestSuite code

---

src/Codeception/Suite.php

This error happened to me while working on another branch:
> $ ./codecept run tests/cli/ConfigNoActorCest.php:runSuitesWithoutActor
> Codeception PHP Testing Framework v5.0.0
> Powered by PHPUnit 10.0-g2bc4a059f by Sebastian Bergmann and contributors.
> [Seed] 820860849
> PHP Fatal error:  Uncaught TypeError: Codeception\Suite::findMatchedTest(): Return value must be of type PHPUnit\Framework\SelfDescribing, none returned in /.../Codeception/src/Codeception/Suite.php:72
> Stack trace:
> #0 /.../Codeception/src/Codeception/Suite.php(53): Codeception\Suite->findMatchedTest()
> #1 /.../Codeception/src/Codeception/Suite.php(27): Codeception\Suite->getDependencies()
> #2 /.../Codeception/src/Codeception/SuiteManager.php(120): Codeception\Suite->reorderDependencies()

Fix type error when there is no matching test

---

src/Codeception/Lib/Interfaces/Web.php

See https://github.com/Codeception/module-symfony/pull/124#issuecomment-800233544

Standardize "@example.com" as domain in documentation

---

src/Codeception/Command/GenerateCept.php

The Cept format has been deprecated some 4 years ago https://github.com/Codeception/Codeception/issues/3976 - so I think it's about time to start thinking about ways to actually remove it from the codebase :-)
I deleted the explanation in order to remove the commands from https://codeception.com/docs/reference/Commands.html

Deprecating `GenerateCept`

---

src/Codeception/Command/Run.php

See https://github.com/Codeception/Codeception/discussions/6081#discussioncomment-275698

Explaining `--debug` as alias for `-vv`

---

src/Codeception/Coverage/PhpCodeCoverageFactory.php
src/Codeception/Coverage/Subscriber/Local.php
src/Codeception/Coverage/SuiteSubscriber.php
src/Codeception/Test/Feature/CodeCoverage.php
src/Codeception/Test/Test.php
src/PHPUnit/Compatibility/PHPUnit10.php
src/PHPUnit/Compatibility/PHPUnit9.php
src/PHPUnit/NonFinal/JUnit.php
src/PHPUnit/ResultPrinter.php
src/PHPUnit/ResultPrinter/HTML.php
src/PHPUnit/ResultPrinter/Report.php
src/PHPUnit/ResultPrinter/UI.php
src/PHPUnit/Runner.php
tests/data/claypit/tests/_data/MyReportPrinter.php

Benefits of doing something like this:
- There is no need to comment the code.
- The compatibility logic is in one place, it is easy to know *where* it is used and *which* of them there are.
- With fewer literals out there and there, typos are less likely to occur.
I'm not sure if that namespace (`Codeception\PHPUnit\Compatibility`) was the best to place something like this, but that is subject to change.

Abstract PHPUnit compatibility logic

---

src/Codeception/Lib/Generator/Actions.php
tests/cli/BuildCest.php

Nullable fields syntax ( `?string`) was introduced in 7.1
Fixes #6153

Action generator: Don't generate nullable types for PHP 7.0

---

src/Codeception/Lib/Interfaces/Web.php

Sounds like a tongue twister ... ;-)
I was expecting this text to be in https://github.com/Codeception/lib-innerbrowser/blob/master/src/Codeception/Lib/InnerBrowser.php#L941 - while in fact it's even in another module! So, again, a link at each function to get to its source code would really be nice - see https://github.com/Codeception/Codeception/discussions/6063#discussioncomment-244542
(More precisely: If the documentation isn't where the function is, then *two* links)

Explaining how to uncheck a pre-checked checkbox

---

src/Codeception/Command/DryRun.php

Symfony/console 5.3 introduced negatable options, so `--no-ansi` option no longer exists.
It makes `dry-run` command fail with ` The "no-ansi" option does not exist.` error.
I fixed it by copying no-ansi logic from [run command](https://github.com/Codeception/Codeception/blob/4.1.20/src/Codeception/Command/Run.php#L303).

Make dry-run command compatible with symfony/console 5.3

---

src/Codeception/Util/Maybe.php

`$val` can also be an `array` or an `ArrayAccess` implementation.

Fix Maybe::value()

---

composer.json

This is required so that the latest commit on the main branch is always downloaded instead of the latest stable version.

Explicitly require lib-innerbrowser as a dev dependency

---

src/Codeception/Lib/Interfaces/ActiveRecord.php

`haveRecord` [returns](https://github.com/Codeception/module-laravel/blob/f32a941a06e57bb06d2e485da11b191f38bec659/src/Codeception/Module/Laravel.php#L908) an `int` or an Eloquent model in Laravel module, so it shouldn't be typed to `: void`.

Fix ActiveRecord::haveRecord

---

src/Codeception/Configuration.php

Addresses #6270.
I was looking for a URL shortener that I could use, but apparently all of the big ones require you to sign up for an account nowadays. I also wasn't sure if it would be accepted since I don't know if any of these services let you change the target URL after a short URL's created, so I figured I'd just put the full link in there.
At first I was going to compensate for the length by breaking it out onto a new line, but from what I can tell the package Codeception uses for CLI output already handles this if I'm not mistaken.
If that's not the case and/or a short URL would be better, let me know and I'll update it.

Replaces outdated short URL for the bootstrap config option

---

src/Codeception/Template/Api.php

Since REST module 1.4.1 it is possible to use `AsJson` suffix to send JSON requests:
```php
$user = $I->sendPostAsJson('user', ['id' => 1]);
codecept_debug($user['id'])
$I->assertEquals(1, $user['id'])
```

Added api step decoration

---

src/Codeception/Coverage/Filter.php
tests/unit/Codeception/Coverage/FilterTest.php

[Code Coverage documentation](https://codeception.com/docs/11-Codecoverage#Configuration) gives examples for file patters ending with `*`.
```yml
coverage:
enabled: true
include:
- app/*
exclude:
- app/cache/*
```
Recently [it was brought to my attention](https://stackoverflow.com/questions/69443881/include-exclude-files-for-remote-coverage-in-codeception) that such rule adds non-PHP files to code coverage report too.
I tested it myself and got feature files, yaml files and everything in tests/_output directory added to code coverage report.
So I made this simple patch to change `/*` to `/*.php`.
Alternatively users could use `- app/*.php` in their include list, but it is better to have sane defaults.
If someone thinks that this is a breaking change, it could be merged to 5.0 branch …

Code Coverage of PHP files only

---

src/Codeception/Codecept.php
src/Codeception/Command/Run.php
src/Codeception/Subscriber/FailFast.php
tests/cli/RunCest.php
tests/data/claypit/tests/unit/FailingTest.php
tests/data/claypit/tests/unit/MultipleFailingTest.php
tests/unit/Codeception/SuiteManagerTest.php

https://github.com/Codeception/Codeception/issues/6152
First time working with this code base. This appears to work, although ran into a few issues.
1. Not super happy about having to cache the suite object in order to potentially stop it later. Is there some form of a container present for a better way to access this?
2. Had to be a bit hacky around the failure tests. Ended out just making a separate test class/group for multiple failures.
3. I could not get 5 of the `RemoteWith...` tests to pass locally. However, I don't think this is related to my changes.
Aside that, let me know if any requested changes or bugs found. Intent was to keep this working with boolean values as well for `fail-fast`, in terms of the existing configuration files.
Not sure if this falls into the "merge into …

Added optional value to fail-fast option

---

readme.md

What's the benefit of having this info here that needs to be updated every year? (latest: @Arhell at https://github.com/Codeception/Codeception/pull/6282)
Also: What is https://codeception.com/credits about at all? Can we delete this? Anybody interested in the team will certainly find https://github.com/Codeception/Codeception/graphs/contributors ;-)
@DavertMik I know what you're probably saying ("marekting" :-) - so my question is: When was this page last updated? ;-)

Deleting copyright and "team" link

---

src/Codeception/Example.php

Fixes https://github.com/Codeception/Codeception/issues/6291

Fix E_DEPRECATED warnings in Example class on PHP 8.1

---

src/Codeception/Step.php
src/Codeception/Subscriber/Console.php

Closes https://github.com/Codeception/Codeception/issues/6259
* I followed the syntax of https://phpstan.org/user-guide/output-format#opening-file-in-an-editor even though we wouldn't need the second `%` here. (This is due to some phpstan internals, the code ultimately reads `\str_replace(['%file%', '%line%'], ...`).
But I'd say having an *identical* `editorUrl` syntax between Codeception and phpstan by far outweighs the "cost" of some unneeded `%` characters... ;-)
* `$line = 0;` is a fallback in case the trace iteration doesn't work out. I'm guessing that putting 1 for the line is better than leaving it empty.

Adding clickable `editorUrl` from `codeception.yml`

---

src/Codeception/Lib/GroupManager.php
tests/data/group_manager_test/group_chunk_1_1
tests/data/group_manager_test/group_chunk_1_2
tests/unit/Codeception/Lib/GroupManagerTest.php

Replaces #6300 
This fixes using group manager to import groups from files by wildcard pattern.
```
#insude codeception.yml
groups:
group_*: tests/_data/group_*
```
**Previous behavior**: `tests/_data/group_*` pattern found only files `group_1`, `group_2`, but NOT `group_awesome`, `group_1_1` etc.
This behavior was incorrect as it didn't match all from a wildcard and limited results to `group_\d+`
**Current behavior**: `tests/_data/group_*` pattern finds all group* files in directory: `group_1`, `group_1_1`, etc

Fixed wildcard matching of group files

---

src/Codeception/Command/Shared/FileSystem.php

Hi!
When you build suites in PHP 8.1, you have a message: 
```
vendor/bin/codecept build
Building Actor classes for suites: acceptance, functional, unit
-> AcceptanceTesterActions.php generated successfully. 71 methods added
Deprecated: file_put_contents(): Passing null to parameter #3 ($flags) of type int is deprecated in /var/www/core/vendor/codeception/codeception/src/Codeception/Command/Shared/FileSystem.php on line 51
```
This pull request fixed it. I changed the default value of flags in the method 'FileSystem::createFile()'.

Fix message about deprecated in build-stage

---

src/Codeception/Lib/Generator/Actions.php
tests/cli/BuildCest.php

Before this change, action generator generated `?mixed`.
Fixes #6317

Action generator: Handle mixed type correctly

---

composer.json
src/Codeception/Lib/ParamsLoader.php

* require-dev because `SimpleXMLElement` is used in tests
* suggest and check in `ParamsLoader` to print a friendly error when simplexml extension is not loaded

Handle missing simplexml extension in ParamsLoader

---

src/Codeception/Command/Bootstrap.php
src/Codeception/Command/Build.php
src/Codeception/Command/Clean.php
src/Codeception/Command/Completion.php
src/Codeception/Command/CompletionFallback.php
src/Codeception/Command/ConfigValidate.php
src/Codeception/Command/Console.php
src/Codeception/Command/DryRun.php
src/Codeception/Command/GenerateCest.php
src/Codeception/Command/GenerateEnvironment.php
src/Codeception/Command/GenerateFeature.php
src/Codeception/Command/GenerateGroup.php
src/Codeception/Command/GenerateHelper.php
src/Codeception/Command/GeneratePageObject.php
src/Codeception/Command/GenerateScenarios.php
src/Codeception/Command/GenerateSnapshot.php
src/Codeception/Command/GenerateStepObject.php
src/Codeception/Command/GenerateSuite.php
src/Codeception/Command/GenerateTest.php
src/Codeception/Command/GherkinSnippets.php
src/Codeception/Command/GherkinSteps.php
src/Codeception/Command/Init.php
src/Codeception/Command/Run.php
src/Codeception/Command/SelfUpdate.php

These constants were added in Symfony 5.1 and Codeception 5 allows 4.4 onwards.

Replace symfony console constants with integers

---

ext/RunProcess.php
src/Codeception/Extension.php
tests/data/claypit/tests/_support/SuiteExtension.php

Minor typed property and docblock fixes for the `Extension` and `RunProcess` extension classes.

[Codecept5] Updated types for Extension class properties

---

.github/workflows/build.yml

It will help to ensure that we didn't break compatibility with older versions of dependencies

CI: Prefer lowest versions of dependencies on PHP 8.0

---

composer.json
src/Codeception/Lib/ParamsLoader.php

I noticed that in contrast to the other ways to load params (php, yml, xml etc), when loading from `.env` files there is a side-effect that modifies the `$_ENV` and `$_SERVER` superglobals. While this is usually what you want in the most common use-case for `phpdotenv`, in this case it is a bit odd, as `.env` files are merely used as another input format to load and merge Codeception params. That it also messes around with the values read from the real environment is unexpected.
The piece if code I used to parse the `.env` file into an array is supported in both v4 and v5 of `phpdotenv`.
I based this on the 5.0 branch as it is a breaking change. I also created a bugfix PR for 4.x that fixes environment variables being overwritten but does not remove the side-effect (#6347).

Return params from env file without modifying superglobals

---

src/Codeception/Lib/Generator/Actions.php
tests/cli/BuildCest.php

Intersection types were introduced in PHP 8.1 - `Interface1 & Interface2`. See https://php.watch/versions/8.1/intersection-types for more information.
This change allows to use intersection types as action parameter and return type.
Also I fixed class names used in union and intersection types.
Before this change class names used union types were generated without leading backslash and were relating to `_generated` namespace.

4.1 Generate actions with intersection types

---

src/Codeception/Lib/Actor/Shared/Pause.php

This changes makes `self` and `$this` work as expected.
Fixes #6086

Execute interactive console in the scope of paused test class

---

functions.php
src/Codeception/Lib/Actor/Shared/Pause.php
src/Codeception/Lib/PauseShell.php
src/Codeception/Test/Unit.php
src/Codeception/Util/Debug.php

More pause options
* all shell settings moved to `Codecept\Lib\PauseShell`
* `codecept_pause()` function
* added `$this->pause()` for unit tests 
* all pause commands to receive `$vars` as array:
```php
codecept_pause(['user' => $user]);
$I->pause(['pageObject' => $pageObject]);
```
TODO: Documentation!

Improved shell usage

---

src/Codeception/Coverage/Filter.php

https://github.com/Codeception/Codeception/pull/6092 started to use `declare(strict_types=1)`.
`symfony/finder` does not return the file paths as string but as instance of `SplFileInfo`.
This leads to the following exception when using exclude lists containing wildcards:
```
> vendor/bin/codecept run api --colors --coverage coverage_api.cov
Codeception PHP Testing Framework v5.0.0-RC1 https://helpukrainewin.org/
Powered by PHPUnit 9.5.19 #StandWithUkraine
Fatal error: Uncaught TypeError: SebastianBergmann\CodeCoverage\Filter::excludeFile(): Argument #1 ($filename) must be of type string, Symfony\Component\Finder\SplFileInfo given, called in /builds/robot/base/robot-pub/vendor/codeception/codeception/src/Codeception/Coverage/Filter.php on line 95 and defined in …
```

Fix exclude list in coverage filter

---

src/Codeception/Lib/ParamsLoader.php

As suggested in https://github.com/Codeception/Codeception/pull/6393#discussion_r829284908
Could not think of a reasonable way to test this - PhpDotenv seems to always take priority

Populate $_ENV when loading .env with Symfony/DotEnv

---

src/Codeception/Codecept.php
src/Codeception/Command/Run.php
src/Codeception/Test/Loader.php
tests/cli/RunCest.php

Introduced `--shard` option to execute non-intersecting subsets of tests. This allows parallelizing tests for multiple agents. The use case is slow-running browser tests that might be executed on different machines. Using shards you can easily split tests by machines and execute them independently. This feature does not aggregate reports from agents, however this can be achieved with robo-paratest.
To split tests for 3 agents call a command per agent:
```
codecept run --shard 1/3
codecept run --shard 2/3
codecept run --shard 3/3
```
Also, as a side-effect, this PR adds `--filter` and `--grep` options which I got used to while working on CodeceptJS
P.S. Updated Parallel testing guide coming soon when this is merged

Added --shard, --grep, --filter options

---

src/Codeception/Configuration.php
src/Codeception/Util/Template.php
tests/cli/ConfigParamsCest.php
tests/data/params/params.yml
tests/data/params/tests/_support/ComplexTester.php
tests/data/params/tests/_support/Helper/Dummy.php
tests/data/params/tests/complex.suite.yml
tests/data/params/tests/complex/YamlCept.php
tests/data/params/tests/dummy.suite.yml
tests/data/params/tests/dummy/YamlCept.php

This change allows to use non-string values in parameterized configuration files.
Most importantly objects and arrays, but also integers, floats and booleans.
Because unquoted placeholder `%var%` is not a valid value in Yaml format, this change will replace quoted placeholders with unquoted values,   e.g .  `param: "%var%"` will be rendered as `param: false`
Fixes #6408 
Fixes #5223

Encode non-string parameters in configuration files

---

.github/workflows/build.yml

PHPUnit 10 will require PHP 8.1.
I will double the number of test builds to 4:
1. Latest stable versions of all dependencies on PHP 8.0
2. Latest stable versions of all dependencies on PHP 8.1
3. Lowest supported version of all dependencies on PHP 8.0
4. PHPUnit 10 on PHP 8.1

CI: Run tests against PHPUnit 10

---

src/Codeception/Coverage/SuiteSubscriber.php

We had a few feature requests to add some code coverage setting and a few attempts to add these settings to Codeception.
I reviewed configuration options of PHPCodeCoverage library and added 3 missing settings:
* strict_covers_annotation - marks test as risky if it has `@covers` annotation but executes some other code
* ignore_deprecated_code - doesn't collect code coverage for code having `@deprecated` annotation
* disable_code_coverage_ignore - ignores `@codeCoverageIgnore`, `@codeCoverageIgnoreStart` and `@codeCoverageIgnoreEnd` annotations
The only setting I left out is coverage_cache_directory, see https://github.com/sebastianbergmann/phpunit/blob/master/src/TextUI/TestRunner.php#L245-L277
Closes #6258
Replaces #5874 
Replaces #5922

Add more code coverage settings

---

src/Codeception/InitTemplate.php

I think the type declaration here is incorrect, which is causing commands like `codecept init acceptance` to break:
```
Fatal error: Uncaught TypeError: Codeception\InitTemplate::ask(): Argument #2 ($answer) must be of type array|bool|null, string given, called in vendor/codeception/codeception/src/Codeception/Template/Acceptance.php on line 86 and defined in vendor/codeception/codeception/src/Codeception/InitTemplate.php:100
Stack trace:
#0 vendor/codeception/codeception/src/Codeception/Template/Acceptance.php(86): Codeception\InitTemplate->ask('Where tests wil...', 'tests')
#1 vendor/codeception/codeception/src/Codeception/Command/Init.php(58): Codeception\Template\Acceptance->setup()
#2 vendor/symfony/console/Command/Command.php(298): …
```

Fix incorrect $answer type declaration in InitTemplate

---

src/Codeception/Codecept.php
src/Codeception/Configuration.php
src/Codeception/InitTemplate.php
src/Codeception/Lib/ModuleContainer.php
src/Codeception/Subscriber/Console.php
src/Codeception/Subscriber/Deprecation.php
src/Codeception/Subscriber/ExtensionLoader.php
src/Codeception/Test/Loader/Gherkin.php

`Configuration::mergeConfig` only deals with arrays now.
Added some `@param array<string, mixed>` annotations to pass phpstan level 6.

Use stricter types in Configuration

---

ext/DotReporter.php

Added proxy for the RESULT_PRINT_AFTER event, so the event handling is done in the configured StandardReporter.

Codeception 5.0: Fix for DotReporter result printer

---

tests/support/CoverGuy.php

Code coverage results are different on different versions of PHP so the test must be more flexible

Fix code coverage tests

---

ext/DotReporter.php
ext/SimpleReporter.php
src/Codeception/Subscriber/Console.php
tests/cli/ExtensionsCest.php

Follow up to  #6441
Before:
After:
I will investigate why it reports 0 assertions later.
cc: @Orchestrator404

Fix DotReporter output

---

src/Codeception/Attribute/After.php
src/Codeception/Attribute/Before.php
src/Codeception/Attribute/DataProvider.php
src/Codeception/Attribute/Depends.php
src/Codeception/Attribute/Env.php
src/Codeception/Attribute/Examples.php
src/Codeception/Attribute/Group.php
src/Codeception/Attribute/Incomplete.php
src/Codeception/Attribute/Skip.php
src/Codeception/Subscriber/ErrorHandler.php
src/Codeception/Test/Cest.php
src/Codeception/Test/Loader/Cest.php
src/Codeception/Test/Loader/Unit.php
src/Codeception/Test/Metadata.php
src/Codeception/Test/Unit.php
src/Codeception/Util/Annotation.php
tests/cli/RunCest.php
tests/cli/SnapshotCest.php
tests/data/claypit/tests/Attrs.suite.yml
tests/data/claypit/tests/Attrs/BasicScenarioCest.php
tests/data/claypit/tests/Attrs/BasicUnitTest.php
tests/data/claypit/tests/_support/AttrsTester.php
tests/data/claypit/tests/order/ParsedLoadedTest.php

Added attributes for Cest format (some of them also work for Test)
Usage example (updated):
```php
#[Incomplete]
#[Skip]
#[Group('ue1')]
#[Example([1, 1], [2, 2])]
#[Depends('test1')]
#[Before('test1')]
#[Before('test2')]
public function myTest($I) 
{
}
```

Added basic attributes support

---

src/Codeception/Events.php
src/Codeception/Subscriber/Console.php
tests/cli/IncludedCest.php
tests/cli/RunUselessTestsCest.php
tests/data/useless/codeception.yml
tests/data/useless/tests/_output/.gitignore
tests/data/useless/tests/_support/UnitTester.php
tests/data/useless/tests/_support/_generated/.gitignore
tests/data/useless/tests/unit.suite.yml
tests/data/useless/tests/unit/UselessCept.php
tests/data/useless/tests/unit/UselessCest.php
tests/data/useless/tests/unit/UselessTest.php

Only unit tests are supported
Status U is printed in standard output
Depends on https://github.com/Codeception/phpunit-wrapper/pull/100
Before:
After:
Linked pull request will fix printing test summary for `--report` too:

4.2  Backport test.useless event from Codeception 5.0

---

src/Codeception/Configuration.php
src/Codeception/Subscriber/ErrorHandler.php
tests/cli/ErrorExpectationsCest.php
tests/data/error_handling/codeception.yml
tests/data/error_handling/tests/unit/ErrorExceptionTest.php
tests/unit/Codeception/Subscriber/ErrorHandlerTest.php

Fix compatibility with PHPUnit error expectations

---

src/Codeception/Command/DryRun.php
src/Codeception/Lib/Generator/Actions.php
src/Codeception/Step.php
tests/cli/DryRunCest.php
tests/data/typed_helper/codeception.yml
tests/data/typed_helper/tests/_output/.gitignore
tests/data/typed_helper/tests/_support/Helper/Unit.php
tests/data/typed_helper/tests/_support/UnitTester.php
tests/data/typed_helper/tests/_support/_generated/.gitignore
tests/data/typed_helper/tests/unit.suite.yml
tests/data/typed_helper/tests/unit/UseTypedHelperCest.php

Make dry-run work with module methods having return types

---

src/Codeception/Subscriber/BeforeAfterTest.php
tests/cli/OrderCest.php

Execute before/after class hooks only once

---

src/Codeception/Module.php
src/Codeception/Step.php

In test data providers, there may be binary data (example inet_pton result) that causes a json encoding error, since the JSON_THROW_ON_ERROR flag is added and strict_types=1 (by the way, this problem may occur in other Codeception modules, such as Codeception/module-db)

added support to binary data

---

src/Codeception/Test/Cest.php
src/Codeception/Test/Gherkin.php

Fixes #4947
[Unit format](https://github.com/Codeception/Codeception/blob/6021a4a7e7f7351a3c187ff6b8761f49a0d83ce6/src/Codeception/Test/Unit.php#L70-L77) injected dependencies to actor class already, so it was easy to make Gherkin and Cest formats work in the same way.

Inject dependencies to actor in Cest and Gherkin formats

---

readme.md
src/Codeception/Command/Run.php
tests/cli/DataProviderFailuresAndExceptionsCest.php

Initially Codeception was a wrapper for PHPUnit with additional test formats and modules. Test orchestration and reporting was performed by PHPUnit code.
This is no longer the case in Codeception 5, the role of PHPUnit was reduced to provider of assertions, also PHPUnit TestCase test format is supported. We use a few utility classes too - `PHPUnit\Runner\Version` class to implement compatibility with PHPUnit 9 and 10, `PHPUnit\Util\Test` to get linesToBeCovered and LinesToBeUsed and we catch and throw a few PHPUnit exceptions.
We use `phpunit/php-code-coverage` and `sebastian/diff` libraries too, but Codeception 5 is no longer powered by PHPUnit, we have our own engine :)

Not powered by PHPUnit

---

src/Codeception/Lib/Di.php

This change allows to simplify dependency injection and Cest format in the future.
Nobody should be using untyped method arguments in PHP 8 anyway, since they bring so many benefits.
It was surprise to me too that parameter types in Cest format are optional: 
`e.g. public function runSuitesWithoutActor($I)`
untyped methods are called with actor, scenario and example (if exampled are used) in that order.
This change makes Codeception log deprecation messages about Cest files with missing argument type declarations:
> DEPRECATION: Untyped method arguments in Cest format are deprecated since Codeception 5.0.0 and will be removed in 6.0.0 /.../Codeception/tests/cli/ConfigNoActorCest.php:11
> DEPRECATION: Untyped method arguments in Cest format are deprecated since Codeception 5.0.0 and will …

Deprecate untyped method arguments in Cest format

---

src/Codeception/Command/Completion.php

`class_exists(ConsoleCompletion::class)` return always **false** in position before import class namespaces. 
The output of this message provokes a problem with establishing a session and adding session handlers.
Like this: 
```                                                            
session_set_save_handler(): Session save handler cannot be changed after headers have already been sent  
```

Fixed false negative message about missing stecman/symfony-console-completion packege

---

src/Codeception/InitTemplate.php
src/Codeception/Template/Acceptance.php
src/Codeception/Template/Api.php
src/Codeception/Template/Unit.php
tests/unit/Codeception/Command/BuildTest.php

I tested template functionality and fixed 5 issues:
* Templates added incompatible versions of modules to composer.json
* `codecept init Acceptance` generated invalid codeception.yml file with 2 `support_namespace` settings
* `codecept init Api` generated codeception.yml with suite name `Api` and crashed (single suite commands all generate suite names in lowercase`.
* Acceptance, Api and Unit templates generated Actor files not in Support namespace.
* Acceptance and Api templates generated first test with incorrect `use` statement.
Fixes #6542 
Replaces #6545

Template patches

---

src/Codeception/Exception/Deprecation.php
src/Codeception/Exception/Error.php
src/Codeception/Exception/Notice.php
src/Codeception/Exception/Warning.php
src/Codeception/Subscriber/ErrorHandler.php
tests/cli/ErrorExpectationsCest.php
tests/unit/Codeception/Subscriber/ErrorHandlerTest.php

Error exceptions have been removed from PHPUnit 10,
Error expectations (`expectDeprecation*()`, `expectError*()`, `expectNotice*()`, and `expectWarning*()`) won't be supported
`expectException*()` can be used instead.
P.S. There is non-zero possibility that `expectException` will be broken later, if it happens we can reimplement all these methods in `Codeception\Test\Unit`, but method names must be different.
P.P.S. There is non-zero possibility that some future change will be so big that Codeception won't be able to support PHPUnit 10.

Fix PHPUnit 10 compatibility

---

src/Codeception/Configuration.php

Fixes #6533
Fixes #6519
If the test is namespaced, Suite basename is in dot separated format "NAMESPACE.SUITE", e.g. "Tests.acceptance".
When c3.php calls `Configuration::suiteSettings`, it removes namespace, but leaves the dot: https://github.com/Codeception/Codeception/blob/5.0.1/src/Codeception/Configuration.php#L332-L335
and throws exception `Suite .acceptance was not loaded`
Removing the dot solves the problem.

Fix remote code coverage for namespaced suites

---

src/Codeception/Test/Filter.php

Had some bug in my own custom command 
When we have included groups as an empty array and the test don't have any groups isGroupAccepted is always false. 
Example
```
count(array_intersect([], [])) === 0) 
```

Fixed issue when include groups and test groups empty

---

Dockerfile

The current `codeception/codeception` Docker image is huge (707.46 MB), I've tried to reduce the size a bit.
By utilizing https://github.com/mlocati/docker-php-extension-installer (which uninstalls unneccessary packages after extension install) and layer optimization I've created two flavors of the image:
* debian bullseye based: 486.36 MB (`docker pull djbasster/codeception:latest`)
* alpine based: 158.49 MB (`docker pull djbasster/codeception:latest-alpine`)
My images are also multi-arch images (amd64/arm64) to run natively on Apple Silicone, as well.
I've used the following script to build:
```bash
#!/usr/bin/env sh
architecture=$(arch)
image=djbasster/codeception:latest
if [ "$architecture" = "arm64" ] || [ "$CI" = true ]; then
docker buildx build \
--platform …
```

Docker Image Makeover

---

src/Codeception/Command/SelfUpdate.php

`file_get_contents(https://codeception.com/php73/codecept.version): Failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found`

Command: SelfUpdate -> try to fix "PHAR_URL"

---

.github/workflows/build.yml
src/Codeception/Exception/InvalidTestException.php
src/Codeception/Test/DataProvider.php
src/Codeception/Test/Filter.php
src/Codeception/Test/Loader/Unit.php
src/Codeception/Test/TestCaseWrapper.php
tests/cli/DataProviderFailuresAndExceptionsCest.php
tests/cli/RunCest.php
tests/data/dataprovider_failures_and_exceptions/tests/unit/InvalidDataProviderTest.php
tests/unit/Codeception/Test/DataProviderTest.php

Because it no longer exists in PHPUnit 10
Invalid or failing data provider will stop test execution immediately.
See https://github.com/sebastianbergmann/phpunit/commit/7ccf97c28f81e1edf6f9045ddf7a847a746bf3fe

PHPUnit 10 compatibility: Stop using ErrorTestCase in Unit Loader

---

src/Codeception/Test/Cest.php
src/Codeception/Test/Interfaces/StrictCoverage.php
src/Codeception/Test/TestCaseWrapper.php
tests/data/claypit/tests/math/MathTest.php

In projects where I don't use `@covers` annotations, `\PHPUnit\Util\Test::getLinesToBeCovered` can return `false`, and so it should `StrictCoverage::getLinesToBeCovered`: 
https://github.com/sebastianbergmann/phpunit/blob/3e6f90ca7e3d02025b1d147bd8d4a89fd4ca8a1d/src/Util/Test.php#L126
I didn't make it to have a test for it though: how can I generate code coverage locally so I can inspect the right place to put my test?

StrictCoverage::getLinesToBeCovered can return false

---

src/Codeception/Subscriber/FailFast.php

In a module I want to handle failures and see whether fail-fast is enabled or not. For example, extending the `Doctrine2` module to not cleanup when fail-fast is enabled so the state of the Doctrine data store can be introspected after a failure has occurred.
As it stands, modules catch `Events::TEST_FAIL` and `Events::TEST_ERROR` before the `FailFast` subscriber because modules are configured first.
A simple dump of the EventDispatcher's set of listeners for `test.fail` shows:
```php
"test.fail" => array:4 [
0 => Codeception\Subscriber\Module::failed(FailEvent $event): void^ {#28422
returnType: "void"
this: Codeception\Subscriber\Module^ {#308}
}
1 => Codeception\Subscriber\FailFast::stopOnFail(TestEvent $e): void^ {#28416
returnType: "void"
this: Codeception\Subscriber\FailFast {#318 …} …
```

Set event subscriber priority for failure events

---

src/Codeception/Test/Test.php
src/Codeception/Test/TestCaseWrapper.php
src/Codeception/Test/Unit.php

Don't override resultAggregator property in test formats

---

src/Codeception/Lib/Di.php

Because there is no better way to support type union.
Closes #6588

Undeprecate untyped method arguments in Cest format

---

src/Codeception/Reporter/HtmlReporter.php
src/Codeception/Suite.php
src/Codeception/Test/Test.php
tests/cli/RunCest.php

Print failure/error/warning/skipped/incomplete messages in HTML reports

---

src/Codeception/Test/Test.php
src/Codeception/Test/TestCaseWrapper.php
tests/cli/RunUselessTestsCest.php
tests/data/useless/tests/unit/UselessTest.php

I noticed that the PHPUnit TestCase method `expectNotToPerformAssertions()` wasn't being correctly applied by the TestCaseWrapper in Codeception. Unit tests with `expectNotToPerformAssertions` were being identified as useless tests, despite having informed the test runner that it does not perform assertions.
What I propose fixes the issue however it may not be the preferred way to do it. Happy to make alterations if required.
Side note, the test `RunUselessTestsCest:checkOutput` is failing because the `UselessCest` and `UselessCept` output isn't showing correctly in the test. Doesn't appear to be related but I'll make sure and fix in a subsequent commit if it it my fault.

Fixed 'expectNotToPerformAssertions override in unit tests

---

.github/workflows/build.yml
composer.json

This:
- Updates the version for several GitHub-branded actions from `v2` to `v3`.
- Consolidates the PHPCS commands into composer scripts so they can easily be run by devs before committing/pushing.
_(This was originally part of #6593, I have pulled it out into a separate PR to make things cleaner)_

Bump GitHub actions

---

composer.json
src/Codeception/Lib/Generator/Actions.php
tests/cli/BuildCest.php

This adds support for attributes in generated Action traits as discussed [here](https://github.com/Codeception/Codeception/issues/6592). This closes #6592.
- ~I've also tidied up a few CI-related things~ see #6604 instead.
- ~Added parameters to the attributes so IDEs don't complain about parameters being there when they think there shouldn't be~ see #6600 instead.

Support for Attributes in Actions

---

src/Codeception/Attribute/After.php
src/Codeception/Attribute/AfterClass.php
src/Codeception/Attribute/Before.php
src/Codeception/Attribute/BeforeClass.php
src/Codeception/Attribute/DataProvider.php
src/Codeception/Attribute/Depends.php
src/Codeception/Attribute/Env.php
src/Codeception/Attribute/Examples.php
src/Codeception/Attribute/Given.php
src/Codeception/Attribute/Group.php
src/Codeception/Attribute/Incomplete.php
src/Codeception/Attribute/Prepare.php
src/Codeception/Attribute/Skip.php
src/Codeception/Attribute/Then.php
src/Codeception/Attribute/When.php
tests/data/claypit/tests/unit/DependsTest.php

Hey there.
The current implementation of attributes does not include any signatures and thus IDEs like PhpStorm report that attributes accept no arguments and also provide no hints on the type or number of arguments supported.
I have added constructors with proper signatures to fix this.
Due to the way attributes are read, there is no further change needed.
Looking forward, it could be beneficial to make the passed in values available via getters instead of using `ReflectionAttribute::getArguments` in the code processing attributes. But that is for another time.

Provide typed signatures for attributes

---

src/Codeception/Command/Run.php

Don't disable test shuffling when --shard option is used

---

src/Codeception/SuiteManager.php
src/Codeception/Test/Unit.php
tests/cli/OrderCest.php
tests/data/claypit/tests/order/CanCantFailTest.php

Fix conditional assertions in Unit format

---

src/Codeception/Step/TryTo.php
tests/data/retries/tests/_support/Helper/Retry.php
tests/data/retries/tests/retry.suite.yml
tests/data/retries/tests/retry/TryToCest.php

tryTo methods must always return Boolean result

---

src/Codeception/Test/Metadata.php
tests/cli/RunSkippedCest.php
tests/data/skip/codeception.yml
tests/data/skip/tests/_output/.gitignore
tests/data/skip/tests/_support/UnitTester.php
tests/data/skip/tests/_support/_generated/.gitignore
tests/data/skip/tests/unit.suite.yml
tests/data/skip/tests/unit/ClassLevelSkipAnnotationWithMessageCest.php
tests/data/skip/tests/unit/ClassLevelSkipAnnotationWithoutMessageCest.php
tests/data/skip/tests/unit/ClassLevelSkipAttributeWithMessageCest.php
tests/data/skip/tests/unit/ClassLevelSkipAttributeWithoutMessageCest.php
tests/data/skip/tests/unit/MethodLevelSkipAnnotationWithMessageCest.php
tests/data/skip/tests/unit/MethodLevelSkipAnnotationWithoutMessageCest.php
tests/data/skip/tests/unit/MethodLevelSkipAttributeWithMessageCest.php
tests/data/skip/tests/unit/MethodLevelSkipAttributeWithoutMessageCest.php

Fixes #6615
This change ensures that `@skip` annotation and `#[Codeception\Attribute\Skip]` with and without message are handled correctly at class and method level.

Fix skip issues

---

src/Codeception/Command/Run.php

Fix depricated messages when running tests:
Deprecated: Using ${var} in strings is deprecated, use {$var} instead in ../vendor/codeception/codeception/src/Codeception/Command/Run.php on line 422
Deprecated: Using ${var} in strings is deprecated, use {$var} instead in ../vendor/codeception/codeception/src/Codeception/Command/Run.php on line 505

Update Run.php (Fix depricated messages when running tests)

---

src/Codeception/Template/Bootstrap.php

Enable the same decorators for Acceptance tester as in codecept init Acceptance

Use correct indentation of step_decorators in bootstrap command

---

composer.json
src/Codeception/ResultAggregator.php
src/Codeception/Scenario.php
src/Codeception/Subscriber/Console.php
src/Codeception/Test/Cept.php
src/Codeception/Test/Cest.php
src/Codeception/Test/Gherkin.php
src/Codeception/Test/Test.php
src/Codeception/Test/TestCaseWrapper.php
src/Codeception/Test/Unit.php
tests/cli/OrderCest.php
tests/cli/RunCest.php
tests/data/claypit/tests/_support/Helper/Scenario.php
tests/data/claypit/tests/_support/ScenarioGuy.php
tests/data/claypit/tests/scenario.suite.yml
tests/data/claypit/tests/scenario/FailureAndExceptionCest.php
tests/data/claypit/tests/scenario/MultipleConditionalFailsCest.php

Fixed #5820 and probably many other reports about incorrect failed step output
The problem with `$failedStep = (string)array_shift($this->failedStep);` in [src/Codeception/Subscriber/Console.php](https://github.com/Codeception/Codeception/compare/fix-failed-step-output?expand=1#diff-a66d9a47f594bb583f325ea19ee1505d50f22bc4c8232cbf025dffd8ec9a8282) was that all failed steps are added to that array in order of test execution, but errors are printed before failures and order of printing doesn't match order of execution.

Fix failed step output

---

src/Codeception/Command/CompletionFallback.php

I don't have `stecman/symfony-console-completion` package, so Symfony 6.2 throws deprecated error:
```
PHP Deprecated: Since symfony/console 6.1: Relying on the static property "$defaultName" for setting a command name is deprecated. Add the "Symfony\Component\Console\Attribute\AsCommand" attribute to the "Codeception\Command\CompletionFallback" class instead. in /var/www/vendor/symfony/deprecation-contracts/function.php on line 25
```
I think we can skip using `AsCommand` since it have constructor variable for it and supported by all Symfony versions.

Fix static $defaultName deprecated

---

src/Codeception/Reporter/JUnitReporter.php
tests/cli/RunCest.php

JUnitReporter: Do not set 'useless' testsuite attribute in strict mode

---

.github/workflows/build.yml
composer.json

I noticed that Github Actions build was downloading 1.1G of composer files from cache because Github action runs `composer update --prefer-source`.
We need the source, because CI runs tests of module-asserts, module-db, module-filesystem, module-phpbrowser.
On my computer vendor dir was actually 1.3G large.
`composer update --prefer-dist` reduced the size of vendor dir to 19G, but it removed tests of the 4 modules that we care about.
Setting `preferred-install` `source` for these 4 modules increased the size of vendor dir to 22M, but it is very good improvement from 1.1 - 1.3 G.
Cache size was reduced from 1.1G to 4.2M

Reduce the size of vendor dir in Github Actions

---

ext/Recorder.php

Added a missing null coalescing operator when accessing $this->dir in persists in Reporter.pho - resolves #6642

[BUGFIX] #6642 Added a missing null coalescing operator 

---

src/Codeception/Reporter/JUnitReporter.php

`hasOutput()` method was renamed to `hasUnexpectedOutput()` in PHPUnit 10.0.16, but we don't have to use it, because it only checks if output is not empty and expectation on output is not set.
Fixes #6654

Fix JUnitReporter compatibility with PHPUnit 10.0.16

---

src/Codeception/Test/Loader.php

A file without tests will cause sharding to break:
```sh
Fatal error: Uncaught ValueError: array_chunk(): Argument #2 ($length) must be greater than 0 in /project/vendor/codeception/codeception/src/Codeception/Test/Loader.php:109
Stack trace:
#0 /project/vendor/codeception/codeception/src/Codeception/Test/Loader.php(109): array_chunk(Array, 0)
#1 /project/vendor/codeception/codeception/src/Codeception/Test/Loader.php(100): Codeception\Test\Loader->splitTestsIntoChunks(4)
#2 /project/vendor/codeception/codeception/src/Codeception/SuiteManager.php(86): Codeception\Test\Loader->getTests()
#3 /project/vendor/codeception/codeception/src/Codeception/Codecept.php(258): Codeception\SuiteManager->loadTests(NULL)
#4 /project/vendor/codeception/codeception/src/Codeception/Codecept.php(216): …
```

fix sharding for empty tests file

---

composer.json
src/Codeception/Test/Test.php
src/Codeception/Test/TestCaseWrapper.php
tests/cli/RunUselessTestsCest.php
tests/data/useless/tests/unit/UselessTest.php

This fixes #6671.
The fix works for both PHPUnit and Codeception mocking methods. It also works when using a external mocking library like Mockery.

Include mock expectations in assertion count 

---

src/Codeception/Test/Cest.php

The Depends attribute can be added multiple times to tests now to indicate dependencies on various other tests.
Fixes #6675

Allow multiple test dependencies

---

src/Codeception/Coverage/Subscriber/LocalServer.php

This PR works in conjunction with https://github.com/Codeception/c3/pull/90 and fixes incomplete Code Coverage issues with Acceptance Testing as described in https://github.com/Codeception/c3/issues/89.

Wait for all tests to finish before accessing the serialized test results

---

src/Codeception/Test/Descriptor.php

feat: Support binary data

---

src/Codeception/Coverage/Subscriber/LocalServer.php
tests/data/claypit/c3.php

This could potentially close #6709 but on the other hand it might result in truncated reports again. This would happen if the accumulated runtime of the [registered shutdown functions in c3.php](https://github.com/Codeception/c3/blob/e23298a1cd5e7745973ea26a53572a3d9b013439/c3.php#L416) exceeds 10 * 0.25 = 2.5 sec which seems possible.
Maybe a bigger value for `retries` is necessary.

Avoid infinite loop while waiting for all running tests to finish

---

src/Codeception/Command/Shared/ActorTrait.php
src/Codeception/SuiteManager.php
src/Codeception/Test/DataProvider.php
src/Codeception/Test/Loader.php
src/Codeception/Test/Loader/Cest.php
tests/data/data_provider/DataProviderReceivesActorTest.php
tests/support/CodeGuy.php
tests/unit/Codeception/Test/DataProviderTest.php

It makes possible to use actors inside dataProviders. It's a very useful functionality, during testing it happens that data need to be retrieved ie.: from the database, but it's not possible to use it with the current solution. There was a discussion about it in the past: #4087 
I am not sure if I implemented it in the correct way, I am new to Codeception and open source contribution as well. What do you think of it @DavertMik?

Add actor to Cest tests dataProviders

---

src/Codeception/Lib/ModuleContainer.php

The Doctrine2 module was replaced by the Doctrine module which adds support for newer Doctrine versions while keeping compatibility with Doctrine ORMv2/DBALv3.
See https://github.com/Codeception/module-doctrine/pull/28

Replace Doctrine2 with Doctrine module

---

src/Codeception/ResultAggregator.php
src/Codeception/Test/Test.php
tests/cli/RunCest.php
tests/data/claypit/tests/scenario/ExpectedFailureTest.php

This fixes https://github.com/Codeception/Codeception/issues/6716 which results in incorrect test failures being reported where a scenario has a failed assertion that has been caught within the test itself or via `expectException`

Prevent unrelated error from being displayed if a scenario step has failed

---

src/Codeception/Reporter/ReportPrinter.php

Closes #6740
When I run `codecept run --report --no-ansi` there is still color output  
So I fixed it by removing extra chars in `ReportPrinter::testFailure`, I think it just typo

Fix  FAIL message color highlighting

---

.github/workflows/build.yml
src/Codeception/Configuration.php
src/Codeception/Subscriber/ErrorHandler.php
tests/unit.suite.yml

PHP 8.4 deprecates the `E_STRICT` error level constant.
RFC: https://wiki.php.net/rfc/deprecations_php_8_4#remove_e_strict_error_level_and_deprecate_e_strict_constant
This PR removes the constant from the internal test suite and the default configuration.
For the error handler the constant is only used for PHP 8.3 or lower.
Furthermore, tests against PHP 8.4 are enabled in the CI.

PHP 8.4: `E_STRICT` deprecation

---

composer.json
src/Codeception/Test/Loader/Gherkin.php

Fixes https://github.com/Codeception/Codeception/issues/6833
Replaces https://github.com/Codeception/Codeception/pull/6836
I overlooked that the release notes https://github.com/Behat/Gherkin/releases/tag/v4.12.0 already suggest a simple way to load the keywords independently from the file path:
> Provide CachedArrayKeywords::withDefaultKeywords() to create an instance without an external dependency on the path to the i18n.php file in this repo. NOTE that paths to source files will change in the next Gherkin release - use the new constructor to avoid any impact.
This PR uses this approach and bumps the minimum version of `behat/gherkin` to 4.12 which should be okay because this version does still support PHP 8.1 which is also the case for codeception v5.

Fix loading keywords in behat/gherkin v4.12

---

src/Codeception/Scenario.php

`->current()` is mentioned at https://codeception.com/docs/AdvancedUsage
So if you don't merge this, the docs need to be changed to `->current(null)`

Update Scenario.php: Adding default value to `current()`

---

composer.json

Fixes https://github.com/Codeception/module-asserts/pull/29#issuecomment-2828563411
The latest version of `codeception/module-asserts` contains unit tests for all assertions provided by this module.
However, they only work with `codeception/lib-asserts:2.2` because this version contains various compatibility fixes for newer PHPUnit versions.
That's why this PR bumps the `codeception/lib-asserts` version to 2.2 order to make the CI green again.

Fix AssertsTest CI pipeline
